"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { supabase, say } from "../../lib/supabase";
import { Nav, requireTenant } from "../shell";

function humanType(t){if(!t)return"Event";return String(t).replace(/^analytic_/,"").replaceAll("_"," ").replace(/\b\w/g,(c)=>c.toUpperCase());}
function ago(ts){if(!ts)return"unknown";const s=Math.max(0,Math.round((Date.now()-Date.parse(ts))/1000));if(s<60)return`${s}s ago`;if(s<3600)return`${Math.round(s/60)}m ago`;if(s<86400)return`${Math.round(s/3600)}h ago`;return`${Math.round(s/86400)}d ago`;}
function exact(ts,timeZone){if(!ts)return"";try{return new Intl.DateTimeFormat("en-PK",{timeZone:timeZone||"Asia/Karachi",day:"numeric",month:"short",year:"numeric",hour:"numeric",minute:"2-digit",hour12:true}).format(new Date(ts))+" · site time"}catch{return String(ts||"")}}
function clock(ts,timeZone){if(!ts)return"";try{return new Intl.DateTimeFormat("en-PK",{timeZone:timeZone||"Asia/Karachi",hour:"numeric",minute:"2-digit",hour12:true}).format(new Date(ts))}catch{return""}}
function sourceLabel(row){if(row?.native_ai)return"Recorder AI";if(row?.event_source==="watchlog_local_ai")return"WatchLog local AI";return"Recorder event";}
function clipLabel(status){if(!status)return"Not requested";return({pending:"Queued",processing:"Retrieving",ready:"Ready",unsupported:"Unsupported",failed:"Failed",expired:"Expired"})[status]||humanType(status);}
function bytesLabel(value){const n=Number(value||0);if(!n)return"";if(n<1024*1024)return`${Math.round(n/1024)} KB`;return`${(n/1024/1024).toFixed(1)} MB`;}
function decodeB64(value){const raw=atob(value||"");const out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i+=1)out[i]=raw.charCodeAt(i);return out;}
async function digestHex(blob){if(!globalThis.crypto?.subtle)throw new Error("This browser cannot verify the footage checksum. Use a current browser and try again.");const digest=await crypto.subtle.digest("SHA-256",await blob.arrayBuffer());return Array.from(new Uint8Array(digest)).map((b)=>b.toString(16).padStart(2,"0")).join("");}

export default function Incidents(){
  const[email,setEmail]=useState(""),[rows,setRows]=useState(null),[sites,setSites]=useState([]),[err,setErr]=useState(""),[days,setDays]=useState(7),[site,setSite]=useState(""),[type,setType]=useState(""),[selected,setSelected]=useState(null),[role,setRole]=useState("viewer"),[clip,setClip]=useState(null),[clipBusy,setClipBusy]=useState(false),[clipNote,setClipNote]=useState("");
  const shots=useRef(new Map());const[,force]=useState(0);
  const load=useCallback(async(d,s,t)=>{const g=await requireTenant();if(!g)return;setEmail(g.session.user.email||"");const sb=supabase();const[inc,si,me]=await Promise.all([sb.rpc("wl_incidents",{p_days:d,p_site:s||null,p_type:t||null}),sb.rpc("wl_sites"),sb.rpc("wl_my_role")]);if(inc.error||si.error||me.error){setErr(say(inc.error||si.error||me.error));return;}setErr("");setRows(inc.data||[]);setSites(si.data||[]);setRole(me.data||"viewer");},[]);
  useEffect(()=>{load(days,site,type);},[days,site,type,load]);
  async function loadShot(eventId){if(shots.current.has(eventId))return;shots.current.set(eventId,null);const{data}=await supabase().rpc("wl_portal_snapshot",{p_event_id:eventId});shots.current.set(eventId,data?.image_b64?`data:${data.content_type||"image/jpeg"};base64,${data.image_b64}`:false);force((n)=>n+1);}
  useEffect(()=>{(rows||[]).filter((r)=>r.has_snapshot).slice(0,24).forEach((r)=>loadShot(r.event_id));},[rows]);
  useEffect(()=>{if(!rows?.length){setSelected(null);return;}setSelected((cur)=>cur&&rows.some((r)=>r.event_id===cur.event_id)?rows.find((r)=>r.event_id===cur.event_id):rows[0]);},[rows]);
  useEffect(()=>{if(selected?.has_snapshot)loadShot(selected.event_id);},[selected]);
  const refreshClip=useCallback(async(eventId)=>{if(!eventId){setClip(null);return;}const{data,error}=await supabase().rpc("wl_incident_clip_status",{p_event_id:eventId});if(error){if(/wl_incident_clip_status|schema cache|function/i.test(error.message||"")){setClip(null);return;}setClipNote(say(error));return;}setClip(data||null);},[]);
  useEffect(()=>{setClip(null);setClipNote("");if(selected?.event_id)refreshClip(selected.event_id);},[selected?.event_id,refreshClip]);
  useEffect(()=>{if(!selected?.event_id||!(clip?.status==="pending"||clip?.status==="processing"))return;const timer=setInterval(()=>refreshClip(selected.event_id),5000);return()=>clearInterval(timer);},[clip?.status,selected?.event_id,refreshClip]);
  const types=Array.from(new Set((rows||[]).map((r)=>r.event_type))).sort();
  function zoneFor(row){const id=row?.site_id||site;return sites.find(s=>String(s.id)===String(id))?.timezone||"Asia/Karachi"}
  const selectedZone=zoneFor(selected);
  const canRequest=role==="owner"||role==="admin";

  async function requestFootage(){if(!selected?.event_id||!canRequest)return;setClipBusy(true);setClipNote("");const{error}=await supabase().rpc("wl_request_incident_clip",{p_event_id:selected.event_id,p_pre_seconds:10,p_post_seconds:20});if(error){setClipNote(say(error));setClipBusy(false);return;}await refreshClip(selected.event_id);setClipNote("WatchLog requested a short evidence window around this camera event.");setClipBusy(false);}

  async function downloadFootage(){if(!clip?.request_id||clip.status!=="ready")return;setClipBusy(true);setClipNote("Preparing the temporary evidence footage download…");try{const parts=[];for(let seq=0;seq<Number(clip.chunks||0);seq+=1){const{data,error}=await supabase().rpc("wl_incident_clip_chunk",{p_request_id:clip.request_id,p_sequence_no:seq});if(error||!data?.data_b64)throw error||new Error(`Missing footage chunk ${seq}`);parts.push(decodeB64(data.data_b64));}if(!parts.length)throw new Error("No footage data is available.");const blob=new Blob(parts,{type:clip.content_type||"application/octet-stream"});if(Number(clip.bytes||0)>0&&blob.size!==Number(clip.bytes))throw new Error("Footage size check failed. Request it again.");if(!clip.sha256)throw new Error("Footage checksum is missing. Request it again.");const digest=await digestHex(blob);if(digest!==clip.sha256)throw new Error("Footage integrity check failed. Request it again.");const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=`WatchLog-evidence-${selected.event_id}.${clip.file_extension||"dav"}`;document.body.appendChild(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setClipNote(`Downloaded ${bytesLabel(blob.size)} of evidence footage. The temporary copy expires automatically.`);}catch(error){setClipNote(say(error));}finally{setClipBusy(false);}}

  return <div className="shell"><Nav active="Control Room" email={email}/><main className="main">
    <header className="target-page-head"><div><div className="target-eyebrow">Camera evidence</div><h1>Review camera events and supporting evidence</h1><p>Review event moments, images and requested footage without treating every camera event as an incident.</p></div></header>
    {err&&<div className="err">{err}</div>}
    <section className="panel incident-filterbar" aria-label="Camera evidence filters"><div className="field"><label>Site</label><select value={site} onChange={(e)=>setSite(e.target.value)}><option value="">All sites</option>{sites.map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div className="field"><label>Type</label><select value={type} onChange={(e)=>setType(e.target.value)}><option value="">All types</option>{types.map((t)=><option key={t} value={t}>{humanType(t)}</option>)}</select></div><div className="field"><label>Date range</label><select value={days} onChange={(e)=>setDays(Number(e.target.value))}><option value={1}>Last 24 hours</option><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option></select></div><div className="incident-count">{rows===null?"Loading...":<><strong>{rows.length}</strong>event{rows.length===1?"":"s"}</>}</div></section>

    {rows===null?<div className="panel"><div className="empty">Loading camera evidence...</div></div>:rows.length===0?<div className="panel"><div className="empty">No reviewable camera events are available for this period. This does not make a claim about unverified time.</div></div>:<section className="incident-workspace">
      <div className="panel"><div className="target-panel-title"><div><h2>Camera event history</h2><p>Select a moment to review the supporting evidence.</p></div></div><div className="incident-list">{rows.map((r)=>{const shot=shots.current.get(r.event_id),isSelected=selected?.event_id===r.event_id,tz=zoneFor(r);return <button type="button" className={`incident-item${isSelected?" selected":""}`} key={r.event_id} onClick={()=>setSelected(r)} aria-pressed={isSelected}>{r.has_snapshot&&typeof shot==="string"?<img className="incident-thumb" src={shot} alt={`still from ${r.camera||"camera"}`}/>:<span className="incident-thumb incident-thumb-empty">{r.has_snapshot?(shot===false?"unavailable":"loading"):"no image"}</span>}<span className="incident-item-meta"><strong>{clock(r.device_ts,tz)} · {r.camera||"Unassigned camera"}</strong><span>{r.site}</span><span title={exact(r.device_ts,tz)}>{ago(r.device_ts)}</span></span><span className="incident-type">{humanType(r.event_type)}</span></button>;})}</div></div>
      <article className="panel incident-detail" aria-live="polite">{selected?<div className="incident-detail-body"><h2 className="incident-title">{selected.camera||"Unassigned camera"} - {humanType(selected.event_type)}</h2><div className="incident-sub">{selected.site} · {clock(selected.device_ts,selectedZone)} · {ago(selected.device_ts)}</div><div className="incident-frame">{selected.has_snapshot?(typeof shots.current.get(selected.event_id)==="string"?<img src={shots.current.get(selected.event_id)} alt={`Evidence still from ${selected.camera||"camera"}`}/>:<div className="incident-frame-empty">{shots.current.get(selected.event_id)===false?"This evidence image is unavailable.":"Loading the evidence image..."}</div>):<div className="incident-frame-empty">This camera event does not have an image.</div>}</div><div className="incident-meta-grid"><div className="incident-meta-item"><small>Camera</small><b>{selected.camera||"Unassigned"}</b></div><div className="incident-meta-item"><small>Activity</small><b>{humanType(selected.event_type)}</b></div><div className="incident-meta-item"><small>Source</small><b>{sourceLabel(selected)}</b></div><div className="incident-meta-item"><small>Evidence state</small><b>Available for review</b></div><div className="incident-meta-item"><small>Recorded</small><b>{exact(selected.device_ts,selectedZone)}</b></div><div className="incident-meta-item"><small>Site</small><b>{selected.site}</b></div></div>
        <section className="panel" style={{marginTop:16,padding:16}}><div style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"center",flexWrap:"wrap"}}><div><div className="target-eyebrow">Evidence footage</div><h3 style={{margin:"5px 0"}}>{clipLabel(clip?.status)}</h3><p className="muted" style={{margin:0,maxWidth:560}}>{clip?.status==="ready"?`A temporary ${bytesLabel(clip.bytes)} evidence file is ready. It expires ${exact(clip.expires_at,selectedZone)}.`:clip?.status==="processing"?"WatchLog is retrieving the requested time window from the camera system.":clip?.status==="pending"?"The footage request is waiting for the site to respond.":clip?.status==="unsupported"?"This recorder did not provide footage for this request.":clip?.status==="failed"?(clip.error_message||"The recorder could not provide this footage window."):clip?.status==="expired"?"The temporary evidence copy expired. The original CCTV recording remains on the recorder.":"WatchLog can request a short recording window around this camera event without continuously streaming CCTV video."}</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{clip?.status==="ready"?<button className="small" disabled={clipBusy} onClick={downloadFootage}>{clipBusy?"Preparing…":"Download footage"}</button>:canRequest&&!(clip?.status==="pending"||clip?.status==="processing")?<button className="small" disabled={clipBusy} onClick={requestFootage}>{clipBusy?"Requesting…":clip?.status==="expired"||clip?.status==="failed"||clip?.status==="unsupported"?"Request again":"Retrieve footage"}</button>:null}{(clip?.status==="pending"||clip?.status==="processing")&&<button className="secondary small" onClick={()=>refreshClip(selected.event_id)}>Check status</button>}</div></div>{!canRequest&&<p className="muted" style={{fontSize:11,marginTop:10}}>Owners and Admins can request recorder footage. Viewer access remains read-only.</p>}{clipNote&&<div className="muted" style={{fontSize:12,marginTop:10}}>{clipNote}</div>}</section>
        <p className="incident-note">The evidence image is available for review. Normal CCTV recording remains on the recorder. Footage retrieval is explicit and on demand; WatchLog does not continuously stream recorder video as its normal workflow.</p></div>:<div className="empty">Select a camera event to review its evidence.</div>}</article>
    </section>}
  </main></div>;
}
