"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { supabase, say } from "../../lib/supabase";
import { Nav, requireTenant } from "../shell";

function humanType(t){if(!t)return"Event";return String(t).replace(/^analytic_/,"").replaceAll("_"," ").replace(/\b\w/g,(c)=>c.toUpperCase());}
function ago(ts){if(!ts)return"unknown";const s=Math.max(0,Math.round((Date.now()-Date.parse(ts))/1000));if(s<60)return`${s}s ago`;if(s<3600)return`${Math.round(s/60)}m ago`;if(s<86400)return`${Math.round(s/3600)}h ago`;return`${Math.round(s/86400)}d ago`;}
function exact(ts){try{return new Date(ts).toLocaleString();}catch{return String(ts||"");}}
function clock(ts){try{return new Date(ts).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"});}catch{return"";}}

export default function Incidents(){
  const[email,setEmail]=useState(""),[rows,setRows]=useState(null),[sites,setSites]=useState([]),[err,setErr]=useState(""),[days,setDays]=useState(7),[site,setSite]=useState(""),[type,setType]=useState(""),[selected,setSelected]=useState(null);
  const shots=useRef(new Map());const[,force]=useState(0);
  const load=useCallback(async(d,s,t)=>{const g=await requireTenant();if(!g)return;setEmail(g.session.user.email||"");const sb=supabase();const[inc,si]=await Promise.all([sb.rpc("wl_incidents",{p_days:d,p_site:s||null,p_type:t||null}),sb.rpc("wl_sites")]);if(inc.error||si.error){setErr(say(inc.error||si.error));return;}setErr("");setRows(inc.data||[]);setSites(si.data||[]);},[]);
  useEffect(()=>{load(days,site,type);},[days,site,type,load]);
  async function loadShot(eventId){if(shots.current.has(eventId))return;shots.current.set(eventId,null);const{data}=await supabase().rpc("wl_portal_snapshot",{p_event_id:eventId});shots.current.set(eventId,data?.image_b64?`data:${data.content_type||"image/jpeg"};base64,${data.image_b64}`:false);force((n)=>n+1);}
  useEffect(()=>{(rows||[]).filter((r)=>r.has_snapshot).slice(0,24).forEach((r)=>loadShot(r.event_id));},[rows]);
  useEffect(()=>{if(!rows?.length){setSelected(null);return;}setSelected((cur)=>cur&&rows.some((r)=>r.event_id===cur.event_id)?rows.find((r)=>r.event_id===cur.event_id):rows[0]);},[rows]);
  useEffect(()=>{if(selected?.has_snapshot)loadShot(selected.event_id);},[selected]);
  const types=Array.from(new Set((rows||[]).map((r)=>r.event_type))).sort();

  return <div className="shell"><Nav active="Incidents" email={email}/><main className="main">
    <header className="target-page-head"><div><div className="target-eyebrow">Incident review</div><h1>Only what is worth reviewing.</h1><p>People, vehicles, motorcycles and selected analytics incidents, with the image and context your team needs to understand the moment.</p></div></header>
    {err&&<div className="err">{err}</div>}
    <section className="panel incident-filterbar" aria-label="Incident filters"><div className="field"><label>Site</label><select value={site} onChange={(e)=>setSite(e.target.value)}><option value="">All sites</option>{sites.map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div className="field"><label>Type</label><select value={type} onChange={(e)=>setType(e.target.value)}><option value="">All types</option>{types.map((t)=><option key={t} value={t}>{humanType(t)}</option>)}</select></div><div className="field"><label>Date range</label><select value={days} onChange={(e)=>setDays(Number(e.target.value))}><option value={1}>Last 24 hours</option><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option></select></div><div className="incident-count">{rows===null?"Loading...":<><strong>{rows.length}</strong>incident{rows.length===1?"":"s"}</>}</div></section>

    {rows===null?<div className="panel"><div className="empty">Loading incident history...</div></div>:rows.length===0?<div className="panel"><div className="empty">No incidents in this period. WatchLog keeps quiet periods quiet instead of filling them with routine camera activity.</div></div>:<section className="incident-workspace">
      <div className="panel"><div className="target-panel-title"><div><h2>Incident history</h2><p>Select a moment to review it.</p></div></div><div className="incident-list">{rows.map((r)=>{const shot=shots.current.get(r.event_id),isSelected=selected?.event_id===r.event_id;return <button type="button" className={`incident-item${isSelected?" selected":""}`} key={r.event_id} onClick={()=>setSelected(r)} aria-pressed={isSelected}>{r.has_snapshot&&typeof shot==="string"?<img className="incident-thumb" src={shot} alt={`still from ${r.camera||"camera"}`}/>:<span className="incident-thumb incident-thumb-empty">{r.has_snapshot?(shot===false?"unavailable":"loading"):"no image"}</span>}<span className="incident-item-meta"><strong>{clock(r.device_ts)} · {r.camera||"Unassigned camera"}</strong><span>{r.site}</span><span title={exact(r.device_ts)}>{ago(r.device_ts)}</span></span><span className="incident-type">{humanType(r.event_type)}</span></button>;})}</div></div>
      <article className="panel incident-detail" aria-live="polite">{selected?<div className="incident-detail-body"><h2 className="incident-title">{selected.camera||"Unassigned camera"} - {humanType(selected.event_type)}</h2><div className="incident-sub">{selected.site} · {clock(selected.device_ts)} · {ago(selected.device_ts)}</div><div className="incident-frame">{selected.has_snapshot?(typeof shots.current.get(selected.event_id)==="string"?<img src={shots.current.get(selected.event_id)} alt={`Incident still from ${selected.camera||"camera"}`}/>:<div className="incident-frame-empty">{shots.current.get(selected.event_id)===false?"This incident image is unavailable.":"Loading the incident image..."}</div>):<div className="incident-frame-empty">This incident does not have an image.</div>}</div><div className="incident-meta-grid"><div className="incident-meta-item"><small>Camera</small><b>{selected.camera||"Unassigned"}</b></div><div className="incident-meta-item"><small>Detected</small><b>{humanType(selected.event_type)}</b></div><div className="incident-meta-item"><small>Source</small><b>{selected.site}</b></div><div className="incident-meta-item"><small>Review state</small><b>WatchLog incident</b></div><div className="incident-meta-item"><small>Recorded</small><b>{exact(selected.device_ts)}</b></div><div className="incident-meta-item"><small>Site</small><b>{selected.site}</b></div></div><p className="incident-note">This incident includes a captured image for review. Your normal CCTV recording remains available through your own camera system.</p></div>:<div className="empty">Select an incident to review it.</div>}</article>
    </section>}
  </main></div>;
}
