"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { supabase, say } from "../../lib/supabase";
import { Nav, requireTenant } from "../shell";
import { rememberSite, selectedSiteId, withSite } from "../site-context";
import Mark from "../mark";

function human(v){return String(v||"Activity").replace(/^analytic_/,"").replaceAll("_"," ").replace(/\b\w/g,(c)=>c.toUpperCase());}
function ago(ts){if(!ts)return"Unknown time";const s=Math.max(0,Math.round((Date.now()-Date.parse(ts))/1000));if(s<60)return`${s}s ago`;if(s<3600)return`${Math.round(s/60)}m ago`;if(s<86400)return`${Math.round(s/3600)}h ago`;return`${Math.round(s/86400)}d ago`;}
function exact(ts){try{return new Date(ts).toLocaleString();}catch{return String(ts||"");}}
function source(row){if(row?.event_source==="recorder_archive")return"Recovered from recorder";if(row?.event_source==="watchlog_local_ai")return"WatchLog local AI";if(row?.native_ai)return"Recorder AI";return"Recorder event";}

export default function IncidentWorkspace(){
  const[email,setEmail]=useState(""),[sites,setSites]=useState([]),[siteId,setSiteId]=useState(""),[days,setDays]=useState(7),[type,setType]=useState(""),[rows,setRows]=useState(null),[selected,setSelected]=useState(null),[shots,setShots]=useState({}),[answer,setAnswer]=useState(""),[askBusy,setAskBusy]=useState(false),[error,setError]=useState("");
  const loaded=useRef(new Set());
  const loadBase=useCallback(async()=>{const g=await requireTenant();if(!g)return;setEmail(g.session.user.email||"");const s=await supabase().rpc("wl_sites");if(s.error){setError(say(s.error));return;}const list=s.data||[];setSites(list);const preferred=new URLSearchParams(window.location.search).get("site")||selectedSiteId()||list[0]?.id||"";if(preferred){setSiteId(preferred);rememberSite(preferred,list.find((x)=>x.id===preferred)?.name||"");}},[]);
  const loadIncidents=useCallback(async()=>{if(!siteId)return;const{data,error}=await supabase().rpc("wl_incidents",{p_days:days,p_site:siteId,p_type:type||null});if(error){setError(say(error));return;}const list=data||[];setRows(list);setSelected((cur)=>cur&&list.some((x)=>x.event_id===cur.event_id)?list.find((x)=>x.event_id===cur.event_id):list[0]||null);setError("");},[siteId,days,type]);
  useEffect(()=>{loadBase();},[loadBase]);useEffect(()=>{loadIncidents();},[loadIncidents]);
  useEffect(()=>{let live=true;(async()=>{for(const r of (rows||[]).filter((x)=>x.has_snapshot).slice(0,24)){if(loaded.current.has(r.event_id))continue;loaded.current.add(r.event_id);const{data}=await supabase().rpc("wl_portal_snapshot",{p_event_id:r.event_id});if(!live)return;setShots((m)=>({...m,[r.event_id]:data?.image_b64?`data:${data.content_type||"image/jpeg"};base64,${data.image_b64}`:false}));}})();return()=>{live=false;};},[rows]);
  function choose(id){setSiteId(id);setSelected(null);setAnswer("");loaded.current.clear();setShots({});rememberSite(id,sites.find((s)=>s.id===id)?.name||"");history.replaceState(null,"",`/incidents/?site=${encodeURIComponent(id)}`);}
  async function askAboutIncident(){if(!selected||askBusy)return;setAskBusy(true);setAnswer("");const prompt=`Explain this WatchLog incident in plain language and tell me what needs attention. Incident type: ${selected.event_type||"activity"}. Camera: ${selected.camera||"unknown"}. Occurred: ${selected.device_ts||"unknown"}. Evidence source: ${source(selected)}. Do not invent details that are not supported by WatchLog data.`;const{data,error}=await supabase().functions.invoke("watchlog-ai",{body:{prompt,site_id:siteId,conversation_id:null}});setAskBusy(false);if(error||data?.error){setError(data?.message||say(error));return;}setAnswer(data.answer||"");}
  const types=Array.from(new Set((rows||[]).map((r)=>r.event_type).filter(Boolean))).sort();const site=sites.find((s)=>s.id===siteId);

  return <div className="shell"><Nav active="Incidents" email={email} currentSiteId={siteId}/><main className="main">
    <header className="target-page-head"><div><div className="target-eyebrow">Incidents</div><h1>{site?.name||"Site"} security review</h1><p>Only moments worth reviewing, with evidence and provenance. Routine camera activity stays out of the way.</p></div><div className="target-actions"><select value={siteId} onChange={(e)=>choose(e.target.value)}>{sites.map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={days} onChange={(e)=>setDays(Number(e.target.value))}><option value={1}>24 hours</option><option value={7}>7 days</option><option value={30}>30 days</option><option value={90}>90 days</option></select></div></header>
    {error&&<div className="err">{error}</div>}
    <div className="incident-quick-filter"><button className={!type?"active":""} onClick={()=>setType("")}>All</button>{types.slice(0,6).map((t)=><button key={t} className={type===t?"active":""} onClick={()=>setType(t)}>{human(t)}</button>)}</div>
    {rows===null?<div className="panel"><div className="empty">Loading incidents for this site…</div></div>:rows.length===0?<div className="panel"><div className="empty"><b>No incidents in this period.</b><p>WatchLog keeps quiet periods quiet. Use the AI workspace if you want a broader activity summary.</p></div></div>:<section className="incident-workspace">
      <div className="panel"><div className="target-panel-title"><div><h2>Needs review</h2><p>{rows.length} incident{rows.length===1?"":"s"} in this period</p></div></div><div className="incident-list">{rows.map((r)=>{const shot=shots[r.event_id],active=selected?.event_id===r.event_id;return <button type="button" className={`incident-item${active?" selected":""}`} key={r.event_id} onClick={()=>{setSelected(r);setAnswer("");}}>{r.has_snapshot&&typeof shot==="string"?<img className="incident-thumb" src={shot} alt={`Incident still from ${r.camera||"camera"}`}/>:<span className="incident-thumb incident-thumb-empty">{r.has_snapshot?(shot===false?"unavailable":"loading"):"no image"}</span>}<span className="incident-item-meta"><strong>{r.camera||"Unassigned camera"}</strong><span>{human(r.event_type)} · {ago(r.device_ts)}</span><span>{source(r)}</span></span></button>;})}</div></div>
      <article className="panel incident-detail">{selected?<div className="incident-detail-body"><div className="target-eyebrow">Incident detail</div><h2 className="incident-title">{human(selected.event_type)}</h2><div className="incident-sub">{selected.camera||"Unassigned camera"} · {exact(selected.device_ts)}</div><div className="incident-frame">{selected.has_snapshot&&typeof shots[selected.event_id]==="string"?<img src={shots[selected.event_id]} alt={`Evidence from ${selected.camera||"camera"}`}/>:<div className="incident-frame-empty">{selected.has_snapshot?"Loading evidence…":"No still image is attached to this incident."}</div>}</div><div className="incident-meta-grid"><div className="incident-meta-item"><small>Camera</small><b>{selected.camera||"Unassigned"}</b></div><div className="incident-meta-item"><small>Evidence source</small><b>{source(selected)}</b></div><div className="incident-meta-item"><small>Occurred</small><b>{exact(selected.device_ts)}</b></div><div className="incident-meta-item"><small>Site</small><b>{site?.name||selected.site||"Selected site"}</b></div></div><div className="incident-ai-box"><div className="incident-ai-head"><Mark size={22}/><b>WatchLog AI</b></div>{answer?<p>{answer}</p>:<p>Ask WatchLog to explain this incident using the selected site's verified context.</p>}<button onClick={askAboutIncident} disabled={askBusy}>{askBusy?"Reviewing…":"Ask WatchLog about this incident"}</button></div><div className="incident-detail-actions"><a className="secondaryLink" href={withSite("/incidents/evidence/",siteId)}>Advanced evidence & footage</a><a className="secondaryLink" href={withSite("/site-health/",siteId)}>Site Health</a></div></div>:<div className="empty">Select an incident to review it.</div>}</article>
    </section>}
  </main></div>;
}
