"use client";

import { useCallback, useEffect, useState } from "react";
import { supabase, say } from "../../lib/supabase";
import { Nav, requireTenant } from "../shell";
import { rememberSite, selectedSiteId, withSite } from "../site-context";
import ui from "../portal.module.css";

function human(v){return String(v||"Not verified").replaceAll("_"," ").replace(/\b\w/g,(c)=>c.toUpperCase());}
function ago(ts){if(!ts)return"Never";const s=Math.max(0,Math.round((Date.now()-Date.parse(ts))/1000));if(s<60)return`${s}s ago`;if(s<3600)return`${Math.round(s/60)}m ago`;if(s<86400)return`${Math.round(s/3600)}h ago`;return`${Math.round(s/86400)}d ago`;}
function Pill({state,label}){const cls=state==="ok"?"s-ok":state==="bad"?"s-bad":state==="warn"?"s-warn":"s-unk";return <span className={`pill ${cls}`}>{label}</span>;}

export default function CameraWorkspace(){
  const[email,setEmail]=useState(""),[sites,setSites]=useState([]),[siteId,setSiteId]=useState(""),[ctx,setCtx]=useState(null),[shots,setShots]=useState({}),[busyId,setBusyId]=useState(""),[error,setError]=useState(""),[stamp,setStamp]=useState("");
  const load=useCallback(async()=>{const g=await requireTenant();if(!g)return;setEmail(g.session.user.email||"");const s=await supabase().rpc("wl_sites");if(s.error){setError(say(s.error));return;}const list=s.data||[];setSites(list);const preferred=new URLSearchParams(window.location.search).get("site")||selectedSiteId()||list[0]?.id||"";if(preferred){setSiteId(preferred);rememberSite(preferred,list.find((x)=>x.id===preferred)?.name||"");}},[]);
  const refresh=useCallback(async(id)=>{if(!id)return;const{data,error}=await supabase().rpc("wl_ai_context",{p_site_id:id});if(error){setError(say(error));return;}setCtx(data||null);setError("");setStamp(new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}));},[]);
  useEffect(()=>{load();},[load]);useEffect(()=>{if(siteId)refresh(siteId);},[siteId,refresh]);useEffect(()=>{if(!siteId)return;const t=setInterval(()=>refresh(siteId),12000);return()=>clearInterval(t);},[siteId,refresh]);
  const site=sites.find((s)=>s.id===siteId),cameras=(ctx?.cameras||[]).filter((c)=>c.monitor),faults=ctx?.faults||[];
  useEffect(()=>{let live=true;(async()=>{for(const c of cameras.slice(0,16)){if(shots[c.id]!==undefined)continue;const{data}=await supabase().rpc("wl_camera_config_snapshot",{p_camera_id:c.id});if(!live)return;setShots((m)=>({...m,[c.id]:data?.image_b64?{image:`data:${data.content_type||"image/jpeg"};base64,${data.image_b64}`,captured:data.captured_at||null}:false}));}})();return()=>{live=false;};},[cameras,shots]);
  function choose(id){setSiteId(id);setShots({});rememberSite(id,sites.find((s)=>s.id===id)?.name||"");history.replaceState(null,"",`/control-room/?site=${encodeURIComponent(id)}`);}
  async function fresh(c){setBusyId(c.id);setError("");const{error}=await supabase().rpc("wl_request_config_snapshot",{p_camera_id:c.id});if(error){setBusyId("");setError(say(error));return;}setTimeout(async()=>{const{data}=await supabase().rpc("wl_camera_config_snapshot",{p_camera_id:c.id});if(data?.image_b64)setShots((m)=>({...m,[c.id]:{image:`data:${data.content_type||"image/jpeg"};base64,${data.image_b64}`,captured:data.captured_at||null}}));setBusyId("");},2500);}

  return <div className="shell"><Nav active="Control Room" email={email} currentSiteId={siteId} right={<span>{stamp?`Updated ${stamp}`:""}</span>}/><main className="main">
    <header className="target-page-head"><div><div className="target-eyebrow">Camera View</div><h1>{site?.name||"Site"} cameras</h1><p>See current camera health and the latest requested stills first. Layout configuration stays available without taking over the monitoring view.</p></div><div className="target-actions"><select value={siteId} onChange={(e)=>choose(e.target.value)}>{sites.map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button className="ghost small" onClick={()=>refresh(siteId)}>Refresh</button><a className={ui.secondaryLink} href={withSite("/control-room/advanced/",siteId)}>Edit layouts</a></div></header>
    {error&&<div className="err">{error}</div>}
    {!ctx?<div className="panel"><div className="empty">Loading this site's cameras…</div></div>:<>
      <section className={ui.metricGrid}><div className={ui.metric}><div className={ui.metricValue}>{cameras.length}</div><div className={ui.metricLabel}>Monitored cameras</div></div><div className={ui.metric}><div className={ui.metricValue}>{cameras.filter((c)=>c.health_state!=="offline").length}</div><div className={ui.metricLabel}>Reporting</div></div><div className={ui.metric}><div className={ui.metricValue}>{cameras.filter((c)=>String(c.recording_state||"").toLowerCase().includes("record")).length}</div><div className={ui.metricLabel}>Recording verified</div></div><div className={ui.metric}><div className={ui.metricValue}>{faults.length}</div><div className={ui.metricLabel}>Needs attention</div></div></section>
      {faults.length>0&&<div className={ui.callout}><span className={ui.statusDot}/><div><strong>{faults.length} item{faults.length===1?"":"s"} need attention.</strong><p>Open Site Health for the monitoring and recovery context behind these camera issues.</p><a className={ui.primaryLink} href={withSite("/site-health/",siteId)}>Open Site Health</a></div></div>}
      <div className={ui.sectionHead}><div><h2>Cameras</h2><p>Tiles show requested still images, not live cloud video. Capture time tells you how recent each image is.</p></div></div>
      {cameras.length?<section className="camera-view-grid">{cameras.map((c)=>{const shot=shots[c.id];const state=c.health_state==="offline"?"bad":c.health_state?"ok":"unknown";return <article className="camera-view-card" key={c.id}><div className="camera-view-media">{shot?.image?<img src={shot.image} alt={`Latest requested still from ${c.name||`camera ${c.channel}`}`}/>:<div>{shot===undefined?"Loading latest still…":"No requested still available"}</div>}</div><div className="camera-view-body"><div className="camera-view-title"><div><b>{c.name||`Camera ${c.channel}`}</b><small>Channel {c.channel} · {human(c.purpose||"general")}</small></div><Pill state={state} label={human(c.health_state)}/></div><div className="camera-view-meta"><span>{shot?.captured?`Captured ${ago(shot.captured)}`:"No capture time"}</span><span>{human(c.recording_state)}</span></div><button className="ghost small" disabled={busyId===c.id} onClick={()=>fresh(c)}>{busyId===c.id?"Requesting…":"Request fresh still"}</button></div></article>;})}</section>:<div className={ui.emptyCard}>{ctx?.connectivity?.agent_online?"No cameras are configured for monitoring yet. Continue Guided Setup to choose them.":"Connect WatchLog to this site before camera views are available."}</div>}
      <div className={ui.sectionHead}><div><h2>What should I review?</h2><p>Use WatchLog's focused views instead of configuring everything from the camera screen.</p></div></div><section className={ui.threeCol}><a className={ui.roleCard} href={withSite("/incidents/",siteId)}><strong>Incidents</strong><p>Review moments that need security attention and evidence.</p><span>Open incidents →</span></a><a className={ui.roleCard} href={withSite("/analytics/",siteId)}><strong>Analytics</strong><p>Understand activity patterns and configured site intelligence.</p><span>Open analytics →</span></a><a className={ui.roleCard} href={withSite("/control-room/advanced/",siteId)}><strong>Advanced layouts</strong><p>Build saved multi-camera operating layouts when you need them.</p><span>Edit layouts →</span></a></section>
    </>}
  </main></div>;
}
