"""Single source of truth for the WatchLog build version.

Everything derives its version from here: the runtime agent, the analytics
entrypoint, the setup UI/backend, the NSIS installer (read by the build script
and passed as /DAPPVERSION), and the portal heartbeat (via the agent). Do not
hardcode a version string anywhere else — the 0.3.3 release shipped runtime
identifying itself as 0.3.0 precisely because there were three separate
constants. A contract test enforces this.

BUILD_SHA / BUILD_CHANNEL are optionally stamped by the release pipeline.
"""
from __future__ import annotations

import os

VERSION = "5.0.17"

# BUILD_SHA / BUILD_CHANNEL are stamped at BUILD time into build_info.py, which the freezer
# bundles into the exe. Reading it from a bundled module (not just an env var) is what lets a
# SHIPPED Agent report its exact source commit on a customer machine that has no build
# environment. Resolution order: baked build_info -> env var (dev runs) -> empty/default.
try:
    import build_info as _bi  # type: ignore  # generated by build_exe.ps1, gitignored
except Exception:  # noqa: BLE001 — absent in source checkouts / dev
    _bi = None

BUILD_SHA = (getattr(_bi, "BUILD_SHA", "") or os.environ.get("WATCHLOG_BUILD_SHA", "")).strip()
BUILD_CHANNEL = (getattr(_bi, "BUILD_CHANNEL", "") or os.environ.get("WATCHLOG_BUILD_CHANNEL", "")
                 or "production").strip()


def version_string() -> str:
    """Human/diagnostic version, e.g. '0.4.4' or '0.4.4+abc1234'."""
    return f"{VERSION}+{BUILD_SHA[:7]}" if BUILD_SHA else VERSION


def build_metadata() -> dict:
    """Exact build identity for --version, heartbeat and the support bundle."""
    return {"version": VERSION, "build_sha": BUILD_SHA, "channel": BUILD_CHANNEL,
            "version_string": version_string()}
