"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase, say } from "../../lib/supabase";
import { Nav, requireTenant, setupPill } from "../shell";
import styles from "./site-health.module.css";

const REFRESH_MS=15000;
function liveness(lastSeen){if(!lastSeen)return["s-unk","not connected"];const age=(Date.now()-Date.parse(lastSeen))/1000;if(age<180)return["s-ok","online"];if(age<1800)return["s-warn","needs attention"];return["s-bad","offline"];}
function ago(ts){if(!ts)return"Never";const s=Math.max(0,Math.round((Date.now()-Date.parse(ts))/1000));if(s<60)return`${s}s ago`;if(s<3600)return`${Math.round(s/60)}m ago`;if(s<86400)return`${Math.round(s/3600)}h ago`;return`${Math.round(s/86400)}d ago`;}
function human(v){if(!v)return"Issue";return String(v).replaceAll("_"," ").replace(/^./,(c)=>c.toUpperCase());}
// Phase-A operational-health vocabulary -> status pills (status is never colour alone; each carries its word).
const SS_MAP={ok:["s-ok","healthy"],degraded:["s-warn","low space"],fault:["s-bad","fault"],unknown:["s-unk","unknown"]};
const SEV_CLS={critical:"s-bad",warning:"s-warn",info:"s-unk"};
function statePill(map,key){const[cls,label]=map[key]||map.unknown;return <span className={"pill "+cls}>{label}</span>;}
function reachPill(v,okWord,badWord){if(v===true)return <span className="pill s-ok">{okWord}</span>;if(v===false)return <span className="pill s-bad">{badWord}</span>;return <span className="pill s-unk">unknown</span>;}
function issueLine(item,fallback){const primary=item?.camera||item?.hostname||item?.device||item?.site||fallback;const secondary=[item?.site&&item.site!==primary?item.site:null,item?.event_type||item?.type?human(item.event_type||item.type):null,item?.device_ts||item?.last_seen_at||item?.last_activity_at?ago(item.device_ts||item.last_seen_at||item.last_activity_at):null].filter(Boolean).join(" · ");return[primary,secondary];}
function IssueCard({title,copy,items,fallback}){return <section className={styles.issueCard}><h3>{title}</h3><p>{copy}</p>{items.length?<div className={styles.issueList}>{items.slice(0,8).map((item,i)=>{const[primary,secondary]=issueLine(item,fallback);return <div className={styles.issue} key={item.event_id||item.id||`${primary}-${i}`}><i/><div><strong>{primary}</strong>{secondary&&<small>{secondary}</small>}</div></div>;})}</div>:<div className={styles.clear}>No issue in this category.</div>}</section>;}

export default function SiteHealth(){
  const[email,setEmail]=useState(""),[overview,setOverview]=useState(null),[sites,setSites]=useState([]),[details,setDetails]=useState({cameras:[],faults:[]}),[error,setError]=useState(""),[stamp,setStamp]=useState(""),[snaps,setSnaps]=useState({});
  const load=useCallback(async()=>{const guard=await requireTenant();if(!guard)return;setEmail(guard.session.user.email||"");const sb=supabase();const[o,s,h]=await Promise.all([sb.rpc("wl_portal_overview",{p_days:7}),sb.rpc("wl_sites"),sb.rpc("wl_site_health_details",{p_days:1})]);if(o.error||s.error||h.error){setError(say(o.error||s.error||h.error));return;}setError("");setOverview(o.data||{});setSites(s.data||[]);setDetails(h.data||{cameras:[],faults:[]});try{const snapRes=await Promise.all((s.data||[]).map((site)=>sb.rpc("wl_site_health_snapshot",{p_site_id:site.id})));const m={};(s.data||[]).forEach((site,i)=>{if(snapRes[i]&&!snapRes[i].error)m[site.id]=snapRes[i].data;});setSnaps(m);}catch(_e){/* additive: the legacy view still renders if the snapshot RPC is unavailable */}setStamp(new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}));},[]);
  useEffect(()=>{load();const timer=setInterval(load,REFRESH_MS);return()=>clearInterval(timer);},[load]);
  const agents=overview?.agents||[],health=overview?.health||{},offlineAgents=health.offline_agents||[],cameras=details?.cameras||[],faults=details?.faults||[],quietCameras=cameras.filter((c)=>c.activity_state==="silent"||c.activity_state==="never"),onlineAgents=agents.filter((a)=>liveness(a.last_seen_at)[0]==="s-ok").length,totalCameras=Number(overview?.totals?.cameras||cameras.length||sites.reduce((n,s)=>n+Number(s.cameras||0),0));
  const bySite=useMemo(()=>{const grouped={};for(const a of agents)(grouped[a.site]=grouped[a.site]||[]).push(a);return grouped;},[agents]);
  const camerasBySite=useMemo(()=>{const grouped={};for(const c of cameras)(grouped[c.site]=grouped[c.site]||[]).push(c);return grouped;},[cameras]);
  const healthySites=sites.filter((s)=>{const siteAgents=bySite[s.name]||[],hasOnline=siteAgents.some((a)=>liveness(a.last_seen_at)[0]==="s-ok")||s.online,issue=offlineAgents.some((a)=>a.site===s.name)||quietCameras.some((c)=>c.site===s.name)||faults.some((f)=>f.site===s.name);return hasOnline&&!issue;}).length;
  const reportingCameras=Math.max(0,totalCameras-quietCameras.length);

  return <div className="shell"><Nav active="Site Health" email={email} right={<span className="muted hide-sm" style={{fontSize:"var(--font-size-xs)"}}>{stamp?`updated ${stamp}`:""}</span>}/><main className="main">
    <header className="target-page-head"><div><div className="target-eyebrow">Site Health</div><h1>Know when something goes quiet.</h1><p>WatchLog checks the connection and activity at each location so your team can see where attention is needed without diagnosing the underlying technology.</p></div></header>
    {error&&<div className="err">{error}</div>}
    {!overview?<div className="panel"><div className="empty">Loading site health...</div></div>:<>
      <section className={styles.metrics} aria-label="Site health summary"><div className={styles.metric}><div className={styles.metricLabel}>Healthy sites</div><div className={styles.metricValue} style={{color:"var(--color-status-ok-dark)"}}>{healthySites} / {sites.length}</div><div className={styles.metricHint}>No current connection or camera issue</div></div><div className={styles.metric}><div className={styles.metricLabel}>Cameras reporting</div><div className={styles.metricValue} style={{color:quietCameras.length?"var(--color-status-warn-dark)":"var(--color-status-ok-dark)"}}>{reportingCameras} / {totalCameras}</div><div className={styles.metricHint}>{quietCameras.length} quiet or not yet seen</div></div><div className={styles.metric}><div className={styles.metricLabel}>Site connections online</div><div className={styles.metricValue} style={{color:onlineAgents===agents.length?"var(--color-status-ok-dark)":"var(--color-status-warn-dark)"}}>{onlineAgents} / {agents.length}</div><div className={styles.metricHint}>Recent contact with WatchLog</div></div><div className={styles.metric}><div className={styles.metricLabel}>Current equipment issues</div><div className={styles.metricValue} style={{color:faults.length?"var(--color-status-warn-dark)":"var(--color-status-ok-dark)"}}>{faults.length}</div><div className={styles.metricHint}>Camera-system issues, 24h</div></div></section>

      <div className={styles.sectionHead}><div><h2>Sites</h2><p>Connection and camera activity by location.</p></div></div>
      <section className="health-site-grid">{sites.map((s)=>{const siteAgents=bySite[s.name]||[],online=siteAgents.filter((a)=>liveness(a.last_seen_at)[0]==="s-ok").length,siteCameras=camerasBySite[s.name]||[],knownCameras=siteCameras.length||Number(s.cameras||0),siteQuiet=siteCameras.filter((c)=>c.activity_state==="silent"||c.activity_state==="never").length,siteFaults=faults.filter((f)=>f.site===s.name).length,siteOfflineAgents=offlineAgents.filter((a)=>a.site===s.name).length,siteIssues=siteOfflineAgents+siteQuiet+siteFaults,siteOnline=s.online||online>0,score=knownCameras?Math.max(0,Math.round(((knownCameras-siteQuiet)/knownCameras)*100)):(siteOnline?100:0),ringClass=!siteOnline?"bad":siteIssues?"warn":"",[setupLabel,setupClass]=setupPill(s.setup_state,siteOnline);return <article className="health-site-card" key={s.id}><div className={`health-ring ${ringClass}`} style={{"--score":score}}><span><strong>{score}%</strong><small>Reporting</small></span></div><div><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"flex-start"}}><div><h3>{s.name}</h3><div className="health-site-summary">{knownCameras} camera{knownCameras===1?"":"s"} · last activity {ago(s.last_event)}</div></div><span className={"pill "+(siteIssues?"s-warn":siteOnline?"s-ok":"s-bad")}>{siteIssues?`${siteIssues} issue${siteIssues===1?"":"s"}`:siteOnline?"healthy":"offline"}</span></div><div className="health-camera-list">{siteCameras.length?siteCameras.slice(0,5).map((c)=><div className={`health-camera-row${c.activity_state==="active"?"":" warn"}`} key={c.id}><i/><span>{c.camera}</span><span>{c.activity_state==="active"?"recent":c.activity_state==="silent"?"quiet 24h+":"not seen"}</span></div>):<><div className="health-camera-row"><i/><span>WatchLog connection</span><span>{online}/{siteAgents.length} online</span></div><div className="health-camera-row"><i/><span>Setup</span><span><span className={"pill "+setupClass}>{setupLabel}</span></span></div></>}{siteCameras.length>5&&<div className="muted" style={{fontSize:11}}>+ {siteCameras.length-5} more cameras</div>}</div></div></article>;})}{!sites.length&&<div className="panel"><div className="empty">No sites yet. Add a site in Settings to begin health monitoring.</div></div>}</section>

      <div className={styles.sectionHead}><div><h2>Needs attention</h2><p>The specific gaps WatchLog has observed. A quiet list is good news.</p></div></div><div className={styles.issueGrid}><IssueCard title="Site connections" copy="Locations that have stopped checking in to WatchLog." items={offlineAgents} fallback="Site connection offline"/><IssueCard title="Quiet cameras" copy="Cameras with no recorded activity in the last 24 hours. Review in context before treating silence as a fault." items={quietCameras} fallback="Camera quiet"/><IssueCard title="Camera-system issues" copy="Equipment issues reported from the CCTV system in the last 24 hours." items={faults} fallback="Camera-system issue"/></div>

      <div className={styles.sectionHead}><div><h2>Operational health</h2><p>Live per-layer status the WatchLog agent confirmed — recorder connection, credentials, storage and open faults. UNKNOWN means not currently observed, never assumed down.</p></div></div>
      <section className="health-site-grid">{sites.some((s)=>snaps[s.id])?sites.map((s)=>{const snap=snaps[s.id];if(!snap)return null;const rec=(snap.recorders||[])[0]||{},sum=snap.summary||{},fs=snap.faults||[],worst=fs.some((f)=>f.severity==="critical")?"s-bad":fs.length?"s-warn":"s-ok";return <article className="health-site-card" key={"op-"+s.id}><div><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"flex-start"}}><div><h3>{s.name}</h3><div className="health-site-summary">{sum.operational||0}/{sum.cameras_total||0} operational{sum.offline?` · ${sum.offline} offline`:""}{sum.unknown?` · ${sum.unknown} unknown`:""}</div></div><span className={"pill "+worst}>{fs.length?`${fs.length} open fault${fs.length===1?"":"s"}`:"all clear"}</span></div><div className="health-camera-list"><div className="health-camera-row"><i/><span>Recorder reachable</span><span>{reachPill(rec.nvr_reachable,"reachable","unreachable")}</span></div><div className="health-camera-row"><i/><span>Credentials</span><span>{reachPill(rec.nvr_auth_ok,"authenticated","auth failed")}</span></div><div className="health-camera-row"><i/><span>Storage</span><span>{statePill(SS_MAP,rec.storage_state||"unknown")}</span></div></div>{fs.length?<div className="health-camera-list">{fs.slice(0,6).map((f)=><div className="health-camera-row warn" key={f.id}><i/><span>{human(f.fault_type)}{f.domain==="camera"||f.domain==="recording"?"":" (recorder)"}</span><span><span className={"pill "+(SEV_CLS[f.severity]||"s-unk")}>{f.severity}</span></span></div>)}</div>:null}</div></article>;}):<div className="panel"><div className="empty">No agent has reported layered health yet. This view populates once a WatchLog agent runs its health cycle.</div></div>}</section>

      <div className={styles.sectionHead}><div><h2>Camera activity</h2><p>Last activity WatchLog received from every connected camera, by site.</p></div></div><div className="panel"><div className={styles.tableWrap}>{cameras.length?<table><thead><tr><th>Site</th><th>Camera</th><th>Channel</th><th>Activity state</th><th>Last reported activity</th></tr></thead><tbody>{cameras.map((c)=><tr key={c.id}><td>{c.site}</td><td className={styles.agentName}>{c.camera}</td><td className="mono">{c.channel}</td><td><span className={"pill "+(c.activity_state==="active"?"s-ok":c.activity_state==="silent"?"s-warn":"s-unk")}>{c.activity_state==="active"?"recent activity":c.activity_state==="silent"?"quiet 24h+":"no activity yet"}</span></td><td title={c.last_activity_at?new Date(c.last_activity_at).toLocaleString():""}>{ago(c.last_activity_at)}</td></tr>)}</tbody></table>:<div className="empty">No cameras are connected yet.</div>}</div></div>

      <div className={styles.sectionHead}><div><h2>Site connections</h2><p>Last contact between each location and WatchLog.</p></div></div><div className="panel"><div className={styles.tableWrap}>{agents.length?<table><thead><tr><th>Site</th><th>Site computer</th><th>Status</th><th>Last contact</th><th className="hide-sm">Camera system</th></tr></thead><tbody>{agents.map((a)=>{const[cls,label]=liveness(a.last_seen_at),recorder=[a.device_vendor,a.device_model].filter(Boolean).join(" ");return <tr key={a.agent_id}><td>{a.site}</td><td className={styles.agentName}>{a.hostname||"Site computer"}</td><td><span className={"pill "+cls}>{label}</span></td><td>{ago(a.last_seen_at)}</td><td className="muted hide-sm">{recorder||"Not identified"}</td></tr>;})}</tbody></table>:<div className="empty">No site has connected to WatchLog yet.</div>}</div></div>
    </>}
  </main></div>;
}
