import "./globals.css";
import "./visual-target.css";
import "./module-target.css";

export const metadata = {
  title: "WatchLog",
  description:
    "Your cameras already see everything. WatchLog tells you what they saw.",
  // Assets are generated by tools/build_brand_assets.py and copied into
  // public/. Do not hand-edit them there - they will be overwritten.
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "16x16 32x32 48x48" },
      { url: "/icon.svg", type: "image/svg+xml" },
      { url: "/icon-192.png", type: "image/png", sizes: "192x192" },
      { url: "/icon-512.png", type: "image/png", sizes: "512x512" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180" }],
  },
};

export const viewport = {
  // Matches the dark product canvas, so the mobile browser chrome does not
  // flash white against it on load.
  themeColor: "#0B1220",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Geist is the geometric grotesque the chosen direction calls
            for; Inter is the fallback already present everywhere. */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Geist:wght@400;500;600;700;800&family=Inter:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
