"use client";

import { useEffect, useState } from "react";
import { supabase, say } from "../../lib/supabase";
import Mark from "../mark";
import { SETUP_STEPS } from "../shell";

export default function Onboarding(){
  const[stage,setStage]=useState("loading"),[company,setCompany]=useState(""),[site,setSite]=useState("Main site"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[code,setCode]=useState(""),[setupState,setSetupState]=useState("awaiting_agent");
  useEffect(()=>{if(stage!=="connect")return;let live=true;const tick=async()=>{const{data}=await supabase().rpc("wl_sites");if(live&&data?.[0])setSetupState(data[0].setup_state);};tick();const t=setInterval(tick,8000);return()=>{live=false;clearInterval(t);};},[stage]);
  useEffect(()=>{(async()=>{const sb=supabase();const{data:{session}}=await sb.auth.getSession();if(!session){location.replace("/login/");return;}const{data:tenant}=await sb.rpc("wl_my_tenant");if(tenant){location.replace("/dashboard/");return;}setCompany(session.user?.user_metadata?.company||"");setStage("form");})();},[]);
  async function createTenant(e){e.preventDefault();setBusy(true);setError("");const{data,error}=await supabase().rpc("wl_bootstrap_tenant",{p_company:company,p_site_name:site,p_timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||"Asia/Karachi"});if(error){setError(say(error));setBusy(false);return;}setCode(data.enrollment_code||"");setStage("connect");setBusy(false);}
  if(stage==="loading")return <div className="center"><p className="muted">Loading...</p></div>;
  if(stage==="form")return <div className="center"><form className="auth-card" onSubmit={createTenant}><div className="brand"><Mark/><span className="brand-name">WatchLog</span></div><h1>Set up your first site</h1><p className="sub">A site is one location with one recorder and one Site Agent installation.</p>{error&&<div className="err">{error}</div>}<label htmlFor="company">Company</label><input id="company" required value={company} onChange={(e)=>setCompany(e.target.value)}/><label htmlFor="site">Site name</label><input id="site" required value={site} onChange={(e)=>setSite(e.target.value)} placeholder="Head Office, Warehouse, Plant"/><button type="submit" disabled={busy}>{busy?"Creating...":"Continue"}</button></form></div>;

  return <div className="center"><div className="auth-card" style={{maxWidth:620}}><div className="brand"><Mark/><span className="brand-name">WatchLog</span></div><h1>Connect your recorder</h1><p className="sub">About ten minutes on the Windows PC that will stay at this site.</p>
    <div className="banner" style={{marginBottom:24}}><b style={{fontSize:"var(--font-size-sm)"}}>Before you run the installer, have these four things</b><ul><li>A supported NVR or DVR already connected to the cameras</li><li>A Windows PC on the <b>same network</b> as that recorder, kept switched on</li><li>The recorder&apos;s own username and password</li><li>An ordinary internet connection for outbound WatchLog traffic</li></ul><p className="muted" style={{fontSize:"var(--font-size-sm)",margin:"10px 0 0"}}>Recorder credentials stay on that site PC. WatchLog does not expose the recorder or require port forwarding.</p></div>
    <div className="card" style={{marginBottom:20}}><div style={{fontSize:"var(--font-size-xs)",textTransform:"uppercase",letterSpacing:".06em",color:"var(--color-muted-dark)",fontWeight:700,marginBottom:10}}>Live setup progress</div>{SETUP_STEPS.map(([key,label],i)=>{const cur=SETUP_STEPS.findIndex(([k])=>k===setupState),done=i<=cur,active=i===cur;return <div key={key} style={{display:"flex",alignItems:"center",gap:10,padding:"4px 0",opacity:done?1:.45}}><span style={{width:16,height:16,borderRadius:999,flex:"none",background:done?"var(--wl-blue)":"transparent",border:"1px solid var(--wl-blue)"}}/><span style={{fontSize:"var(--font-size-sm)",fontWeight:active?700:400}}>{label}</span></div>;})}<p className="muted" style={{fontSize:"var(--font-size-xs)",margin:"10px 0 0"}}>This updates automatically as the Site Agent enrolls, proves the recorder connection and discovers cameras.</p></div>
    <ol className="steps"><li><b>Download the WatchLog Windows installer</b><p>It installs the Site Agent, registers it to start automatically at boot and then opens the guided recorder setup.</p><p style={{marginTop:8}}>{process.env.NEXT_PUBLIC_INSTALLER_URL?<a href={process.env.NEXT_PUBLIC_INSTALLER_URL}><button className="small" type="button" style={{width:"auto"}}>Download WatchLog for Windows</button></a>:<span className="muted" style={{fontSize:"var(--font-size-sm)"}}>The signed download appears here once published. The release file is <span className="mono">WatchLog-Setup.exe</span>.</span>}</p></li><li><b>Run setup and enter your enrollment code</b><p>The wizard searches the local network, asks for the recorder&apos;s own login and proves it works before saving anything.</p><div className="code-box">{code||"-"}</div><p>Single use, valid 14 days.</p></li><li><b>Let the cameras sync</b><p>The Site Agent runs in the background, the portal advances to ready, and discovered cameras become available for incidents, health and Analytics Studio.</p></li></ol>
    <p style={{marginTop:24}}><a href="/dashboard/"><button type="button">Go to Overview</button></a></p>
  </div></div>;
}
