"use client";

import { useEffect, useState } from "react";
import { supabase, say } from "../../lib/supabase";
import Mark from "../mark";
import { SETUP_STEPS } from "../shell";

async function accountState(sb){const{data,error}=await sb.rpc("wl_my_account");if(!error)return data;if(/wl_my_account|schema cache|function/i.test(error.message||""))return undefined;throw error;}

export default function Onboarding(){
  const[stage,setStage]=useState("loading"),[company,setCompany]=useState(""),[site,setSite]=useState("Main site"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[code,setCode]=useState(""),[setupState,setSetupState]=useState("awaiting_agent");
  useEffect(()=>{if(stage!=="connect")return;let live=true;const tick=async()=>{const{data}=await supabase().rpc("wl_sites");if(live&&data?.[0])setSetupState(data[0].setup_state);};tick();const t=setInterval(tick,8000);return()=>{live=false;clearInterval(t);};},[stage]);
  useEffect(()=>{(async()=>{const sb=supabase();const{data:{session}}=await sb.auth.getSession();if(!session){location.replace("/login/");return;}try{const account=await accountState(sb);if(account?.account_status==="suspended"){location.replace("/account-suspended/");return;}if(account?.tenant_id){location.replace("/dashboard/");return;}}catch{setError("WatchLog could not verify your account. Please try again.");setStage("error");return;}const{data:tenant}=await sb.rpc("wl_my_tenant");if(tenant){location.replace("/dashboard/");return;}setCompany(session.user?.user_metadata?.company||"");setStage("form");})();},[]);
  async function createTenant(e){e.preventDefault();setBusy(true);setError("");const{data,error}=await supabase().rpc("wl_bootstrap_tenant",{p_company:company,p_site_name:site,p_timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||"Asia/Karachi"});if(error){setError(say(error));setBusy(false);return;}setCode(data.enrollment_code||"");setStage("connect");setBusy(false);}
  if(stage==="loading")return <div className="center"><p className="muted">Loading...</p></div>;
  if(stage==="error")return <div className="center"><div className="auth-card"><div className="brand"><Mark tone="white"/><span className="brand-name">WatchLog</span></div><h1>We could not open your account</h1><p className="sub">{error}</p><a href="/">Try again</a></div></div>;
  if(stage==="form")return <div className="center"><form className="auth-card" onSubmit={createTenant}><div className="brand"><Mark tone="white"/><span className="brand-name">WatchLog</span></div><div className="target-eyebrow">Welcome to WatchLog</div><h1>Set up your first site</h1><p className="sub">Tell us where your first cameras are located. You can add more sites whenever you need them.</p>{error&&<div className="err">{error}</div>}<label htmlFor="company">Company</label><input id="company" required value={company} onChange={(e)=>setCompany(e.target.value)}/><label htmlFor="site">Site name</label><input id="site" required value={site} onChange={(e)=>setSite(e.target.value)} placeholder="Head Office, Warehouse, Plant"/><button type="submit" disabled={busy}>{busy?"Creating...":"Continue"}</button></form></div>;

  const current=SETUP_STEPS.findIndex(([k])=>k===setupState);
  return <div className="center"><div className="auth-card setup-target"><div className="brand"><Mark tone="white"/><span className="brand-name">WatchLog</span></div><div style={{textAlign:"center",marginBottom:22}}><h1 style={{fontSize:"clamp(2rem,4vw,2.7rem)"}}>Connect your cameras</h1><p className="sub" style={{marginBottom:0}}>Follow the guided Windows setup at your site. Most installations take about ten minutes.</p></div>
    {error&&<div className="err">{error}</div>}
    <section className="card" style={{marginBottom:14}}><h2 style={{margin:"0 0 10px",fontSize:16,textTransform:"none",letterSpacing:"-.02em",color:"#fff"}}>Before you start</h2><ul style={{margin:0,paddingLeft:18,color:"#cbd3de",fontSize:13,lineHeight:1.8}}><li>A Windows computer at the site, connected to the same network as your CCTV system</li><li>Your CCTV username and password for the guided connection step</li><li>A normal internet connection so WatchLog can update your portal and reports</li></ul></section>

    <section className="card" style={{marginBottom:14}}><h2 style={{margin:"0 0 4px",fontSize:16,textTransform:"none",letterSpacing:"-.02em",color:"#fff"}}>Setup progress</h2><p className="muted" style={{fontSize:12,margin:"0 0 8px"}}>This page updates automatically while WatchLog connects the site and prepares the cameras.</p><div className="setup-progress">{SETUP_STEPS.slice(1).map(([key,label],i)=>{const absoluteIndex=i+1,ready=setupState==="ready",done=ready?absoluteIndex<=current:absoluteIndex<current,active=!done&&absoluteIndex===current,pending=absoluteIndex>current;return <div className={`setup-progress-row${done?" done":active?" active":pending?" pending":""}`} key={key}><span className="setup-progress-dot">{done?"✓":""}</span><b style={{fontSize:13}}>{label}</b><span className="setup-progress-state">{done?"Done":active?"In progress":"Pending"}</span></div>;})}</div></section>

    <section className="card" style={{marginBottom:0}}><div className="setup-progress-row done"><span className="setup-progress-dot">1</span><div><b>Download WatchLog for Windows</b><div className="muted" style={{fontSize:12,marginTop:3}}>The guided setup will help connect this location.</div></div><span>{process.env.NEXT_PUBLIC_INSTALLER_URL?<a href={process.env.NEXT_PUBLIC_INSTALLER_URL}><button className="small" type="button">Download for Windows</button></a>:<span className="muted" style={{fontSize:11}}>Contact WatchLog Support for the Windows setup</span>}</span></div><div className="setup-progress-row active"><span className="setup-progress-dot">2</span><div><b>Run WatchLog and enter this setup code</b><div className="muted" style={{fontSize:12,marginTop:3}}>The code can be used once and is valid for 14 days.</div></div><div className="code-box" style={{margin:0,minWidth:190,padding:"10px 14px",fontSize:20}}>{code||"-"}</div></div><div className="setup-progress-row pending"><span className="setup-progress-dot">3</span><div><b>Watch your site come online</b><div className="muted" style={{fontSize:12,marginTop:3}}>Once cameras are ready, Overview, Site Health and Analytics will begin filling in.</div></div><span/></div></section>
    <p style={{margin:"20px 0 0",textAlign:"center"}}><a href="/dashboard/">Go to Overview</a></p>
  </div></div>;
}
