"use client";

import { useEffect, useState } from "react";
import { supabase, say } from "../../lib/supabase";
import Mark from "../mark";
import { SETUP_STEPS } from "../shell";

export default function Onboarding(){
  const[stage,setStage]=useState("loading"),[company,setCompany]=useState(""),[site,setSite]=useState("Main site"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[code,setCode]=useState(""),[setupState,setSetupState]=useState("awaiting_agent");
  useEffect(()=>{if(stage!=="connect")return;let live=true;const tick=async()=>{const{data}=await supabase().rpc("wl_sites");if(live&&data?.[0])setSetupState(data[0].setup_state);};tick();const t=setInterval(tick,8000);return()=>{live=false;clearInterval(t);};},[stage]);
  useEffect(()=>{(async()=>{const sb=supabase();const{data:{session}}=await sb.auth.getSession();if(!session){location.replace("/login/");return;}const{data:tenant}=await sb.rpc("wl_my_tenant");if(tenant){location.replace("/dashboard/");return;}setCompany(session.user?.user_metadata?.company||"");setStage("form");})();},[]);
  async function createTenant(e){e.preventDefault();setBusy(true);setError("");const{data,error}=await supabase().rpc("wl_bootstrap_tenant",{p_company:company,p_site_name:site,p_timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||"Asia/Karachi"});if(error){setError(say(error));setBusy(false);return;}setCode(data.enrollment_code||"");setStage("connect");setBusy(false);}
  if(stage==="loading")return <div className="center"><p className="muted">Loading...</p></div>;
  if(stage==="form")return <div className="center"><form className="auth-card" onSubmit={createTenant}><div className="brand"><Mark tone="white"/><span className="brand-name">WatchLog</span></div><div className="target-eyebrow">First site</div><h1>Set up your first site</h1><p className="sub">One location, one recorder and one Windows Site Agent. You can add more sites later.</p>{error&&<div className="err">{error}</div>}<label htmlFor="company">Company</label><input id="company" required value={company} onChange={(e)=>setCompany(e.target.value)}/><label htmlFor="site">Site name</label><input id="site" required value={site} onChange={(e)=>setSite(e.target.value)} placeholder="Head Office, Warehouse, Plant"/><button type="submit" disabled={busy}>{busy?"Creating...":"Continue"}</button></form></div>;

  const current=SETUP_STEPS.findIndex(([k])=>k===setupState);
  return <div className="center"><div className="auth-card setup-target"><div className="brand"><Mark tone="white"/><span className="brand-name">WatchLog</span></div><div style={{textAlign:"center",marginBottom:22}}><h1 style={{fontSize:"clamp(2rem,4vw,2.7rem)"}}>Connect your recorder</h1><p className="sub" style={{marginBottom:0}}>About ten minutes, on a Windows PC at the site.</p></div>
    {error&&<div className="err">{error}</div>}
    <section className="card" style={{marginBottom:14}}><h2 style={{margin:"0 0 10px",fontSize:16,textTransform:"none",letterSpacing:"-.02em",color:"#fff"}}>Before you start</h2><ul style={{margin:0,paddingLeft:18,color:"#cbd3de",fontSize:13,lineHeight:1.8}}><li>A Windows PC on the same network as the recorder, kept switched on</li><li>The recorder&apos;s own username and password, which stay on that PC</li><li>An ordinary outbound internet connection; no port forwarding or inbound access</li></ul></section>

    <section className="card" style={{marginBottom:14}}><h2 style={{margin:"0 0 4px",fontSize:16,textTransform:"none",letterSpacing:"-.02em",color:"#fff"}}>Live setup progress</h2><p className="muted" style={{fontSize:12,margin:"0 0 8px"}}>Updates automatically as the Site Agent connects and discovers the recorder.</p><div className="setup-progress">{SETUP_STEPS.slice(1).map(([key,label],i)=>{const absoluteIndex=i+1,ready=setupState==="ready",done=ready?absoluteIndex<=current:absoluteIndex<current,active=!done&&absoluteIndex===current,pending=absoluteIndex>current;return <div className={`setup-progress-row${done?" done":active?" active":pending?" pending":""}`} key={key}><span className="setup-progress-dot">{done?"✓":""}</span><b style={{fontSize:13}}>{label}</b><span className="setup-progress-state">{done?"Done":active?"In progress":"Pending"}</span></div>;})}</div></section>

    <section className="card" style={{marginBottom:0}}><div className="setup-progress-row done"><span className="setup-progress-dot">1</span><div><b>Download the agent</b><div className="muted" style={{fontSize:12,marginTop:3}}>Installs the Site Agent and opens guided recorder setup.</div></div><span>{process.env.NEXT_PUBLIC_INSTALLER_URL?<a href={process.env.NEXT_PUBLIC_INSTALLER_URL}><button className="small" type="button">Download for Windows</button></a>:<span className="muted" style={{fontSize:11}}>Installer publishing pending</span>}</span></div><div className="setup-progress-row active"><span className="setup-progress-dot">2</span><div><b>Run it and enter this code</b><div className="muted" style={{fontSize:12,marginTop:3}}>The code is single use and valid for 14 days.</div></div><div className="code-box" style={{margin:0,minWidth:190,padding:"10px 14px",fontSize:20}}>{code||"-"}</div></div><div className="setup-progress-row pending"><span className="setup-progress-dot">3</span><div><b>Watch it appear</b><div className="muted" style={{fontSize:12,marginTop:3}}>When cameras are discovered, Overview, Site Health and Analytics become available.</div></div><span/></div></section>
    <p style={{margin:"20px 0 0",textAlign:"center"}}><a href="/dashboard/">Go to Overview</a></p>
  </div></div>;
}
