"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase, say } from "../../lib/supabase";
import { Nav } from "../shell";
import { rememberSite, selectedSiteId, withSite } from "../site-context";
import Mark from "../mark";
import styles from "./setup.module.css";

const INSTALLER_URL=process.env.NEXT_PUBLIC_INSTALLER_URL||"";
const SITE_TYPES=[["office","Office","Workplace, head office, professional site"],["warehouse","Warehouse","Storage, dispatch and loading operations"],["factory","Factory","Production floor and restricted operations"],["retail","Retail","Store, showroom or customer-facing branch"],["restaurant","Restaurant","Dining, service and collection areas"],["clinic","Clinic","Healthcare or patient-facing site"],["other","Other","A site that does not fit these categories"]];
const PURPOSES=[["general","General monitoring"],["entrance","Entrance / exit"],["reception","Reception / lobby"],["management","Management / office"],["restricted","Restricted / sensitive area"],["parking","Parking / vehicle access"],["perimeter","Perimeter"],["loading","Loading / service entrance"],["queue","Queue / service area"]];
const DAYS=[[1,"Mon"],[2,"Tue"],[3,"Wed"],[4,"Thu"],[5,"Fri"],[6,"Sat"],[7,"Sun"]];

function stateLabel(s){return String(s||"unknown").replaceAll("_"," ").replace(/\b\w/g,(c)=>c.toUpperCase());}
function recorderName(ctx){return[ctx?.recorder?.vendor,ctx?.recorder?.model].filter(Boolean).join(" ")||"Not identified yet";}
function humanValue(v){if(v===null||v===undefined||v==="")return"Not available";if(typeof v==="boolean")return v?"Yes":"No";if(Array.isArray(v))return v.join(", ")||"None";if(typeof v==="object")return Object.entries(v).slice(0,4).map(([k,x])=>`${stateLabel(k)}: ${typeof x==="object"?"Available":String(x)}`).join(" · ");return stateLabel(v);}

export default function Setup(){
  const[email,setEmail]=useState("");const[role,setRole]=useState("viewer");const[sites,setSites]=useState([]);const[siteId,setSiteId]=useState("");const[context,setContext]=useState(null);const[siteType,setSiteType]=useState("");const[openTime,setOpenTime]=useState("08:00");const[closeTime,setCloseTime]=useState("19:00");const[workingDays,setWorkingDays]=useState([1,2,3,4,5]);const[cameras,setCameras]=useState([]);const[newSite,setNewSite]=useState("");const[recommendation,setRecommendation]=useState(null);const[conversationId,setConversationId]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[note,setNote]=useState("");
  const canManage=role==="owner"||role==="admin";

  const load=useCallback(async()=>{const sb=supabase();const{data:{session}}=await sb.auth.getSession();if(!session){location.replace("/login/");return;}setEmail(session.user.email||"");const[s,r]=await Promise.all([sb.rpc("wl_sites"),sb.rpc("wl_my_role")]);if(s.error||r.error){setError(say(s.error||r.error));return;}const next=s.data||[];setSites(next);setRole(r.data||"viewer");if(!siteId&&next.length){const preferred=new URLSearchParams(window.location.search).get("site")||selectedSiteId()||next[0].id;setSiteId(preferred);rememberSite(preferred,next.find((x)=>x.id===preferred)?.name||"");}},[siteId]);
  const loadContext=useCallback(async(id)=>{if(!id){setContext(null);setCameras([]);return;}const{data,error}=await supabase().rpc("wl_ai_context",{p_site_id:id});if(error){setError(say(error));return;}setContext(data||null);setCameras((data?.cameras||[]).map((c)=>({...c,purpose:c.purpose||"general"})));const bc=data?.business_context||{};if(bc.site_type)setSiteType(bc.site_type);if(bc.open_time)setOpenTime(String(bc.open_time).slice(0,5));if(bc.close_time)setCloseTime(String(bc.close_time).slice(0,5));if(Array.isArray(bc.working_days)&&bc.working_days.length)setWorkingDays(bc.working_days.map(Number));},[]);
  useEffect(()=>{load();},[load]);useEffect(()=>{if(siteId)loadContext(siteId);},[siteId,loadContext]);useEffect(()=>{if(!siteId)return;const t=setInterval(()=>loadContext(siteId),10000);return()=>clearInterval(t);},[siteId,loadContext]);

  const site=sites.find((s)=>s.id===siteId);const steps=context?.onboarding?.steps||[];const monitored=cameras.filter((c)=>c.monitor).length;const configured=cameras.filter((c)=>c.name&&c.name.trim()&&c.purpose&&c.purpose!=="general").length;
  const stage=useMemo(()=>{if(!siteId)return 0;if(!context?.business_context?.captured)return 1;if(!context?.connectivity?.agent_online||!context?.recorder?.identified)return 2;if(!steps.find((s)=>s.key==="map_cameras")?.done)return 3;if(!steps.find((s)=>s.key==="recommendation")?.done)return 4;return 5;},[siteId,context,steps]);
  const progress=stage===0?0:Math.min(100,Math.round(((stage-1)/5)*100));
  const stageCopy={1:["Tell me about this site","I need your operating context before I can make good security recommendations."],2:["Connect this site's cameras","Install WatchLog locally, then I'll identify the recorder and cameras without exposing the recorder to the internet."],3:["Which cameras should I understand?","Name active cameras and tell me what each one is for. I'll ignore unused recorder channels."],4:["I'll recommend the monitoring setup","I'll combine the exact recorder capability profile with your site context. Unknown capabilities stay unconfirmed."],5:["Review and start monitoring","Check the setup, approve WatchLog configuration, and I'll keep helping from the AI workspace."]};

  function chooseSite(id){setSiteId(id);setRecommendation(null);const name=sites.find((s)=>s.id===id)?.name||"";rememberSite(id,name);history.replaceState(null,"",withSite("/setup/",id));}
  async function addSite(e){e.preventDefault();if(!canManage||!newSite.trim())return;setBusy(true);setError("");const{error}=await supabase().rpc("wl_add_site",{p_name:newSite.trim()});setBusy(false);if(error){setError(say(error));return;}setNewSite("");setNote("Site created. Select it to continue setup.");await load();}
  async function issueCode(){if(!siteId||!canManage)return;setBusy(true);const{data,error}=await supabase().rpc("wl_issue_code",{p_site_id:siteId,p_days:14});setBusy(false);if(error){setError(say(error));return;}setNote(`Setup code ${data.code} created. It can be used once and expires in 14 days.`);await load();}
  async function copy(v){try{await navigator.clipboard.writeText(v);setNote("Copied.");}catch{setError("Could not copy automatically. Select the value and copy it manually.");}}
  function patchCamera(id,patch){setCameras((all)=>all.map((c)=>c.id===id?{...c,...patch}:c));}
  async function saveCamera(c){const{error}=await supabase().rpc("wl_ai_setup_camera",{p_site_id:siteId,p_camera_id:c.id,p_name:c.name||null,p_purpose:c.purpose||null,p_monitor:Boolean(c.monitor)});if(error){setError(say(error));return false;}return true;}
  async function saveCameras(){if(!canManage)return;setBusy(true);setError("");for(const c of cameras){if(!await saveCamera(c)){setBusy(false);return;}}const{error}=await supabase().rpc("wl_onboarding_advance",{p_site_id:siteId,p_step:"cameras_mapped",p_done:true});setBusy(false);if(error){setError(say(error));return;}setNote("Camera setup saved. WatchLog will use only monitored cameras for health and intelligence.");await loadContext(siteId);}
  async function saveBusinessContext(){if(!canManage||!siteType)return;const entrances=cameras.filter((c)=>c.monitor&&["entrance","perimeter","loading"].includes(c.purpose)).map((c)=>c.id);const reception=cameras.filter((c)=>c.monitor&&c.purpose==="reception").map((c)=>c.id);const management=cameras.filter((c)=>c.monitor&&c.purpose==="management").map((c)=>c.id);const critical=cameras.filter((c)=>c.monitor&&c.purpose==="restricted").map((c)=>c.id);setBusy(true);setError("");const{error}=await supabase().rpc("wl_upsert_site_context",{p_site_id:siteId,p_site_type:siteType,p_open_time:openTime||null,p_close_time:closeTime||null,p_overnight:false,p_working_days:workingDays,p_entrance_camera_ids:entrances,p_reception_camera_ids:reception,p_management_camera_ids:management,p_critical_camera_ids:critical,p_restricted_purposes:null,p_reporting_prefs:null,p_notification_prefs:null});setBusy(false);if(error){setError(say(error));return;}setNote("Site context saved.");await loadContext(siteId);}
  async function askRecommendation(){if(!siteId)return;setBusy(true);setError("");const prompt="Review this site's current WatchLog setup. Explain what this exact recorder supports, what WatchLog software should handle, which setup details are still missing, and recommend a practical monitoring configuration. Do not execute recorder changes.";const{data,error}=await supabase().functions.invoke("watchlog-ai",{body:{prompt,site_id:siteId,conversation_id:conversationId||null}});setBusy(false);if(error||data?.error){setError(data?.message||say(error)||"WatchLog AI could not prepare the recommendation.");return;}setConversationId(data.conversation_id||conversationId);setRecommendation(data);if(canManage)await supabase().rpc("wl_onboarding_advance",{p_site_id:siteId,p_step:"recommendation_reviewed",p_done:true});await loadContext(siteId);}
  async function approveSetup(){if(!canManage)return;setBusy(true);const{error}=await supabase().rpc("wl_onboarding_advance",{p_site_id:siteId,p_step:"approved",p_done:true});setBusy(false);if(error){setError(say(error));return;}setNote("WatchLog setup approved. Recorder-side changes still require their own safe approval.");await loadContext(siteId);}

  return <div className="shell"><Nav active="Setup" email={email} currentSiteId={siteId}/><main className={`main ${styles.embeddedMain}`}>
    <section className={styles.hero}><div className={styles.heroCopy}><div className={styles.eyebrow}>Guided setup</div><h1>{site?`Set up ${site.name} with WatchLog.`:"Set up your first site with WatchLog."}</h1><p>One step at a time. WatchLog uses your real recorder model and camera state, asks only for context it cannot discover, and never guesses unsupported capabilities.</p></div>{site&&<div className={styles.progressCard}><div className={styles.progressTop}><span>Setup progress</span><b>{progress}%</b></div><div className={styles.progressTrack}><span style={{width:`${progress}%`}}/></div><p>{stageCopy[stage]?.[0]||"Setup complete"}</p></div>}</section>
    {error&&<div className={styles.error}>{error}</div>}{note&&<div className={styles.note}>{note}</div>}
    <section className={styles.siteChooser}><div><label>Site</label><select value={siteId} onChange={(e)=>chooseSite(e.target.value)}><option value="">Select a site</option>{sites.map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div>{canManage&&<form onSubmit={addSite}><input value={newSite} onChange={(e)=>setNewSite(e.target.value)} placeholder="Add a new site"/><button disabled={busy||!newSite.trim()}>Add site</button></form>}</section>

    {!siteId?<section className={styles.empty}><Mark size={44}/><h2>Add or select a site</h2><p>Once a site exists, WatchLog can guide the connection and configuration.</p></section>:<div className={styles.layout}><div className={styles.flow}>
      <section className={styles.aiPrompt}><Mark size={28}/><div><span>WatchLog AI</span><h2>{stageCopy[stage]?.[0]}</h2><p>{stageCopy[stage]?.[1]}</p></div></section>

      {stage===1&&<section className={styles.stepCard}><div className={styles.stepHead}><span className={styles.stepNo}>1</span><div><h2>What kind of site is this?</h2><p>This powers after-hours intelligence, reports, journeys and recommendations.</p></div></div><div className={styles.siteTypes}>{SITE_TYPES.map(([v,label,desc])=><button key={v} className={siteType===v?styles.selected:""} onClick={()=>setSiteType(v)} disabled={!canManage}><b>{label}</b><span>{desc}</span></button>)}</div><div className={styles.hours}><div><label>Opens</label><input type="time" value={openTime} onChange={(e)=>setOpenTime(e.target.value)} disabled={!canManage}/></div><div><label>Closes</label><input type="time" value={closeTime} onChange={(e)=>setCloseTime(e.target.value)} disabled={!canManage}/></div><div className={styles.dayField}><label>Working days</label><div className={styles.days}>{DAYS.map(([n,l])=><button type="button" key={n} className={workingDays.includes(n)?styles.dayOn:""} onClick={()=>setWorkingDays((d)=>d.includes(n)?d.filter((x)=>x!==n):[...d,n].sort())} disabled={!canManage}>{l}</button>)}</div></div></div>{canManage&&<button className={styles.primary} onClick={saveBusinessContext} disabled={busy||!siteType}>Continue</button>}</section>}

      {stage===2&&<section className={styles.stepCard}><div className={styles.stepHead}><span className={styles.stepNo}>2</span><div><h2>Connect WatchLog to the camera system</h2><p>Run WatchLog on a Windows computer at this location. Recorder credentials stay on-site.</p></div></div><div className={styles.connectGrid}><div className={styles.downloadCard}><span>Windows site computer</span><h3>WatchLog for Windows</h3><p>Install it on a computer on the same network as the NVR/DVR.</p>{INSTALLER_URL?<a href={INSTALLER_URL}>Download WatchLog</a>:<div className={styles.unavailable}>The Windows installer is not configured for this environment yet.</div>}</div><div className={styles.codeCard}><span>Single-use setup code</span>{site?.open_code?<><strong>{site.open_code}</strong><button onClick={()=>copy(site.open_code)}>Copy code</button></>:<><strong>Not issued</strong>{canManage&&<button onClick={issueCode} disabled={busy}>Create setup code</button>}</>}<small>Valid for 14 days and usable once.</small></div></div><div className={styles.connectionState}><div><i className={context?.connectivity?.agent_online?styles.ok:""}/><span>WatchLog Agent</span><b>{context?.connectivity?.agent_online?"Online":"Waiting"}</b></div><div><i className={context?.recorder?.identified?styles.ok:""}/><span>Recorder</span><b>{recorderName(context)}</b></div><div><i className={cameras.length?styles.ok:""}/><span>Cameras</span><b>{cameras.length?`${cameras.length} discovered`:"Waiting"}</b></div></div></section>}

      {stage===3&&<section className={styles.stepCard}><div className={styles.stepHead}><span className={styles.stepNo}>3</span><div><h2>Which cameras should WatchLog understand?</h2><p>Rename active cameras and choose their purpose. Ignore unused recorder channels.</p></div></div>{!cameras.length?<div className={styles.waiting}>Camera channels will appear after the Site Agent discovers the recorder.</div>:<div className={styles.cameraGrid}>{cameras.map((c)=><article className={`${styles.cameraCard} ${!c.monitor?styles.ignored:""}`} key={c.id}><div className={styles.cameraTop}><span>Channel {c.channel}</span><label className={styles.switch}><input type="checkbox" checked={Boolean(c.monitor)} onChange={(e)=>patchCamera(c.id,{monitor:e.target.checked})} disabled={!canManage}/><i/></label></div><div className={styles.cameraPlaceholder}><span>{c.health_state==="offline"?"Camera unavailable":"Latest camera frame"}</span><small>{stateLabel(c.health_state)}</small></div><label>Name<input value={c.name||""} onChange={(e)=>patchCamera(c.id,{name:e.target.value})} disabled={!canManage||!c.monitor}/></label><label>Purpose<select value={c.purpose||"general"} onChange={(e)=>patchCamera(c.id,{purpose:e.target.value})} disabled={!canManage||!c.monitor}>{PURPOSES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><div className={styles.cameraFoot}><span>{c.monitor?`Recording: ${stateLabel(c.recording_state)}`:"Ignored / unused"}</span></div></article>)}</div>} {canManage&&cameras.length>0&&<div className={styles.actionRow}><span>{monitored} monitored · {cameras.length-monitored} ignored · {configured} purpose-mapped</span><button className={styles.primary} onClick={saveCameras} disabled={busy}>Save and continue</button></div>}</section>}

      {stage===4&&<section className={styles.stepCard}><div className={styles.stepHead}><span className={styles.stepNo}>4</span><div><h2>Let WatchLog recommend the monitoring setup</h2><p>Your exact recorder capability profile is combined with site context. Unsupported or unknown recorder features are not guessed.</p></div></div><div className={styles.deviceTruth}><div><span>Detected recorder</span><b>{recorderName(context)}</b></div><div><span>Capability evidence</span><b>{context?.capability_known?"Exact model profile loaded":"Not confirmed yet"}</b></div><div><span>Recorder changes</span><b>Human approval required</b></div></div>{!recommendation?<button className={styles.aiButton} onClick={askRecommendation} disabled={busy||!context?.recorder?.identified}><Mark size={22}/><span><b>{busy?"Preparing recommendation…":"Ask WatchLog to recommend the setup"}</b><small>Uses recorder capability truth + site context</small></span><em>→</em></button>:<div className={styles.recommendation}><div className={styles.aiBubble}><Mark size={24}/><p>{recommendation.answer}</p></div>{(recommendation.cards||[]).slice(0,5).map((card,i)=><div className={styles.recCard} key={i}><b>{card.title||stateLabel(card.type)}</b><p>{Object.entries(card.data||{}).slice(0,4).map(([k,v])=>`${stateLabel(k)}: ${humanValue(v)}`).join(" · ")||"WatchLog recommendation"}</p></div>)}<button className={styles.primary} onClick={()=>loadContext(siteId)}>Continue to review</button></div>}</section>}

      {stage===5&&<section className={`${styles.stepCard} ${styles.finish}`}><div className={styles.stepHead}><span className={styles.stepNo}>5</span><div><h2>Review and start monitoring</h2><p>Approving confirms WatchLog configuration. Recorder-side changes still require separate safe approval.</p></div></div><div className={styles.readiness}>{steps.map((s)=><div key={s.key}><span className={s.done?styles.readyYes:styles.readyNo}>{s.done?"✓":"○"}</span><b>{s.label}</b></div>)}</div><div className={styles.finalActions}>{canManage&&<button className={styles.primary} onClick={approveSetup} disabled={busy||!steps.find((s)=>s.key==="recommendation")?.done}>Approve WatchLog setup</button>}<a href={withSite("/ai/",siteId)}>Open WatchLog AI</a><a href={withSite("/site-health/",siteId)}>View Site Health</a></div></section>}
    </div>

    <aside className={styles.guide}><div className={styles.guideHead}><Mark size={27}/><div><b>Setup checklist</b><span>{stage===5?"Ready for review":`Step ${stage} of 5`}</span></div></div><div className={styles.setupTimeline}>{[1,2,3,4,5].map((n)=><div key={n} className={n<stage?styles.timelineDone:n===stage?styles.timelineActive:""}><span>{n<stage?"✓":n}</span><b>{["Site context","Connect cameras","Map cameras","AI recommendation","Review"][n-1]}</b></div>)}</div><div className={styles.guideFacts}><div><span>Agent</span><b>{context?.connectivity?.agent_online?"Online":"Not connected"}</b></div><div><span>Recorder</span><b>{recorderName(context)}</b></div><div><span>Cameras</span><b>{monitored} monitored</b></div></div><button className={styles.askLink} onClick={()=>location.href=withSite("/ai/",siteId)}>Ask WatchLog about setup →</button><div className={styles.safety}><b>Safe by design</b><p>Recorder credentials stay at the site. Recorder writes require explicit authorized approval.</p></div></aside>
    </div>}
  </main></div>;
}
