-- =====================================================================
-- 0066 — Recorder Capability KB, batch 2 (the broad multi-model loader 0061 deferred).
--
-- 18 entry Dahua/Hikvision XVR/NVR/DVR models, every fact OFFICIAL_DOCUMENTED from the
-- exact-model datasheet (none FIELD_VERIFIED). Silence is recorded as verdict 'unknown'
-- (never laundered into 'unsupported'); a datasheet whose Intelligent-Alarm list is
-- exhaustive yields 'unsupported'. Two hard rules stay structural:
--   * an 'unknown' verdict can never be read as unsupported,
--   * OFFICIAL documentation is never emitted as FIELD_VERIFIED.
-- Deliberate contrast preserved WITHIN a series: DH-XVR1B04-I lists an exhaustive
-- SMD-only alarm row (perimeter/face -> 'unsupported'), while its sibling DH-XVR1B16-I
-- has no such row (-> 'unknown'). The model must never generalize one across the other.
-- Generated from a reviewed capability matrix (supabase/_gen_0066.py).
-- =====================================================================

insert into public.recorder_capability_sources (id, vendor, source_type, doc_name, url, doc_version, retrieved_date, notes) values
 ('DAHUA-XVR-S10','Dahua','official','DH-XVR1B04-I datasheet (Cooper-I)','https://material.dahuasecurity.com/uploads/cpq/prm-os-srv-res/smart/datasheetzipfiles/XVR1B04-I_V2_datasheet_20230302.pdf','V2 Rev002 2023','2023-03-02'::date,'multi-model KB batch 2'),
 ('DAHUA-XVR-S11','Dahua','official','DH-XVR1B16-I datasheet (Cooper-I)','https://material.dahuasecurity.com/uploads/cpq/prm-os-srv-res/smart/datasheetzipfiles/XVR1B16-I_datasheet_20220530.pdf','Rev002 2022','2022-05-30'::date,'multi-model KB batch 2'),
 ('DAHUA-XVR-S12','Dahua','official','DH-XVR4104HS-I datasheet (XVR4000-I)','https://material.dahuasecurity.com/uploads/cpq/prm-os-srv-res/smart/datasheetzipfiles/XVR4104HS-I_datasheet_20220905.pdf','Rev002 2022','2022-09-05'::date,'multi-model KB batch 2'),
 ('DAHUA-XVR-S13','Dahua','official','DH-XVR4108HS-I datasheet (XVR4000-I)','https://material.dahuasecurity.com/uploads/cpq/prm-os-srv-res/smart/datasheetzipfiles/XVR4108HS-I_datasheet_20220530.pdf','Rev002 2022','2022-05-30'::date,'multi-model KB batch 2'),
 ('DAHUA-XVR-S14','Dahua','official','DH-XVR5104H-I3 datasheet (XVR5000-I3, HW v3.0)','https://material.dahuasecurity.com/uploads/cpq/prm-os-srv-res/smart/datasheetzipfiles/XVR5104H-I3_V3_datasheet_20240717.pdf','V3 Rev002 2024','2024-07-17'::date,'multi-model KB batch 2'),
 ('DAHUA-XVR-S15','Dahua','official','DH-XVR5108H-I3 datasheet (XVR5000-I3, HW v3.0)','https://material.dahuasecurity.com/uploads/cpq/prm-os-srv-res/smart/datasheetzipfiles/XVR5108H-I3_V3_datasheet_20240717.pdf','V3 Rev002 2024','2024-07-17'::date,'multi-model KB batch 2'),
 ('DAHUA-NVR-S20','Dahua','official','DHI-NVR4104HS-P-4KS2 datasheet (NVR4000-4KS2 Lite)','https://www.dahuasecurity.com/asset/upload/uploads/soft/20190115/DHI-NVR4104_4108HS-P-4KS2_datasheet_20190115.pdf','Rev001.001 2016','2019-01-15'::date,'multi-model KB batch 2'),
 ('DAHUA-NVR-S21','Dahua','official','DHI-NVR4108HS-P-4KS2 datasheet (shared 2-model doc)','https://www.dahuasecurity.com/asset/upload/uploads/soft/20190115/DHI-NVR4104_4108HS-P-4KS2_datasheet_20190115.pdf','Rev001.001 2016','2019-01-15'::date,'multi-model KB batch 2'),
 ('DAHUA-NVR-S22','Dahua','official','DHI-NVR2104HS-P-I2 datasheet (NVR2-I2 WizSense)','https://material.dahuasecurity.com/uploads/soft/20231018/NVR2104HS-P-I2_datasheet.pdf','Rev002 2022','2023-10-18'::date,'multi-model KB batch 2'),
 ('DAHUA-NVR-S23','Dahua','official','DHI-NVR2108HS-8P-I2 datasheet (NVR2-I2 WizSense)','https://material.dahuasecurity.com/uploads/cpq/prm-os-srv-res/smart/datasheetzipfiles/NVR2108HS-8P-I2_datasheet_20220614.pdf','Rev002 2022','2022-06-14'::date,'multi-model KB batch 2'),
 ('HIK-DVR-S30','Hikvision','official','DS-7104HGHI-K1 datasheet (Turbo HD DVR)','https://www.hikvision.com/content/dam/hikvision/products/S000000001/S000000132/S000000133/S000000138/OFR009576/M000018278/Data_Sheet/Datasheet-of_DS-7104HGHI-K1_V4.70.160_20230822.pdf','V4.70.160','2023-08-22'::date,'multi-model KB batch 2'),
 ('HIK-DVR-S31','Hikvision','official','DS-7108HGHI-K1 datasheet (Turbo HD DVR)','https://www.hikvision.com/content/dam/hikvision/products/S000000001/S000000132/S000000133/S000000138/OFR009576/M000018279/Data_Sheet/Datasheet-of_DS-7108HGHI-K1_V4.70.160_20230822.pdf','V4.70.160','2023-08-22'::date,'multi-model KB batch 2'),
 ('HIK-DVR-S32','Hikvision','official','iDS-7204HQHI-M1/S datasheet (Turbo AcuSense)','https://www.hikvision.com/content/dam/hikvision/products/S000000001/S000000132/S000000133/S000000821/OFR000174/M000007976/Data_Sheet/Datasheet-of-iDS-7204HQHI-M1_S_V4.71.000_20240110.pdf','V4.71.000','2024-01-10'::date,'multi-model KB batch 2'),
 ('HIK-DVR-S33','Hikvision','official','iDS-7208HQHI-M1/S datasheet (Turbo AcuSense)','https://assets.hikvision.com/prd/public/all/doc/m000007977/Datasheet-of-iDS-7208HQHI-M1_S_V4.71.000_20230621.pdf','V4.71.000','2023-06-21'::date,'multi-model KB batch 2'),
 ('HIK-NVR-S40','Hikvision','official','DS-7604NI-K1(B) datasheet (DS-7600NI-K1(B) series)','https://www.hikvision.com/content/dam/hikvision/products/S000000001/S000000002/S000000007/S000000026/OFR000040/M000000575/Data_Sheet/Datasheet-of_DS-7600NI-K1-B-NVR_3.4.96_20171025.pdf','V3.4.96','2017-10-25'::date,'multi-model KB batch 2'),
 ('HIK-NVR-S41','Hikvision','official','DS-7608NI-K1(B) datasheet (shared series doc)','https://www.hikvision.com/content/dam/hikvision/products/S000000001/S000000002/S000000007/S000000026/OFR000040/M000000575/Data_Sheet/Datasheet-of_DS-7600NI-K1-B-NVR_3.4.96_20171025.pdf','V3.4.96','2017-10-25'::date,'multi-model KB batch 2'),
 ('HIK-NVR-S42','Hikvision','official','DS-7616NI-Q2(D) datasheet (Q-series Pro NVR)','https://assets.hikvision.com/prd/public/all/doc/m000000579/Datasheet-of-DS-7616NI-Q2-NVRD_V4.71.200_20221031.pdf','V4.71.200','2022-10-31'::date,'multi-model KB batch 2'),
 ('HIK-NVR-S43','Hikvision','official','DS-7108NI-Q1/M(D) datasheet (Value 7 Series NVR)','https://www.hikvision.com/content/dam/hikvision/products/S000000001/S000000132/S000000007/S000000032/OFR000061/M000000621/Data_Sheet/Datasheet-of-DS-7108NI-Q1_M_Value-7-Series-NVR_V4.73.200_20230404.pdf','V4.73.200','2023-04-04'::date,'multi-model KB batch 2')
on conflict (id) do nothing;

insert into public.recorder_capabilities
 (vendor, model, series, firmware_applicability, capability, verdict, evidence_class, ai_location, read_supported, write_supported, safety_class, constraints, source_ids) values
 ('Dahua','DH-XVR1B04-I','Cooper-I','','human_vehicle_classification','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','SMD Plus recorder D:4; AI disabled if IP extension enabled',array['DAHUA-XVR-S10']),
 ('Dahua','DH-XVR1B04-I','Cooper-I','','line_crossing','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','Intelligent Alarm row = SMD Plus only (exhaustive)',array['DAHUA-XVR-S10']),
 ('Dahua','DH-XVR1B04-I','Cooper-I','','intrusion','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','Intelligent Alarm row = SMD Plus only (exhaustive)',array['DAHUA-XVR-S10']),
 ('Dahua','DH-XVR1B04-I','Cooper-I','','face_detection','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','Intelligent Alarm row = SMD Plus only (exhaustive)',array['DAHUA-XVR-S10']),
 ('Dahua','DH-XVR1B04-I','Cooper-I','','face_recognition','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','Intelligent Alarm row = SMD Plus only (exhaustive)',array['DAHUA-XVR-S10']),
 ('Dahua','DH-XVR1B04-I','Cooper-I','','anpr_lpr','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','Intelligent Alarm row = SMD Plus only (exhaustive)',array['DAHUA-XVR-S10']),
 ('Dahua','DH-XVR1B04-I','Cooper-I','','people_counting','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','Intelligent Alarm row = SMD Plus only (exhaustive)',array['DAHUA-XVR-S10']),
 ('Dahua','DH-XVR1B04-I','Cooper-I','','heatmap','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','Intelligent Alarm row = SMD Plus only (exhaustive)',array['DAHUA-XVR-S10']),
 ('Dahua','DH-XVR1B04-I','Cooper-I','','video_loss','supported','OFFICIAL_DOCUMENTED','recorder',true,false,'read','',array['DAHUA-XVR-S10']),
 ('Dahua','DH-XVR1B04-I','Cooper-I','','tamper','supported','OFFICIAL_DOCUMENTED','recorder',true,false,'read','',array['DAHUA-XVR-S10']),
 ('Dahua','DH-XVR1B04-I','Cooper-I','','time_ntp_config','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','',array['DAHUA-XVR-S10']),
 ('Dahua','DH-XVR1B16-I','Cooper-I','','human_vehicle_classification','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','SMD Plus recorder D:8 on 16-analog box; disabled if IP extension',array['DAHUA-XVR-S11']),
 ('Dahua','DH-XVR1B16-I','Cooper-I','','line_crossing','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no intelligent-alarm row; datasheet silent on IVS/Face/Perimeter',array['DAHUA-XVR-S11']),
 ('Dahua','DH-XVR1B16-I','Cooper-I','','intrusion','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no intelligent-alarm row; datasheet silent on IVS/Face/Perimeter',array['DAHUA-XVR-S11']),
 ('Dahua','DH-XVR1B16-I','Cooper-I','','face_detection','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no intelligent-alarm row; datasheet silent on IVS/Face/Perimeter',array['DAHUA-XVR-S11']),
 ('Dahua','DH-XVR1B16-I','Cooper-I','','face_recognition','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no intelligent-alarm row; datasheet silent on IVS/Face/Perimeter',array['DAHUA-XVR-S11']),
 ('Dahua','DH-XVR1B16-I','Cooper-I','','anpr_lpr','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no intelligent-alarm row; datasheet silent on IVS/Face/Perimeter',array['DAHUA-XVR-S11']),
 ('Dahua','DH-XVR1B16-I','Cooper-I','','people_counting','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no intelligent-alarm row; datasheet silent on IVS/Face/Perimeter',array['DAHUA-XVR-S11']),
 ('Dahua','DH-XVR1B16-I','Cooper-I','','heatmap','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no intelligent-alarm row; datasheet silent on IVS/Face/Perimeter',array['DAHUA-XVR-S11']),
 ('Dahua','DH-XVR1B16-I','Cooper-I','','video_loss','supported','OFFICIAL_DOCUMENTED','recorder',true,false,'read','',array['DAHUA-XVR-S11']),
 ('Dahua','DH-XVR1B16-I','Cooper-I','','tamper','supported','OFFICIAL_DOCUMENTED','recorder',true,false,'read','',array['DAHUA-XVR-S11']),
 ('Dahua','DH-XVR1B16-I','Cooper-I','','time_ntp_config','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','',array['DAHUA-XVR-S11']),
 ('Dahua','DH-XVR4104HS-I','XVR4000-I','','human_vehicle_classification','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','SMD Plus recorder D:4; disabled if IP extension',array['DAHUA-XVR-S12']),
 ('Dahua','DH-XVR4104HS-I','XVR4000-I','','line_crossing','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no intelligent-alarm row; datasheet silent on IVS/Face/Perimeter',array['DAHUA-XVR-S12']),
 ('Dahua','DH-XVR4104HS-I','XVR4000-I','','intrusion','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no intelligent-alarm row; datasheet silent on IVS/Face/Perimeter',array['DAHUA-XVR-S12']),
 ('Dahua','DH-XVR4104HS-I','XVR4000-I','','face_detection','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no intelligent-alarm row; datasheet silent on IVS/Face/Perimeter',array['DAHUA-XVR-S12']),
 ('Dahua','DH-XVR4104HS-I','XVR4000-I','','face_recognition','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no intelligent-alarm row; datasheet silent on IVS/Face/Perimeter',array['DAHUA-XVR-S12']),
 ('Dahua','DH-XVR4104HS-I','XVR4000-I','','anpr_lpr','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no intelligent-alarm row; datasheet silent on IVS/Face/Perimeter',array['DAHUA-XVR-S12']),
 ('Dahua','DH-XVR4104HS-I','XVR4000-I','','people_counting','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no intelligent-alarm row; datasheet silent on IVS/Face/Perimeter',array['DAHUA-XVR-S12']),
 ('Dahua','DH-XVR4104HS-I','XVR4000-I','','heatmap','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no intelligent-alarm row; datasheet silent on IVS/Face/Perimeter',array['DAHUA-XVR-S12']),
 ('Dahua','DH-XVR4104HS-I','XVR4000-I','','video_loss','supported','OFFICIAL_DOCUMENTED','recorder',true,false,'read','',array['DAHUA-XVR-S12']),
 ('Dahua','DH-XVR4104HS-I','XVR4000-I','','tamper','supported','OFFICIAL_DOCUMENTED','recorder',true,false,'read','',array['DAHUA-XVR-S12']),
 ('Dahua','DH-XVR4104HS-I','XVR4000-I','','time_ntp_config','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','',array['DAHUA-XVR-S12']),
 ('Dahua','DH-XVR4108HS-I','XVR4000-I','','human_vehicle_classification','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','SMD Plus recorder D:8; disabled if IP extension',array['DAHUA-XVR-S13']),
 ('Dahua','DH-XVR4108HS-I','XVR4000-I','','line_crossing','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no intelligent-alarm row; datasheet silent on IVS/Face/Perimeter',array['DAHUA-XVR-S13']),
 ('Dahua','DH-XVR4108HS-I','XVR4000-I','','intrusion','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no intelligent-alarm row; datasheet silent on IVS/Face/Perimeter',array['DAHUA-XVR-S13']),
 ('Dahua','DH-XVR4108HS-I','XVR4000-I','','face_detection','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no intelligent-alarm row; datasheet silent on IVS/Face/Perimeter',array['DAHUA-XVR-S13']),
 ('Dahua','DH-XVR4108HS-I','XVR4000-I','','face_recognition','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no intelligent-alarm row; datasheet silent on IVS/Face/Perimeter',array['DAHUA-XVR-S13']),
 ('Dahua','DH-XVR4108HS-I','XVR4000-I','','anpr_lpr','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no intelligent-alarm row; datasheet silent on IVS/Face/Perimeter',array['DAHUA-XVR-S13']),
 ('Dahua','DH-XVR4108HS-I','XVR4000-I','','people_counting','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no intelligent-alarm row; datasheet silent on IVS/Face/Perimeter',array['DAHUA-XVR-S13']),
 ('Dahua','DH-XVR4108HS-I','XVR4000-I','','heatmap','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no intelligent-alarm row; datasheet silent on IVS/Face/Perimeter',array['DAHUA-XVR-S13']),
 ('Dahua','DH-XVR4108HS-I','XVR4000-I','','video_loss','supported','OFFICIAL_DOCUMENTED','recorder',true,false,'read','',array['DAHUA-XVR-S13']),
 ('Dahua','DH-XVR4108HS-I','XVR4000-I','','tamper','supported','OFFICIAL_DOCUMENTED','recorder',true,false,'read','',array['DAHUA-XVR-S13']),
 ('Dahua','DH-XVR4108HS-I','XVR4000-I','','time_ntp_config','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','',array['DAHUA-XVR-S13']),
 ('Dahua','DH-XVR5104H-I3','XVR5000-I3','HW3.0','human_vehicle_classification','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','SMD recorder D:4 + camera 6; AI Mode exclusive Face|IVS&SMD|SMD; IP extension disables',array['DAHUA-XVR-S14']),
 ('Dahua','DH-XVR5104H-I3','XVR5000-I3','HW3.0','line_crossing','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','Perimeter recorder 2ch adv/4ch gen, <=10 IVS/ch; needs AI Mode IVS&SMD',array['DAHUA-XVR-S14']),
 ('Dahua','DH-XVR5104H-I3','XVR5000-I3','HW3.0','intrusion','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','Perimeter recorder 2ch adv/4ch gen; needs AI Mode IVS&SMD',array['DAHUA-XVR-S14']),
 ('Dahua','DH-XVR5104H-I3','XVR5000-I3','HW3.0','face_detection','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','AI by recorder D:1; needs AI Mode Face',array['DAHUA-XVR-S14']),
 ('Dahua','DH-XVR5104H-I3','XVR5000-I3','HW3.0','face_recognition','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','D:1; DB 10 dbs/10000 imgs; needs AI Mode Face',array['DAHUA-XVR-S14']),
 ('Dahua','DH-XVR5104H-I3','XVR5000-I3','HW3.0','anpr_lpr','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','Intelligent Alarm list exhaustive: Face det/rec, Perimeter, SMD Plus',array['DAHUA-XVR-S14']),
 ('Dahua','DH-XVR5104H-I3','XVR5000-I3','HW3.0','people_counting','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','Intelligent Alarm list exhaustive',array['DAHUA-XVR-S14']),
 ('Dahua','DH-XVR5104H-I3','XVR5000-I3','HW3.0','heatmap','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','Intelligent Alarm list exhaustive',array['DAHUA-XVR-S14']),
 ('Dahua','DH-XVR5104H-I3','XVR5000-I3','HW3.0','video_loss','supported','OFFICIAL_DOCUMENTED','recorder',true,false,'read','',array['DAHUA-XVR-S14']),
 ('Dahua','DH-XVR5104H-I3','XVR5000-I3','HW3.0','tamper','supported','OFFICIAL_DOCUMENTED','recorder',true,false,'read','',array['DAHUA-XVR-S14']),
 ('Dahua','DH-XVR5104H-I3','XVR5000-I3','HW3.0','time_ntp_config','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','',array['DAHUA-XVR-S14']),
 ('Dahua','DH-XVR5108H-I3','XVR5000-I3','HW3.0','human_vehicle_classification','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','SMD recorder D:8 + camera 12; AI Mode exclusive; IP extension disables',array['DAHUA-XVR-S15']),
 ('Dahua','DH-XVR5108H-I3','XVR5000-I3','HW3.0','line_crossing','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','Perimeter recorder 2ch adv/4ch gen, <=10 IVS/ch; needs AI Mode IVS&SMD',array['DAHUA-XVR-S15']),
 ('Dahua','DH-XVR5108H-I3','XVR5000-I3','HW3.0','intrusion','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','Perimeter recorder 2ch adv/4ch gen; needs AI Mode IVS&SMD',array['DAHUA-XVR-S15']),
 ('Dahua','DH-XVR5108H-I3','XVR5000-I3','HW3.0','face_detection','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','D:2; needs AI Mode Face',array['DAHUA-XVR-S15']),
 ('Dahua','DH-XVR5108H-I3','XVR5000-I3','HW3.0','face_recognition','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','D:2; DB 10/10000; needs AI Mode Face',array['DAHUA-XVR-S15']),
 ('Dahua','DH-XVR5108H-I3','XVR5000-I3','HW3.0','anpr_lpr','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','Intelligent Alarm list exhaustive: Face det/rec, Perimeter, SMD Plus',array['DAHUA-XVR-S15']),
 ('Dahua','DH-XVR5108H-I3','XVR5000-I3','HW3.0','people_counting','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','Intelligent Alarm list exhaustive',array['DAHUA-XVR-S15']),
 ('Dahua','DH-XVR5108H-I3','XVR5000-I3','HW3.0','heatmap','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','Intelligent Alarm list exhaustive',array['DAHUA-XVR-S15']),
 ('Dahua','DH-XVR5108H-I3','XVR5000-I3','HW3.0','video_loss','supported','OFFICIAL_DOCUMENTED','recorder',true,false,'read','',array['DAHUA-XVR-S15']),
 ('Dahua','DH-XVR5108H-I3','XVR5000-I3','HW3.0','tamper','supported','OFFICIAL_DOCUMENTED','recorder',true,false,'read','',array['DAHUA-XVR-S15']),
 ('Dahua','DH-XVR5108H-I3','XVR5000-I3','HW3.0','time_ntp_config','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','',array['DAHUA-XVR-S15']),
 ('Dahua','DHI-NVR4104HS-P-4KS2','NVR4000-4KS2 Lite','','human_vehicle_classification','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no recorder-side AI; SMD not documented on this Lite gen',array['DAHUA-NVR-S20']),
 ('Dahua','DHI-NVR4104HS-P-4KS2','NVR4000-4KS2 Lite','','line_crossing','by_camera','OFFICIAL_DOCUMENTED','camera',null,null,'na','camera IVS recorded by NVR, not recorder-computed',array['DAHUA-NVR-S20']),
 ('Dahua','DHI-NVR4104HS-P-4KS2','NVR4000-4KS2 Lite','','intrusion','by_camera','OFFICIAL_DOCUMENTED','camera',null,null,'na','camera IVS recorded by NVR, not recorder-computed',array['DAHUA-NVR-S20']),
 ('Dahua','DHI-NVR4104HS-P-4KS2','NVR4000-4KS2 Lite','','face_detection','by_camera','OFFICIAL_DOCUMENTED','camera',null,null,'na','facial detection from IP cameras only',array['DAHUA-NVR-S20']),
 ('Dahua','DHI-NVR4104HS-P-4KS2','NVR4000-4KS2 Lite','','face_recognition','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','datasheet silent',array['DAHUA-NVR-S20']),
 ('Dahua','DHI-NVR4104HS-P-4KS2','NVR4000-4KS2 Lite','','anpr_lpr','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','datasheet silent',array['DAHUA-NVR-S20']),
 ('Dahua','DHI-NVR4104HS-P-4KS2','NVR4000-4KS2 Lite','','people_counting','by_camera','OFFICIAL_DOCUMENTED','camera',null,null,'na','business analytics from cameras',array['DAHUA-NVR-S20']),
 ('Dahua','DHI-NVR4104HS-P-4KS2','NVR4000-4KS2 Lite','','heatmap','by_camera','OFFICIAL_DOCUMENTED','camera',null,null,'na','business analytics from cameras',array['DAHUA-NVR-S20']),
 ('Dahua','DHI-NVR4104HS-P-4KS2','NVR4000-4KS2 Lite','','video_loss','supported','OFFICIAL_DOCUMENTED','recorder',true,false,'read','legacy Video Loss wording',array['DAHUA-NVR-S20']),
 ('Dahua','DHI-NVR4104HS-P-4KS2','NVR4000-4KS2 Lite','','tamper','supported','OFFICIAL_DOCUMENTED','recorder',true,false,'read','Tampering',array['DAHUA-NVR-S20']),
 ('Dahua','DHI-NVR4104HS-P-4KS2','NVR4000-4KS2 Lite','','time_ntp_config','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','',array['DAHUA-NVR-S20']),
 ('Dahua','DHI-NVR4108HS-P-4KS2','NVR4000-4KS2 Lite','','human_vehicle_classification','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no recorder-side AI; SMD not documented on this Lite gen',array['DAHUA-NVR-S21']),
 ('Dahua','DHI-NVR4108HS-P-4KS2','NVR4000-4KS2 Lite','','line_crossing','by_camera','OFFICIAL_DOCUMENTED','camera',null,null,'na','camera IVS recorded by NVR, not recorder-computed',array['DAHUA-NVR-S21']),
 ('Dahua','DHI-NVR4108HS-P-4KS2','NVR4000-4KS2 Lite','','intrusion','by_camera','OFFICIAL_DOCUMENTED','camera',null,null,'na','camera IVS recorded by NVR, not recorder-computed',array['DAHUA-NVR-S21']),
 ('Dahua','DHI-NVR4108HS-P-4KS2','NVR4000-4KS2 Lite','','face_detection','by_camera','OFFICIAL_DOCUMENTED','camera',null,null,'na','facial detection from IP cameras only',array['DAHUA-NVR-S21']),
 ('Dahua','DHI-NVR4108HS-P-4KS2','NVR4000-4KS2 Lite','','face_recognition','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','datasheet silent',array['DAHUA-NVR-S21']),
 ('Dahua','DHI-NVR4108HS-P-4KS2','NVR4000-4KS2 Lite','','anpr_lpr','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','datasheet silent',array['DAHUA-NVR-S21']),
 ('Dahua','DHI-NVR4108HS-P-4KS2','NVR4000-4KS2 Lite','','people_counting','by_camera','OFFICIAL_DOCUMENTED','camera',null,null,'na','business analytics from cameras',array['DAHUA-NVR-S21']),
 ('Dahua','DHI-NVR4108HS-P-4KS2','NVR4000-4KS2 Lite','','heatmap','by_camera','OFFICIAL_DOCUMENTED','camera',null,null,'na','business analytics from cameras',array['DAHUA-NVR-S21']),
 ('Dahua','DHI-NVR4108HS-P-4KS2','NVR4000-4KS2 Lite','','video_loss','supported','OFFICIAL_DOCUMENTED','recorder',true,false,'read','legacy Video Loss wording',array['DAHUA-NVR-S21']),
 ('Dahua','DHI-NVR4108HS-P-4KS2','NVR4000-4KS2 Lite','','tamper','supported','OFFICIAL_DOCUMENTED','recorder',true,false,'read','Tampering',array['DAHUA-NVR-S21']),
 ('Dahua','DHI-NVR4108HS-P-4KS2','NVR4000-4KS2 Lite','','time_ntp_config','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','',array['DAHUA-NVR-S21']),
 ('Dahua','DHI-NVR2104HS-P-I2','NVR2-I2 WizSense','','human_vehicle_classification','supported','OFFICIAL_DOCUMENTED','both',true,true,'safe_write','SMD Plus AI-by-NVR D:4 + by-camera 4',array['DAHUA-NVR-S22']),
 ('Dahua','DHI-NVR2104HS-P-I2','NVR2-I2 WizSense','','line_crossing','supported','OFFICIAL_DOCUMENTED','both',true,true,'safe_write','Perimeter AI-by-NVR D:1 + by-camera 4',array['DAHUA-NVR-S22']),
 ('Dahua','DHI-NVR2104HS-P-I2','NVR2-I2 WizSense','','intrusion','supported','OFFICIAL_DOCUMENTED','both',true,true,'safe_write','Perimeter AI-by-NVR D:1 + by-camera 4',array['DAHUA-NVR-S22']),
 ('Dahua','DHI-NVR2104HS-P-I2','NVR2-I2 WizSense','','face_detection','supported','OFFICIAL_DOCUMENTED','both',true,true,'safe_write','AI-by-NVR D:1 + by-camera 4',array['DAHUA-NVR-S22']),
 ('Dahua','DHI-NVR2104HS-P-I2','NVR2-I2 WizSense','','face_recognition','supported','OFFICIAL_DOCUMENTED','both',true,true,'safe_write','AI-by-NVR D:1; DB 10 dbs/5000 imgs',array['DAHUA-NVR-S22']),
 ('Dahua','DHI-NVR2104HS-P-I2','NVR2-I2 WizSense','','anpr_lpr','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','datasheet silent',array['DAHUA-NVR-S22']),
 ('Dahua','DHI-NVR2104HS-P-I2','NVR2-I2 WizSense','','people_counting','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','datasheet silent',array['DAHUA-NVR-S22']),
 ('Dahua','DHI-NVR2104HS-P-I2','NVR2-I2 WizSense','','heatmap','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','datasheet silent',array['DAHUA-NVR-S22']),
 ('Dahua','DHI-NVR2104HS-P-I2','NVR2-I2 WizSense','','video_loss','supported','OFFICIAL_DOCUMENTED','recorder',true,false,'read','Camera offline anomaly + video loss general alarm',array['DAHUA-NVR-S22']),
 ('Dahua','DHI-NVR2104HS-P-I2','NVR2-I2 WizSense','','tamper','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','explicit tamper not itemized; privacy masking only',array['DAHUA-NVR-S22']),
 ('Dahua','DHI-NVR2104HS-P-I2','NVR2-I2 WizSense','','time_ntp_config','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','',array['DAHUA-NVR-S22']),
 ('Dahua','DHI-NVR2108HS-8P-I2','NVR2-I2 WizSense','','human_vehicle_classification','supported','OFFICIAL_DOCUMENTED','both',true,true,'safe_write','SMD Plus AI-by-NVR D:4 + by-camera 6',array['DAHUA-NVR-S23']),
 ('Dahua','DHI-NVR2108HS-8P-I2','NVR2-I2 WizSense','','line_crossing','supported','OFFICIAL_DOCUMENTED','both',true,true,'safe_write','Perimeter AI-by-NVR D:1 + by-camera 4',array['DAHUA-NVR-S23']),
 ('Dahua','DHI-NVR2108HS-8P-I2','NVR2-I2 WizSense','','intrusion','supported','OFFICIAL_DOCUMENTED','both',true,true,'safe_write','Perimeter AI-by-NVR D:1 + by-camera 4',array['DAHUA-NVR-S23']),
 ('Dahua','DHI-NVR2108HS-8P-I2','NVR2-I2 WizSense','','face_detection','supported','OFFICIAL_DOCUMENTED','both',true,true,'safe_write','AI-by-NVR D:1 + by-camera 5',array['DAHUA-NVR-S23']),
 ('Dahua','DHI-NVR2108HS-8P-I2','NVR2-I2 WizSense','','face_recognition','supported','OFFICIAL_DOCUMENTED','both',true,true,'safe_write','AI-by-NVR D:1; DB 10/5000; by-camera 5',array['DAHUA-NVR-S23']),
 ('Dahua','DHI-NVR2108HS-8P-I2','NVR2-I2 WizSense','','anpr_lpr','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','datasheet silent',array['DAHUA-NVR-S23']),
 ('Dahua','DHI-NVR2108HS-8P-I2','NVR2-I2 WizSense','','people_counting','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','datasheet silent',array['DAHUA-NVR-S23']),
 ('Dahua','DHI-NVR2108HS-8P-I2','NVR2-I2 WizSense','','heatmap','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','datasheet silent',array['DAHUA-NVR-S23']),
 ('Dahua','DHI-NVR2108HS-8P-I2','NVR2-I2 WizSense','','video_loss','supported','OFFICIAL_DOCUMENTED','recorder',true,false,'read','Camera offline anomaly + video loss general alarm',array['DAHUA-NVR-S23']),
 ('Dahua','DHI-NVR2108HS-8P-I2','NVR2-I2 WizSense','','tamper','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','explicit tamper not itemized; privacy masking only',array['DAHUA-NVR-S23']),
 ('Dahua','DHI-NVR2108HS-8P-I2','NVR2-I2 WizSense','','time_ntp_config','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','',array['DAHUA-NVR-S23']),
 ('Hikvision','DS-7104HGHI-K1','Turbo HD DVR HGHI-K1','','human_vehicle_classification','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','Motion Detection 2.0 deep-learning human/vehicle, all analog ch',array['HIK-DVR-S30']),
 ('Hikvision','DS-7104HGHI-K1','Turbo HD DVR HGHI-K1','','line_crossing','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','smart section exhaustive = MD2.0 only; no perimeter/face',array['HIK-DVR-S30']),
 ('Hikvision','DS-7104HGHI-K1','Turbo HD DVR HGHI-K1','','intrusion','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','smart section exhaustive = MD2.0 only; no perimeter/face',array['HIK-DVR-S30']),
 ('Hikvision','DS-7104HGHI-K1','Turbo HD DVR HGHI-K1','','face_detection','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','smart section exhaustive = MD2.0 only; no perimeter/face',array['HIK-DVR-S30']),
 ('Hikvision','DS-7104HGHI-K1','Turbo HD DVR HGHI-K1','','face_recognition','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','smart section exhaustive = MD2.0 only; no perimeter/face',array['HIK-DVR-S30']),
 ('Hikvision','DS-7104HGHI-K1','Turbo HD DVR HGHI-K1','','anpr_lpr','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','smart section exhaustive = MD2.0 only; no perimeter/face',array['HIK-DVR-S30']),
 ('Hikvision','DS-7104HGHI-K1','Turbo HD DVR HGHI-K1','','people_counting','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','smart section exhaustive = MD2.0 only; no perimeter/face',array['HIK-DVR-S30']),
 ('Hikvision','DS-7104HGHI-K1','Turbo HD DVR HGHI-K1','','heatmap','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','smart section exhaustive = MD2.0 only; no perimeter/face',array['HIK-DVR-S30']),
 ('Hikvision','DS-7104HGHI-K1','Turbo HD DVR HGHI-K1','','video_loss','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','datasheet has no exception/event table',array['HIK-DVR-S30']),
 ('Hikvision','DS-7104HGHI-K1','Turbo HD DVR HGHI-K1','','tamper','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','datasheet has no exception/event table',array['HIK-DVR-S30']),
 ('Hikvision','DS-7104HGHI-K1','Turbo HD DVR HGHI-K1','','time_ntp_config','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','',array['HIK-DVR-S30']),
 ('Hikvision','DS-7108HGHI-K1','Turbo HD DVR HGHI-K1','','human_vehicle_classification','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','Motion Detection 2.0 deep-learning human/vehicle, all analog ch',array['HIK-DVR-S31']),
 ('Hikvision','DS-7108HGHI-K1','Turbo HD DVR HGHI-K1','','line_crossing','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','smart section exhaustive = MD2.0 only; no perimeter/face',array['HIK-DVR-S31']),
 ('Hikvision','DS-7108HGHI-K1','Turbo HD DVR HGHI-K1','','intrusion','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','smart section exhaustive = MD2.0 only; no perimeter/face',array['HIK-DVR-S31']),
 ('Hikvision','DS-7108HGHI-K1','Turbo HD DVR HGHI-K1','','face_detection','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','smart section exhaustive = MD2.0 only; no perimeter/face',array['HIK-DVR-S31']),
 ('Hikvision','DS-7108HGHI-K1','Turbo HD DVR HGHI-K1','','face_recognition','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','smart section exhaustive = MD2.0 only; no perimeter/face',array['HIK-DVR-S31']),
 ('Hikvision','DS-7108HGHI-K1','Turbo HD DVR HGHI-K1','','anpr_lpr','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','smart section exhaustive = MD2.0 only; no perimeter/face',array['HIK-DVR-S31']),
 ('Hikvision','DS-7108HGHI-K1','Turbo HD DVR HGHI-K1','','people_counting','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','smart section exhaustive = MD2.0 only; no perimeter/face',array['HIK-DVR-S31']),
 ('Hikvision','DS-7108HGHI-K1','Turbo HD DVR HGHI-K1','','heatmap','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','smart section exhaustive = MD2.0 only; no perimeter/face',array['HIK-DVR-S31']),
 ('Hikvision','DS-7108HGHI-K1','Turbo HD DVR HGHI-K1','','video_loss','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','datasheet has no exception/event table',array['HIK-DVR-S31']),
 ('Hikvision','DS-7108HGHI-K1','Turbo HD DVR HGHI-K1','','tamper','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','datasheet has no exception/event table',array['HIK-DVR-S31']),
 ('Hikvision','DS-7108HGHI-K1','Turbo HD DVR HGHI-K1','','time_ntp_config','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','',array['HIK-DVR-S31']),
 ('Hikvision','iDS-7204HQHI-M1/S','Turbo AcuSense HQHI-M1/S','','human_vehicle_classification','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','MD2.0 all analog ch; mutually exclusive with Perimeter',array['HIK-DVR-S32']),
 ('Hikvision','iDS-7204HQHI-M1/S','Turbo AcuSense HQHI-M1/S','','line_crossing','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','Perimeter recorder D:2; MD2.0 and Perimeter cannot both be enabled',array['HIK-DVR-S32']),
 ('Hikvision','iDS-7204HQHI-M1/S','Turbo AcuSense HQHI-M1/S','','intrusion','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','Perimeter recorder D:2; MD2.0 and Perimeter cannot both be enabled',array['HIK-DVR-S32']),
 ('Hikvision','iDS-7204HQHI-M1/S','Turbo AcuSense HQHI-M1/S','','face_detection','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','Facial Detection & Capture',array['HIK-DVR-S32']),
 ('Hikvision','iDS-7204HQHI-M1/S','Turbo AcuSense HQHI-M1/S','','face_recognition','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','/S variant is detection-only; no face recognition',array['HIK-DVR-S32']),
 ('Hikvision','iDS-7204HQHI-M1/S','Turbo AcuSense HQHI-M1/S','','anpr_lpr','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','smart section lists only MD2.0/Perimeter/Facial; silent on ANPR',array['HIK-DVR-S32']),
 ('Hikvision','iDS-7204HQHI-M1/S','Turbo AcuSense HQHI-M1/S','','people_counting','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','smart section lists only MD2.0/Perimeter/Facial; silent',array['HIK-DVR-S32']),
 ('Hikvision','iDS-7204HQHI-M1/S','Turbo AcuSense HQHI-M1/S','','heatmap','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','smart section lists only MD2.0/Perimeter/Facial; silent',array['HIK-DVR-S32']),
 ('Hikvision','iDS-7204HQHI-M1/S','Turbo AcuSense HQHI-M1/S','','video_loss','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','datasheet has no exception/event table',array['HIK-DVR-S32']),
 ('Hikvision','iDS-7204HQHI-M1/S','Turbo AcuSense HQHI-M1/S','','tamper','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','datasheet has no exception/event table',array['HIK-DVR-S32']),
 ('Hikvision','iDS-7204HQHI-M1/S','Turbo AcuSense HQHI-M1/S','','time_ntp_config','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','',array['HIK-DVR-S32']),
 ('Hikvision','iDS-7208HQHI-M1/S','Turbo AcuSense HQHI-M1/S','','human_vehicle_classification','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','MD2.0 all analog ch; mutually exclusive with Perimeter',array['HIK-DVR-S33']),
 ('Hikvision','iDS-7208HQHI-M1/S','Turbo AcuSense HQHI-M1/S','','line_crossing','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','Perimeter recorder D:4 (vs 2 on the 7204); MD2.0 and Perimeter mutually exclusive',array['HIK-DVR-S33']),
 ('Hikvision','iDS-7208HQHI-M1/S','Turbo AcuSense HQHI-M1/S','','intrusion','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','Perimeter recorder D:4 (vs 2 on the 7204); MD2.0 and Perimeter mutually exclusive',array['HIK-DVR-S33']),
 ('Hikvision','iDS-7208HQHI-M1/S','Turbo AcuSense HQHI-M1/S','','face_detection','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','Facial Detection & Capture',array['HIK-DVR-S33']),
 ('Hikvision','iDS-7208HQHI-M1/S','Turbo AcuSense HQHI-M1/S','','face_recognition','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','/S variant is detection-only; no face recognition',array['HIK-DVR-S33']),
 ('Hikvision','iDS-7208HQHI-M1/S','Turbo AcuSense HQHI-M1/S','','anpr_lpr','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','smart section lists only MD2.0/Perimeter/Facial; silent on ANPR',array['HIK-DVR-S33']),
 ('Hikvision','iDS-7208HQHI-M1/S','Turbo AcuSense HQHI-M1/S','','people_counting','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','smart section lists only MD2.0/Perimeter/Facial; silent',array['HIK-DVR-S33']),
 ('Hikvision','iDS-7208HQHI-M1/S','Turbo AcuSense HQHI-M1/S','','heatmap','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','smart section lists only MD2.0/Perimeter/Facial; silent',array['HIK-DVR-S33']),
 ('Hikvision','iDS-7208HQHI-M1/S','Turbo AcuSense HQHI-M1/S','','video_loss','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','datasheet has no exception/event table',array['HIK-DVR-S33']),
 ('Hikvision','iDS-7208HQHI-M1/S','Turbo AcuSense HQHI-M1/S','','tamper','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','datasheet has no exception/event table',array['HIK-DVR-S33']),
 ('Hikvision','iDS-7208HQHI-M1/S','Turbo AcuSense HQHI-M1/S','','time_ntp_config','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','',array['HIK-DVR-S33']),
 ('Hikvision','DS-7604NI-K1(B)','DS-7600NI-K1(B)','','human_vehicle_classification','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no recorder AI engine; camera VCA generic, not itemized',array['HIK-NVR-S40']),
 ('Hikvision','DS-7604NI-K1(B)','DS-7600NI-K1(B)','','line_crossing','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','generic camera VCA, specific types not itemized — do not infer',array['HIK-NVR-S40']),
 ('Hikvision','DS-7604NI-K1(B)','DS-7600NI-K1(B)','','intrusion','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','generic camera VCA, specific types not itemized — do not infer',array['HIK-NVR-S40']),
 ('Hikvision','DS-7604NI-K1(B)','DS-7600NI-K1(B)','','face_detection','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','generic camera VCA, specific types not itemized — do not infer',array['HIK-NVR-S40']),
 ('Hikvision','DS-7604NI-K1(B)','DS-7600NI-K1(B)','','face_recognition','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','generic camera VCA, specific types not itemized — do not infer',array['HIK-NVR-S40']),
 ('Hikvision','DS-7604NI-K1(B)','DS-7600NI-K1(B)','','anpr_lpr','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','generic camera VCA, specific types not itemized — do not infer',array['HIK-NVR-S40']),
 ('Hikvision','DS-7604NI-K1(B)','DS-7600NI-K1(B)','','people_counting','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','generic camera VCA, specific types not itemized — do not infer',array['HIK-NVR-S40']),
 ('Hikvision','DS-7604NI-K1(B)','DS-7600NI-K1(B)','','heatmap','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','generic camera VCA, specific types not itemized — do not infer',array['HIK-NVR-S40']),
 ('Hikvision','DS-7604NI-K1(B)','DS-7600NI-K1(B)','','video_loss','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no exception/event table (sparse 2017 datasheet)',array['HIK-NVR-S40']),
 ('Hikvision','DS-7604NI-K1(B)','DS-7600NI-K1(B)','','tamper','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no exception/event table (sparse 2017 datasheet)',array['HIK-NVR-S40']),
 ('Hikvision','DS-7604NI-K1(B)','DS-7600NI-K1(B)','','time_ntp_config','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','',array['HIK-NVR-S40']),
 ('Hikvision','DS-7608NI-K1(B)','DS-7600NI-K1(B)','','human_vehicle_classification','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no recorder AI engine; camera VCA generic, not itemized',array['HIK-NVR-S41']),
 ('Hikvision','DS-7608NI-K1(B)','DS-7600NI-K1(B)','','line_crossing','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','generic camera VCA, specific types not itemized — do not infer',array['HIK-NVR-S41']),
 ('Hikvision','DS-7608NI-K1(B)','DS-7600NI-K1(B)','','intrusion','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','generic camera VCA, specific types not itemized — do not infer',array['HIK-NVR-S41']),
 ('Hikvision','DS-7608NI-K1(B)','DS-7600NI-K1(B)','','face_detection','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','generic camera VCA, specific types not itemized — do not infer',array['HIK-NVR-S41']),
 ('Hikvision','DS-7608NI-K1(B)','DS-7600NI-K1(B)','','face_recognition','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','generic camera VCA, specific types not itemized — do not infer',array['HIK-NVR-S41']),
 ('Hikvision','DS-7608NI-K1(B)','DS-7600NI-K1(B)','','anpr_lpr','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','generic camera VCA, specific types not itemized — do not infer',array['HIK-NVR-S41']),
 ('Hikvision','DS-7608NI-K1(B)','DS-7600NI-K1(B)','','people_counting','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','generic camera VCA, specific types not itemized — do not infer',array['HIK-NVR-S41']),
 ('Hikvision','DS-7608NI-K1(B)','DS-7600NI-K1(B)','','heatmap','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','generic camera VCA, specific types not itemized — do not infer',array['HIK-NVR-S41']),
 ('Hikvision','DS-7608NI-K1(B)','DS-7600NI-K1(B)','','video_loss','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no exception/event table (sparse 2017 datasheet)',array['HIK-NVR-S41']),
 ('Hikvision','DS-7608NI-K1(B)','DS-7600NI-K1(B)','','tamper','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no exception/event table (sparse 2017 datasheet)',array['HIK-NVR-S41']),
 ('Hikvision','DS-7608NI-K1(B)','DS-7600NI-K1(B)','','time_ntp_config','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','',array['HIK-NVR-S41']),
 ('Hikvision','DS-7616NI-Q2','Q-series Pro NVR','','human_vehicle_classification','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','Motion Detection 2.0 Human/Vehicle Analysis recorder D:4 (not AcuSense)',array['HIK-NVR-S42']),
 ('Hikvision','DS-7616NI-Q2','Q-series Pro NVR','','line_crossing','by_camera','OFFICIAL_DOCUMENTED','camera',null,null,'na','configurable special camera smart functions; camera-side',array['HIK-NVR-S42']),
 ('Hikvision','DS-7616NI-Q2','Q-series Pro NVR','','intrusion','by_camera','OFFICIAL_DOCUMENTED','camera',null,null,'na','configurable special camera smart functions; camera-side',array['HIK-NVR-S42']),
 ('Hikvision','DS-7616NI-Q2','Q-series Pro NVR','','face_detection','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','not listed; silent',array['HIK-NVR-S42']),
 ('Hikvision','DS-7616NI-Q2','Q-series Pro NVR','','face_recognition','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','not listed; silent',array['HIK-NVR-S42']),
 ('Hikvision','DS-7616NI-Q2','Q-series Pro NVR','','anpr_lpr','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','not listed; silent',array['HIK-NVR-S42']),
 ('Hikvision','DS-7616NI-Q2','Q-series Pro NVR','','people_counting','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','not listed; silent',array['HIK-NVR-S42']),
 ('Hikvision','DS-7616NI-Q2','Q-series Pro NVR','','heatmap','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','not listed; silent',array['HIK-NVR-S42']),
 ('Hikvision','DS-7616NI-Q2','Q-series Pro NVR','','video_loss','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','datasheet has no exception/event table',array['HIK-NVR-S42']),
 ('Hikvision','DS-7616NI-Q2','Q-series Pro NVR','','tamper','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','datasheet has no exception/event table',array['HIK-NVR-S42']),
 ('Hikvision','DS-7616NI-Q2','Q-series Pro NVR','','time_ntp_config','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','',array['HIK-NVR-S42']),
 ('Hikvision','DS-7108NI-Q1/M','Value 7 Series NVR','','human_vehicle_classification','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','no recorder AI engine / no MD2.0 row',array['HIK-NVR-S43']),
 ('Hikvision','DS-7108NI-Q1/M','Value 7 Series NVR','','line_crossing','supported','OFFICIAL_DOCUMENTED',null,true,null,'na','documented "supports line crossing" but camera-vs-recorder location NOT stated',array['HIK-NVR-S43']),
 ('Hikvision','DS-7108NI-Q1/M','Value 7 Series NVR','','intrusion','supported','OFFICIAL_DOCUMENTED',null,true,null,'na','documented "supports intrusion detection" but location NOT stated',array['HIK-NVR-S43']),
 ('Hikvision','DS-7108NI-Q1/M','Value 7 Series NVR','','face_detection','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','silent',array['HIK-NVR-S43']),
 ('Hikvision','DS-7108NI-Q1/M','Value 7 Series NVR','','face_recognition','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','silent',array['HIK-NVR-S43']),
 ('Hikvision','DS-7108NI-Q1/M','Value 7 Series NVR','','anpr_lpr','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','silent',array['HIK-NVR-S43']),
 ('Hikvision','DS-7108NI-Q1/M','Value 7 Series NVR','','people_counting','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','silent',array['HIK-NVR-S43']),
 ('Hikvision','DS-7108NI-Q1/M','Value 7 Series NVR','','heatmap','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','silent',array['HIK-NVR-S43']),
 ('Hikvision','DS-7108NI-Q1/M','Value 7 Series NVR','','video_loss','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','datasheet has no exception/event table',array['HIK-NVR-S43']),
 ('Hikvision','DS-7108NI-Q1/M','Value 7 Series NVR','','tamper','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','datasheet has no exception/event table',array['HIK-NVR-S43']),
 ('Hikvision','DS-7108NI-Q1/M','Value 7 Series NVR','','time_ntp_config','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','',array['HIK-NVR-S43'])
on conflict (vendor, model, capability, firmware_applicability) do nothing;
