-- =====================================================================
-- 0077 — Recorder Capability KB, batch 3 (8 high-priority models common in Pakistan CCTV).
-- All OFFICIAL_DOCUMENTED. Where a model could not be sourced cleanly on the official domain,
-- the provenance note records the caveat HONESTLY (mirror / substitution / translated); the
-- fact is still datasheet-grade, never field-verified. Datasheet silence -> 'unknown'; an
-- exhaustive Intelligent-Alarm list -> 'unsupported'; camera-side AI -> 'by_camera'.
-- Generated from a reviewed matrix (supabase/_gen_0077.py).
-- =====================================================================

insert into public.recorder_capability_sources (id, vendor, source_type, doc_name, url, doc_version, retrieved_date, notes) values
 ('DAHUA-XVR-S16','Dahua','official','DH-XVR5216AN-I3 datasheet (XVR5000-I3 WizSense)','https://material.dahuasecurity.com/uploads/cpq/prm-os-srv-res/smart/datasheetzipfiles/XVR5216AN-I3_datasheet_20240722.pdf','Rev002 2024','2024-07-22'::date,'official datasheet'),
 ('DAHUA-XVR-S17','Dahua','official','DH-XVR5232AN-I3 datasheet (XVR5000-I3 WizSense, HW V2.0)','https://materialfile.dahuasecurity.com/uploads/cpq/prm-os-srv-res/smart/datasheetzipfiles/XVR5232AN-I3_V2_datasheet_20241114.pdf','Rev002 2024','2024-11-14'::date,'official datasheet; facts gated to HW V2.0'),
 ('DAHUA-NVR-S24','Dahua','official','DHI-NVR4216-16P-I datasheet (NVR4000-I AI series)','https://www.dahuasecurity.com/','Rev001.001 2019','2019-02-26'::date,'MIRROR: model discontinued/purged from dahuasecurity.com; genuine manufacturer PDF via distributor mirror'),
 ('DAHUA-NVR-S25','Dahua','official','DHI-NVR5216-16P-I/L datasheet (NVR5000-I/L WizMind AcuPick)','https://www.dahuasecurity.com/products/All-Products/Network-Recorders/WizMind-Series/NVR5-IL/2HDD/NVR5216-16P-I/L','Rev001.001 2021','2021-09-28'::date,'TRANSLATED: readable copy was the Chinese-language edition; EN by-recorder/by-camera split cross-referenced'),
 ('HIK-DVR-S34','Hikvision','official','iDS-7208HQHI-M2/FA (via M1/FA datasheet)','https://pro-av.hikvision.com/','V4.71.000','2023-06-21'::date,'SUBSTITUTION: exact M2/FA not published; M1/FA (same platform, 1->2 HDD) used'),
 ('HIK-NVR-S44','Hikvision','official','DS-7616NI-K2/16P datasheet (Pro K NVR)','https://pro-av.hikvision.com/','V4.71.410','2023-09-20'::date,'official datasheet; all analytics camera-side'),
 ('HIK-NVR-S45','Hikvision','official','iDS-7716NXI-I4/16P/X(B) datasheet (DeepinMind NVR)','https://pro-av.hikvision.com/','V4.1.70','2019-08-13'::date,'official datasheet; 2019 baseline rev — newer revs may itemize more'),
 ('DAHUA-XVR-S18','Dahua','official','DH-XVR1B04H-I datasheet (Cooper-I WizSense)','https://material.dahuasecurity.com/uploads/cpq/prm-os-srv-res/smart/datasheetzipfiles/XVR1B04H-I_datasheet_20220530.pdf','V2 Rev002','2022-05-30'::date,'official datasheet/HTML spec')
on conflict (id) do nothing;

insert into public.recorder_capabilities
 (vendor, model, series, firmware_applicability, capability, verdict, evidence_class, ai_location, read_supported, write_supported, safety_class, constraints, source_ids) values
 ('Dahua','DH-XVR5216AN-I3','XVR5000-I3','','human_vehicle_classification','supported','OFFICIAL_DOCUMENTED','both',true,true,'safe_write','SMD Plus recorder 16ch + camera 24ch; AI Mode exclusive Face|IVS&SMD|SMD; IP extension disables',array['DAHUA-XVR-S16']),
 ('Dahua','DH-XVR5216AN-I3','XVR5000-I3','','line_crossing','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','Perimeter recorder 2ch adv/4ch gen, 10 IVS/ch; needs AI Mode IVS&SMD',array['DAHUA-XVR-S16']),
 ('Dahua','DH-XVR5216AN-I3','XVR5000-I3','','intrusion','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','Perimeter recorder 2ch adv/4ch gen; needs AI Mode IVS&SMD',array['DAHUA-XVR-S16']),
 ('Dahua','DH-XVR5216AN-I3','XVR5000-I3','','face_detection','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','D:2 (12 face imgs/s/ch); needs AI Mode Face',array['DAHUA-XVR-S16']),
 ('Dahua','DH-XVR5216AN-I3','XVR5000-I3','','face_recognition','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','D:2; DB 10 dbs/10000 imgs; needs AI Mode Face',array['DAHUA-XVR-S16']),
 ('Dahua','DH-XVR5216AN-I3','XVR5000-I3','','anpr_lpr','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','exhaustive Intelligent Alarm: Face det/rec, Perimeter, SMD Plus',array['DAHUA-XVR-S16']),
 ('Dahua','DH-XVR5216AN-I3','XVR5000-I3','','people_counting','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','exhaustive Intelligent Alarm',array['DAHUA-XVR-S16']),
 ('Dahua','DH-XVR5216AN-I3','XVR5000-I3','','heatmap','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','exhaustive Intelligent Alarm',array['DAHUA-XVR-S16']),
 ('Dahua','DH-XVR5216AN-I3','XVR5000-I3','','video_loss','supported','OFFICIAL_DOCUMENTED','recorder',true,false,'read','Anomaly Alarm: video loss + camera offline',array['DAHUA-XVR-S16']),
 ('Dahua','DH-XVR5216AN-I3','XVR5000-I3','','tamper','supported','OFFICIAL_DOCUMENTED','recorder',true,false,'read','video tampering',array['DAHUA-XVR-S16']),
 ('Dahua','DH-XVR5216AN-I3','XVR5000-I3','','time_ntp_config','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','',array['DAHUA-XVR-S16']),
 ('Dahua','DH-XVR5232AN-I3','XVR5000-I3','HW2.0','human_vehicle_classification','supported','OFFICIAL_DOCUMENTED','both',true,true,'safe_write','SMD Plus recorder 32ch + camera 48ch; Face conflicts with SMD/Perimeter; Encode-Enhancement disables AI',array['DAHUA-XVR-S17']),
 ('Dahua','DH-XVR5232AN-I3','XVR5000-I3','HW2.0','line_crossing','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','Perimeter recorder 2ch adv/8ch gen (8ch), 10 IVS/ch',array['DAHUA-XVR-S17']),
 ('Dahua','DH-XVR5232AN-I3','XVR5000-I3','HW2.0','intrusion','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','Perimeter recorder 2ch adv/8ch gen',array['DAHUA-XVR-S17']),
 ('Dahua','DH-XVR5232AN-I3','XVR5000-I3','HW2.0','face_detection','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','D:2 (12 face imgs/s/ch)',array['DAHUA-XVR-S17']),
 ('Dahua','DH-XVR5232AN-I3','XVR5000-I3','HW2.0','face_recognition','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','D:2; DB 10 dbs/10000 imgs; conflicts with SMD/Perimeter',array['DAHUA-XVR-S17']),
 ('Dahua','DH-XVR5232AN-I3','XVR5000-I3','HW2.0','anpr_lpr','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','exhaustive Intelligent Alarm',array['DAHUA-XVR-S17']),
 ('Dahua','DH-XVR5232AN-I3','XVR5000-I3','HW2.0','people_counting','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','exhaustive Intelligent Alarm',array['DAHUA-XVR-S17']),
 ('Dahua','DH-XVR5232AN-I3','XVR5000-I3','HW2.0','heatmap','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','exhaustive Intelligent Alarm',array['DAHUA-XVR-S17']),
 ('Dahua','DH-XVR5232AN-I3','XVR5000-I3','HW2.0','video_loss','supported','OFFICIAL_DOCUMENTED','recorder',true,false,'read','video loss + camera offline',array['DAHUA-XVR-S17']),
 ('Dahua','DH-XVR5232AN-I3','XVR5000-I3','HW2.0','tamper','supported','OFFICIAL_DOCUMENTED','recorder',true,false,'read','video tampering',array['DAHUA-XVR-S17']),
 ('Dahua','DH-XVR5232AN-I3','XVR5000-I3','HW2.0','time_ntp_config','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','',array['DAHUA-XVR-S17']),
 ('Dahua','DHI-NVR4216-16P-I','NVR4000-I','','human_vehicle_classification','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','Perimeter human/vehicle secondary recognition; metadata search',array['DAHUA-NVR-S24']),
 ('Dahua','DHI-NVR4216-16P-I','NVR4000-I','','line_crossing','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','Perimeter recorder 4ch, 10 IVS rules; tripwire',array['DAHUA-NVR-S24']),
 ('Dahua','DHI-NVR4216-16P-I','NVR4000-I','','intrusion','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','Perimeter recorder 4ch; intrusion',array['DAHUA-NVR-S24']),
 ('Dahua','DHI-NVR4216-16P-I','NVR4000-I','','face_detection','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','face capture/detection with FD camera',array['DAHUA-NVR-S24']),
 ('Dahua','DHI-NVR4216-16P-I','NVR4000-I','','face_recognition','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','2ch video / 8ch picture stream FR; DB 10 dbs/20000 imgs; 12 face pics/s',array['DAHUA-NVR-S24']),
 ('Dahua','DHI-NVR4216-16P-I','NVR4000-I','','anpr_lpr','by_camera','OFFICIAL_DOCUMENTED','camera',null,null,'na','ANPR by Dahua ITC camera; recorder does list mgmt + search only',array['DAHUA-NVR-S24']),
 ('Dahua','DHI-NVR4216-16P-I','NVR4000-I','','people_counting','by_camera','OFFICIAL_DOCUMENTED','camera',null,null,'na','AI-series application; camera-side',array['DAHUA-NVR-S24']),
 ('Dahua','DHI-NVR4216-16P-I','NVR4000-I','','heatmap','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','not mentioned in datasheet',array['DAHUA-NVR-S24']),
 ('Dahua','DHI-NVR4216-16P-I','NVR4000-I','','video_loss','supported','OFFICIAL_DOCUMENTED','recorder',true,false,'read','Video Detection: Video Loss',array['DAHUA-NVR-S24']),
 ('Dahua','DHI-NVR4216-16P-I','NVR4000-I','','tamper','supported','OFFICIAL_DOCUMENTED','recorder',true,false,'read','Tampering',array['DAHUA-NVR-S24']),
 ('Dahua','DHI-NVR4216-16P-I','NVR4000-I','','time_ntp_config','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','',array['DAHUA-NVR-S24']),
 ('Dahua','DHI-NVR5216-16P-I/L','NVR5000-I/L','','human_vehicle_classification','supported','OFFICIAL_DOCUMENTED','both',true,true,'safe_write','SMD Plus recorder 8ch + by camera; perimeter human/vehicle; AcuPick max 16ch',array['DAHUA-NVR-S25']),
 ('Dahua','DHI-NVR5216-16P-I/L','NVR5000-I/L','','line_crossing','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','Perimeter recorder 4ch (up to 12ch total), 10 IVS rules',array['DAHUA-NVR-S25']),
 ('Dahua','DHI-NVR5216-16P-I/L','NVR5000-I/L','','intrusion','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','Perimeter recorder 4ch; human/vehicle classification',array['DAHUA-NVR-S25']),
 ('Dahua','DHI-NVR5216-16P-I/L','NVR5000-I/L','','face_detection','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','D:2',array['DAHUA-NVR-S25']),
 ('Dahua','DHI-NVR5216-16P-I/L','NVR5000-I/L','','face_recognition','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','D:2 (16 face pics/s); 4ch video/16ch picture FR; DB 20 dbs/200000 imgs',array['DAHUA-NVR-S25']),
 ('Dahua','DHI-NVR5216-16P-I/L','NVR5000-I/L','','anpr_lpr','by_camera','OFFICIAL_DOCUMENTED','camera',null,null,'na','Dahua ANPR = AI-by-camera (WizMind); recorder ingests',array['DAHUA-NVR-S25']),
 ('Dahua','DHI-NVR5216-16P-I/L','NVR5000-I/L','','people_counting','by_camera','OFFICIAL_DOCUMENTED','camera',null,null,'na','Dahua People Counting = AI-by-camera',array['DAHUA-NVR-S25']),
 ('Dahua','DHI-NVR5216-16P-I/L','NVR5000-I/L','','heatmap','by_camera','OFFICIAL_DOCUMENTED','camera',null,null,'na','Heat Map = AI-by-camera',array['DAHUA-NVR-S25']),
 ('Dahua','DHI-NVR5216-16P-I/L','NVR5000-I/L','','video_loss','supported','OFFICIAL_DOCUMENTED','recorder',true,false,'read','WizMind NVR video-detection',array['DAHUA-NVR-S25']),
 ('Dahua','DHI-NVR5216-16P-I/L','NVR5000-I/L','','tamper','supported','OFFICIAL_DOCUMENTED','recorder',true,false,'read','Tampering/Camera Masking',array['DAHUA-NVR-S25']),
 ('Dahua','DHI-NVR5216-16P-I/L','NVR5000-I/L','','time_ntp_config','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','',array['DAHUA-NVR-S25']),
 ('Hikvision','iDS-7208HQHI-M2/FA','Turbo AcuSense HQHI-M2/FA','','human_vehicle_classification','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','MD2.0 all analog ch; face-comparison|MD2.0|perimeter mutually exclusive',array['HIK-DVR-S34']),
 ('Hikvision','iDS-7208HQHI-M2/FA','Turbo AcuSense HQHI-M2/FA','','line_crossing','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','deep-learning perimeter (line crossing + intrusion); mutually exclusive with MD2.0/face',array['HIK-DVR-S34']),
 ('Hikvision','iDS-7208HQHI-M2/FA','Turbo AcuSense HQHI-M2/FA','','intrusion','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','deep-learning perimeter; mutually exclusive with MD2.0/face',array['HIK-DVR-S34']),
 ('Hikvision','iDS-7208HQHI-M2/FA','Turbo AcuSense HQHI-M2/FA','','face_detection','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','face capture/comparison pipeline',array['HIK-DVR-S34']),
 ('Hikvision','iDS-7208HQHI-M2/FA','Turbo AcuSense HQHI-M2/FA','','face_recognition','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','1-ch face picture comparison (HD analog); up to 16 libs / 500 pics total',array['HIK-DVR-S34']),
 ('Hikvision','iDS-7208HQHI-M2/FA','Turbo AcuSense HQHI-M2/FA','','anpr_lpr','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','not documented',array['HIK-DVR-S34']),
 ('Hikvision','iDS-7208HQHI-M2/FA','Turbo AcuSense HQHI-M2/FA','','people_counting','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','not documented',array['HIK-DVR-S34']),
 ('Hikvision','iDS-7208HQHI-M2/FA','Turbo AcuSense HQHI-M2/FA','','heatmap','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','not documented',array['HIK-DVR-S34']),
 ('Hikvision','iDS-7208HQHI-M2/FA','Turbo AcuSense HQHI-M2/FA','','video_loss','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','datasheet silent — no exception row',array['HIK-DVR-S34']),
 ('Hikvision','iDS-7208HQHI-M2/FA','Turbo AcuSense HQHI-M2/FA','','tamper','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','datasheet silent',array['HIK-DVR-S34']),
 ('Hikvision','iDS-7208HQHI-M2/FA','Turbo AcuSense HQHI-M2/FA','','time_ntp_config','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','',array['HIK-DVR-S34']),
 ('Hikvision','DS-7616NI-K2/16P','Pro K NVR','','human_vehicle_classification','by_camera','OFFICIAL_DOCUMENTED','camera',null,null,'na','no recorder AI engine; camera special smart functions only',array['HIK-NVR-S44']),
 ('Hikvision','DS-7616NI-K2/16P','Pro K NVR','','line_crossing','by_camera','OFFICIAL_DOCUMENTED','camera',null,null,'na','special camera smart functions: VCA (motion, line crossing, intrusion)',array['HIK-NVR-S44']),
 ('Hikvision','DS-7616NI-K2/16P','Pro K NVR','','intrusion','by_camera','OFFICIAL_DOCUMENTED','camera',null,null,'na','special camera smart functions',array['HIK-NVR-S44']),
 ('Hikvision','DS-7616NI-K2/16P','Pro K NVR','','face_detection','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','not listed; camera-VCA passthrough',array['HIK-NVR-S44']),
 ('Hikvision','DS-7616NI-K2/16P','Pro K NVR','','face_recognition','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','K-series has no recorder-side facial-recognition engine',array['HIK-NVR-S44']),
 ('Hikvision','DS-7616NI-K2/16P','Pro K NVR','','anpr_lpr','by_camera','OFFICIAL_DOCUMENTED','camera',null,null,'na','ANPR = camera smart function',array['HIK-NVR-S44']),
 ('Hikvision','DS-7616NI-K2/16P','Pro K NVR','','people_counting','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','not documented; camera-dependent',array['HIK-NVR-S44']),
 ('Hikvision','DS-7616NI-K2/16P','Pro K NVR','','heatmap','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','not documented; camera-dependent',array['HIK-NVR-S44']),
 ('Hikvision','DS-7616NI-K2/16P','Pro K NVR','','video_loss','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','minimal datasheet — no exception row',array['HIK-NVR-S44']),
 ('Hikvision','DS-7616NI-K2/16P','Pro K NVR','','tamper','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','datasheet silent',array['HIK-NVR-S44']),
 ('Hikvision','DS-7616NI-K2/16P','Pro K NVR','','time_ntp_config','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','',array['HIK-NVR-S44']),
 ('Hikvision','iDS-7716NXI-I4/16P/X','DeepinMind NVR','','human_vehicle_classification','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','16-ch human/vehicle recognition; facial-analytics & human/vehicle mutually exclusive',array['HIK-NVR-S45']),
 ('Hikvision','iDS-7716NXI-I4/16P/X','DeepinMind NVR','','line_crossing','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','recorder-side multiple VCA + human/vehicle analysis (not itemized by name)',array['HIK-NVR-S45']),
 ('Hikvision','iDS-7716NXI-I4/16P/X','DeepinMind NVR','','intrusion','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','recorder-side VCA / human-vehicle analysis',array['HIK-NVR-S45']),
 ('Hikvision','iDS-7716NXI-I4/16P/X','DeepinMind NVR','','face_detection','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','8-ch face capture',array['HIK-NVR-S45']),
 ('Hikvision','iDS-7716NXI-I4/16P/X','DeepinMind NVR','','face_recognition','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','16-ch face comparison; 32 libraries / 100000 pictures; mutually exclusive with human/vehicle',array['HIK-NVR-S45']),
 ('Hikvision','iDS-7716NXI-I4/16P/X','DeepinMind NVR','','anpr_lpr','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','not documented in this (B) rev',array['HIK-NVR-S45']),
 ('Hikvision','iDS-7716NXI-I4/16P/X','DeepinMind NVR','','people_counting','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','not documented',array['HIK-NVR-S45']),
 ('Hikvision','iDS-7716NXI-I4/16P/X','DeepinMind NVR','','heatmap','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','not documented',array['HIK-NVR-S45']),
 ('Hikvision','iDS-7716NXI-I4/16P/X','DeepinMind NVR','','video_loss','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','datasheet silent',array['HIK-NVR-S45']),
 ('Hikvision','iDS-7716NXI-I4/16P/X','DeepinMind NVR','','tamper','unknown','OFFICIAL_DOCUMENTED',null,null,null,'na','datasheet silent',array['HIK-NVR-S45']),
 ('Hikvision','iDS-7716NXI-I4/16P/X','DeepinMind NVR','','time_ntp_config','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','',array['HIK-NVR-S45']),
 ('Dahua','DH-XVR1B04H-I','Cooper-I','','human_vehicle_classification','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','SMD Plus recorder 4ch; IP extension disables SMD',array['DAHUA-XVR-S18']),
 ('Dahua','DH-XVR1B04H-I','Cooper-I','','line_crossing','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','Cooper-I: only recorder AI is SMD Plus; no perimeter',array['DAHUA-XVR-S18']),
 ('Dahua','DH-XVR1B04H-I','Cooper-I','','intrusion','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','Cooper-I: no perimeter',array['DAHUA-XVR-S18']),
 ('Dahua','DH-XVR1B04H-I','Cooper-I','','face_detection','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','not on Cooper-I',array['DAHUA-XVR-S18']),
 ('Dahua','DH-XVR1B04H-I','Cooper-I','','face_recognition','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','not on Cooper-I',array['DAHUA-XVR-S18']),
 ('Dahua','DH-XVR1B04H-I','Cooper-I','','anpr_lpr','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','not on Cooper-I',array['DAHUA-XVR-S18']),
 ('Dahua','DH-XVR1B04H-I','Cooper-I','','people_counting','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','not on Cooper-I',array['DAHUA-XVR-S18']),
 ('Dahua','DH-XVR1B04H-I','Cooper-I','','heatmap','unsupported','OFFICIAL_DOCUMENTED','na',null,null,'na','not on Cooper-I',array['DAHUA-XVR-S18']),
 ('Dahua','DH-XVR1B04H-I','Cooper-I','','video_loss','supported','OFFICIAL_DOCUMENTED','recorder',true,false,'read','Video loss',array['DAHUA-XVR-S18']),
 ('Dahua','DH-XVR1B04H-I','Cooper-I','','tamper','supported','OFFICIAL_DOCUMENTED','recorder',true,false,'read','Video tampering',array['DAHUA-XVR-S18']),
 ('Dahua','DH-XVR1B04H-I','Cooper-I','','time_ntp_config','supported','OFFICIAL_DOCUMENTED','recorder',true,true,'safe_write','',array['DAHUA-XVR-S18'])
on conflict (vendor, model, capability, firmware_applicability) do nothing;
