"use client";

import { Fragment, useCallback, useEffect, useRef, useState } from "react";
import { supabase, say } from "../../lib/supabase";
import { Nav } from "../shell";
import ui from "../portal.module.css";

const REFRESH_MS = 10000;
function liveness(lastSeen) { if (!lastSeen) return ["s-unk","never seen"]; const age=(Date.now()-Date.parse(lastSeen))/1000; if(age<180)return["s-ok","online"]; if(age<1800)return["s-warn","stale"]; return["s-bad","offline"]; }
function ago(ts) { if(!ts)return"never"; const s=Math.max(0,Math.round((Date.now()-Date.parse(ts))/1000)); if(s<60)return s+"s ago"; if(s<3600)return Math.round(s/60)+"m ago"; if(s<86400)return Math.round(s/3600)+"h ago"; return Math.round(s/86400)+"d ago"; }
function humanType(v){ return String(v||"event").replace(/^analytic_/,"").replaceAll("_"," ").replace(/\b\w/g,(c)=>c.toUpperCase()); }
function exact(ts){ try{return new Date(ts).toLocaleString();}catch{return String(ts||"");} }

export default function Dashboard(){
  const [data,setData]=useState(null),[error,setError]=useState(""),[days,setDays]=useState(7),[email,setEmail]=useState(""),[stamp,setStamp]=useState("");
  const shots=useRef(new Map()); const [,force]=useState(0);
  const load=useCallback(async(d)=>{const sb=supabase();const{data:{session}}=await sb.auth.getSession();if(!session){location.replace("/login/");return;}setEmail(session.user.email||"");const{data:res,error}=await sb.rpc("wl_portal_overview",{p_days:d});if(error){setError(say(error));return;}if(!res||!res.tenant){location.replace("/onboarding/");return;}setError("");setData(res);setStamp(new Date().toLocaleTimeString());},[]);
  useEffect(()=>{load(days);const t=setInterval(()=>load(days),REFRESH_MS);return()=>clearInterval(t);},[days,load]);
  async function loadShot(eventId){if(shots.current.has(eventId))return;shots.current.set(eventId,null);const{data}=await supabase().rpc("wl_portal_snapshot",{p_event_id:eventId});shots.current.set(eventId,data?.image_b64?`data:${data.content_type||"image/jpeg"};base64,${data.image_b64}`:false);force((n)=>n+1);}
  useEffect(()=>{(data?.recent||[]).filter((e)=>e.has_snapshot).slice(0,8).forEach((e)=>loadShot(e.event_id));},[data]);
  if(!data&&!error)return <div className="center"><p className="muted">Loading your sites...</p></div>;

  const agents=data?.agents||[],health=data?.health||{},offlineAgents=health.offline_agents||[],silentCameras=health.silent_cameras||[],faults24=health.faults_24h||[];
  const attentionCount=offlineAgents.length+silentCameras.length+faults24.length,offBySite={}; offlineAgents.forEach((a)=>{offBySite[a.site]=(offBySite[a.site]||0)+1;});
  const attentionItems=[...Object.entries(offBySite).map(([site,n])=>`${n} agent${n>1?"s":""} offline on ${site}`),...(silentCameras.length?[`${silentCameras.length} camera${silentCameras.length>1?"s":""} silent`]:[]),...(faults24.length?[`${faults24.length} fault${faults24.length>1?"s":""} in the last 24h`]:[])];
  const online=agents.filter((a)=>liveness(a.last_seen_at)[0]==="s-ok").length,bySite={};agents.forEach((a)=>{(bySite[a.site]=bySite[a.site]||[]).push(a);});
  const withShots=(data?.recent||[]).filter((e)=>e.has_snapshot).slice(0,8),maxType=Math.max(1,...(data?.by_type||[]).map((t)=>t.count));

  return <div className="shell"><Nav active="Overview" email={email} right={<><span className="muted hide-sm" style={{fontSize:"var(--font-size-xs)"}}>updated {stamp}</span><select value={days} onChange={(e)=>setDays(Number(e.target.value))} style={{width:"auto",margin:0}} aria-label="Overview date range"><option value={1}>24 hours</option><option value={7}>7 days</option><option value={30}>30 days</option></select></>}/>
    <main className="main">
      <header className={ui.pageHead}><div><div className={ui.eyebrow}>The platform</div><h1>Every site, one operational view.</h1><p>Incidents, reporting status and site health are summarized here. Open a dedicated surface when something needs investigation.</p></div><div className={ui.headActions}><a className={ui.secondaryLink} href="/site-health/">Review Site Health</a><a className={ui.primaryLink} href="/incidents/">Review incidents</a></div></header>
      {error&&<div className="err">{error}</div>}
      <div className={"banner"+(attentionCount?"":" clear")}>{attentionCount?<><b>{attentionCount} thing{attentionCount>1?"s":""} need attention</b><ul>{attentionItems.map((t,i)=><li key={i}>{t}</li>)}</ul><div style={{marginTop:10}}><a href="/site-health/">Open Site Health</a></div></>:<><b>Everything is reporting normally.</b><div className="muted" style={{fontSize:"var(--font-size-sm)",marginTop:4}}>No offline agents, silent cameras or recent equipment faults were reported.</div></>}</div>
      <section className={ui.metricGrid}><div className={ui.metric}><div className={ui.metricValue}>{data?.totals?.events??0}</div><div className={ui.metricLabel}>Events · {data?.window_days}d</div></div><div className={ui.metric}><div className={ui.metricValue}>{data?.totals?.cameras??0}</div><div className={ui.metricLabel}>Cameras</div></div><div className={ui.metric}><div className={ui.metricValue} style={{color:agents.length&&online===0?"var(--color-status-bad-dark)":online<agents.length?"var(--color-status-warn-dark)":agents.length?"var(--color-status-ok-dark)":undefined}}>{online}/{agents.length}</div><div className={ui.metricLabel}>Site agents online</div></div><div className={ui.metric}><div className={ui.metricValue}>{data?.totals?.sites??0}</div><div className={ui.metricLabel}>{(data?.totals?.sites??0)===1?"Site":"Sites"}</div></div></section>

      <div className={ui.sectionHead}><div><h2>Sites and agents</h2><p>The site is the operating unit; its Windows Site Agent and recorder sit underneath it.</p></div></div>
      <div className="panel"><div className={ui.tableWrap}>{agents.length===0?<div className="empty">No Site Agent has connected yet. <a href="/settings/">Open Sites &amp; Setup</a> to connect one.</div>:<table><thead><tr><th>Site / agent</th><th>Status</th><th>Last seen</th><th>Events</th><th className="hide-sm">Recorder</th></tr></thead><tbody>{Object.entries(bySite).map(([site,list])=>{const anyOnline=list.some((a)=>liveness(a.last_seen_at)[0]==="s-ok"),siteEvents=list.reduce((s,a)=>s+(a.event_count||0),0);return <Fragment key={site}><tr style={{background:"rgba(255,255,255,.025)"}}><td><b>{site}</b></td><td><span className={"pill "+(anyOnline?"s-ok":"s-bad")}>{anyOnline?"online":"offline"}</span></td><td></td><td className="mono">{siteEvents}</td><td className="muted hide-sm">{list.length} agent{list.length>1?"s":""}</td></tr>{list.map((a)=>{const[cls,label]=liveness(a.last_seen_at),device=[a.device_vendor,a.device_model].filter(Boolean).join(" ");return <tr key={a.agent_id}><td className="muted" style={{paddingLeft:"var(--space-6)"}}>{a.hostname||"unknown PC"}</td><td><span className={"pill "+cls}>{label}</span></td><td className="mono" title={exact(a.last_seen_at)}>{ago(a.last_seen_at)}</td><td className="mono">{a.event_count}</td><td className="muted hide-sm">{device||"not set"}</td></tr>;})}</Fragment>;})}</tbody></table>}</div></div>

      <div className={ui.sectionHead}><div><h2>Recent incidents</h2><p>Validated events with stills, ready for a quick review.</p></div><a className={ui.secondaryLink} href="/incidents/">View incident history</a></div>
      {withShots.length===0?<div className={ui.emptyCard}>No incident stills in this window yet.</div>:<div className="shots">{withShots.map((e)=>{const shot=shots.current.get(e.event_id);return <a className="shot" key={e.event_id} href="/incidents/" style={{color:"inherit",textDecoration:"none"}}>{shot===undefined||shot===null?<div style={{display:"grid",placeItems:"center",aspectRatio:"16/9",background:"var(--color-canvas)"}} className="muted">loading still...</div>:shot===false?<div style={{display:"grid",placeItems:"center",aspectRatio:"16/9",background:"var(--color-canvas)"}} className="muted">still unavailable</div>:<img src={shot} alt={`still from ${e.camera||"camera"}`}/>}<div className="meta"><b>{e.camera||"unassigned"}</b> · {humanType(e.event_type)}<div className="muted" title={exact(e.device_ts)}>{ago(e.device_ts)} · {e.site}</div></div></a>;})}</div>}

      <section className={ui.twoCol} style={{marginTop:34}}><div><div className={ui.sectionHead} style={{marginTop:0}}><div><h2>Event mix</h2><p>What the recorder and WatchLog recorded in this window.</p></div></div><div className="panel">{(data?.by_type||[]).length===0?<div className="empty">Nothing yet.</div>:<table><tbody>{data.by_type.map((t)=><tr key={t.event_type}><td style={{width:"38%"}}>{humanType(t.event_type)}</td><td className="mono" style={{width:70}}>{t.count}</td><td><span style={{display:"block",height:8,borderRadius:4,background:"var(--wl-ice)",opacity:.85,width:`${Math.round((t.count/maxType)*100)}%`}}/></td></tr>)}</tbody></table>}</div></div>
      <div><div className={ui.sectionHead} style={{marginTop:0}}><div><h2>Latest activity</h2><p>Relative time first; hover for the exact local timestamp.</p></div></div><div className="panel"><div className={ui.tableWrap}>{(data?.recent||[]).length===0?<div className="empty">Nothing yet.</div>:<table><thead><tr><th>Time</th><th>Camera</th><th>Type</th></tr></thead><tbody>{data.recent.slice(0,12).map((e)=><tr key={e.event_id}><td className="mono" title={exact(e.device_ts)}>{ago(e.device_ts)}</td><td>{e.camera||"unassigned"}<div className="muted" style={{fontSize:"var(--font-size-xs)"}}>{e.site}</div></td><td>{humanType(e.event_type)}</td></tr>)}</tbody></table>}</div></div></div></section>
    </main></div>;
}
