import {withSite} from "../site-context";
function mins(v){return Math.max(0,Math.round(Number(v||0)/60))}
export default function CustomerCard({card,siteId,styles}){const d=card?.data||{};if(card?.type==="coverage"){const r=d.classes||d;const live=Number(r.live_seconds||r.live||0),rec=Number(r.recovered_seconds||r.recovered||0),unv=Number(r.unverified_seconds||r.unverified||0),total=live+rec+unv||1;return <div className={styles.richCard}><div className={styles.richTitle}>{card.title||"Monitoring coverage"}</div><div className={styles.coverageBar}><span className={styles.covLive} style={{width:`${live/total*100}%`}}/><span className={styles.covRecovered} style={{width:`${rec/total*100}%`}}/><span className={styles.covUnverified} style={{width:`${unv/total*100}%`}}/></div><div className={styles.legend}><span><b>Live</b> {mins(live)}m</span><span><b>Recovered</b> {mins(rec)}m</span><span><b>Unverified</b> {mins(unv)}m</span></div><a className={styles.cardAction} href={withSite("/site-health/",siteId)}>Open Site Health →</a></div>}
if(card?.type==="cameras"||card?.type==="health"){const cams=d.cameras||[];return <div className={styles.richCard}><div className={styles.richTitle}>{card.title||"Camera status"}</div>{cams.slice(0,6).map((c,i)=><div className={styles.setupStep} key={c.id||i}><span className={c.health_state==="offline"?styles.stepOpen:styles.stepDone}>{c.health_state==="offline"?"!":"✓"}</span><span>{c.name||`Camera ${c.channel}`} · {c.health_state==="offline"?"Needs attention":"Reporting"}</span></div>)}<a className={styles.cardAction} href={withSite("/control-room/",siteId)}>Open Cameras →</a></div>}
if(card?.type==="incident"){const xs=Array.isArray(d.incidents)?d.incidents:(d.incident?[d.incident]:[]);return <div className={styles.richCard}><div className={styles.richTitle}>{card.title||"Security attention"}</div>{xs.slice(0,5).map((x,i)=><div className={styles.setupStep} key={x.id||i}><span className={styles.stepOpen}>•</span><span>{String(x.incident_type||x.type||"Activity").replaceAll("_"," ")}{x.camera?` · ${x.camera}`:""}</span></div>)}<a className={styles.cardAction} href={withSite("/incidents/",siteId)}>Open Incidents →</a></div>}
if(card?.type==="report")return <div className={styles.richCard}><div className={styles.richTitle}>{card.title||"Management report"}</div><div className={styles.muted}>WatchLog prepared this from the selected site's monitoring, activity and security data.</div><a className={styles.cardAction} href={withSite("/reports/",siteId)}>Open Reports →</a></div>;
if(card?.type==="setup")return <div className={styles.richCard}><div className={styles.richTitle}>{card.title||"Setup"}</div><div className={styles.muted}>Continue the guided setup for this site.</div><a className={styles.cardAction} href={withSite("/setup/",siteId)}>Continue Setup →</a></div>;
if(card?.type==="recorder"||card?.type==="capabilities"){const x=d.recorder||d;return <div className={styles.richCard}><div className={styles.richTitle}>{card.title||"Camera system"}</div><div className={styles.keyGrid}><div><span>System</span><b>{[x.vendor,x.model].filter(Boolean).join(" ")||"Not identified"}</b></div><div><span>WatchLog support</span><b>{d.capability_known===false?"Not yet confirmed":"Checked"}</b></div></div></div>}
if(card?.type==="approval")return <div className={styles.richCard}><div className={styles.richTitle}>{card.title||"Approval needed"}</div><div className={styles.muted}>WatchLog will wait for your approval before changing camera-system settings.</div></div>;return null}
