"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { supabase, say } from "../../lib/supabase";
import { Nav } from "../shell";
import { rememberSite, selectedSiteId, withSite } from "../site-context";
import Mark from "../mark";
import styles from "./ai.module.css";

const SAFE_ROUTES=new Set(["/ai/","/setup/","/reports/","/incidents/","/site-health/","/control-room/","/analytics/","/analytics/studio/","/analytics/schedules/","/site-control/","/settings/"]);
const ACTION_ROUTES={navigate:"/ai/",setup_context:"/setup/",setup_camera:"/setup/",watchlog_rule:"/analytics/studio/",site_control_proposal:"/site-control/"};

function human(v){if(v===null||v===undefined||v==="")return"Not available";return String(v).replaceAll("_"," ").replace(/\b\w/g,(c)=>c.toUpperCase());}
function ago(ts){if(!ts)return"never";const sec=Math.max(0,Math.floor((Date.now()-Date.parse(ts))/1000));if(sec<60)return`${sec}s ago`;if(sec<3600)return`${Math.floor(sec/60)}m ago`;if(sec<86400)return`${Math.floor(sec/3600)}h ago`;return`${Math.floor(sec/86400)}d ago`;}
function StatusDot({state}){const cls=state==="online"||state==="ok"||state==="healthy"?styles.good:state==="offline"||state==="failed"?styles.bad:styles.warn;return <span className={`${styles.dot} ${cls}`}/>;}
function coverageParts(cov){if(!cov||typeof cov!=="object")return[];const root=cov.classes||cov;const get=(key)=>Number(root?.[key]??cov?.seconds?.[key]??cov?.durations?.[key]??0);return[["Live",get("live_seconds")||get("live")],["Recovered",get("recovered_seconds")||get("recovered")],["Unverified",get("unverified_seconds")||get("unverified")]];}

function starterPrompts(ctx,name){
  if(!ctx)return["Set up my first site","How does WatchLog connect to my cameras?","What do I need to install?","What can WatchLog monitor?"];
  const connected=Boolean(ctx?.connectivity?.agent_online||ctx?.connectivity?.last_seen);
  const recorder=Boolean(ctx?.recorder?.identified||ctx?.recorder?.model||ctx?.recorder?.vendor);
  const cameras=ctx?.cameras||[];
  if(!connected)return[`Continue setting up ${name||"this site"}`,"What do I need to install?","Create a setup plan for this site","How does WatchLog connect securely?"];
  if(!recorder)return["Help me connect my recorder","Check the WatchLog Agent","What recorder information do you need?","Continue site setup"];
  if(!cameras.length)return["Check my recorder connection","Find my cameras","What can this recorder support?","Continue site setup"];
  return["What happened overnight?","Check my cameras","Was yesterday fully monitored?","Show today's incidents"];
}

function siteState(ctx){
  if(!ctx)return{label:"Setup required",state:"unknown"};
  const last=ctx?.connectivity?.last_seen;
  const online=Boolean(ctx?.connectivity?.agent_online);
  const cameras=ctx?.cameras||[];
  const monitored=cameras.filter((c)=>c.monitor).length;
  const faults=ctx?.faults||[];
  if(!last&&!online)return{label:"Setup required",state:"unknown"};
  if(!online)return{label:"Offline",state:"offline"};
  if(!monitored)return{label:"Connected · setup incomplete",state:"unknown"};
  if(faults.length)return{label:"Needs attention",state:"unknown"};
  return{label:"Monitoring",state:"online"};
}

function actionHref(action,siteId){const kind=String(action?.kind||"");const requested=String(action?.data?.href||"");const route=requested&&SAFE_ROUTES.has(requested)?requested:(ACTION_ROUTES[kind]||"/ai/");return withSite(route,siteId);}
function ActionButtons({actions=[],siteId}){const safe=(Array.isArray(actions)?actions:[]).filter((a)=>ACTION_ROUTES[a?.kind]).slice(0,4);if(!safe.length)return null;return <div className={styles.suggestionRow}>{safe.map((a,i)=><a key={`${a.kind}-${i}`} className={styles.cardAction} href={actionHref(a,siteId)}>{a.label||"Continue"} →</a>)}</div>;}

function RichCard({card,siteId}){const data=card?.data||{};
  if(card?.type==="coverage"){const parts=coverageParts(data),total=parts.reduce((s,[,n])=>s+n,0)||1;return <div className={styles.richCard}><div className={styles.richTitle}>{card.title||"Monitoring coverage"}</div><div className={styles.coverageBar}>{parts.map(([label,n])=><span key={label} className={styles[`cov${label}`]} style={{width:`${Math.max(0,n/total*100)}%`}}/>)}</div><div className={styles.legend}>{parts.map(([label,n])=><span key={label}><b>{label}</b> {Math.round(n/60)}m</span>)}</div><a className={styles.cardAction} href={withSite("/site-health/",siteId)}>Open site health →</a></div>;}
  if(card?.type==="cameras"||card?.type==="health"){const cameras=data.cameras||[];return <div className={styles.richCard}><div className={styles.richTitle}>{card.title||"Camera health"}</div>{cameras.length?<div className={styles.cameraMiniGrid}>{cameras.slice(0,8).map((c)=><div className={styles.cameraMini} key={c.id||c.channel}><StatusDot state={c.health_state}/><div><b>{c.name||`Camera ${c.channel}`}</b><span>{c.monitor===false?"Ignored":human(c.recording_state||c.health_state)}</span></div></div>)}</div>:<div className={styles.muted}>Camera health will appear after WatchLog connects to the recorder.</div>}<a className={styles.cardAction} href={withSite("/site-health/",siteId)}>Open site health →</a></div>;}
  if(card?.type==="incident"){const incidents=Array.isArray(data.incidents)?data.incidents:(data.incident?[data.incident]:[]);return <div className={styles.richCard}><div className={styles.richTitle}>{card.title||"Incidents"}</div>{incidents.length?<div className={styles.setupSteps}>{incidents.slice(0,6).map((x,i)=><div className={styles.setupStep} key={x.id||i}><StatusDot state={x.severity==="critical"?"offline":"unknown"}/><span><b>{human(x.incident_type||x.type||"Activity")}</b>{x.camera?` · ${x.camera}`:""}</span></div>)}</div>:<div className={styles.muted}>No incident is recorded in this result.</div>}<a className={styles.cardAction} href={withSite("/incidents/",siteId)}>Open incidents →</a></div>;}
  if(card?.type==="report"){const payload=data.payload||{},parts=coverageParts(payload.coverage||{});return <div className={styles.richCard}><div className={styles.richTitle}>{card.title||"WatchLog report"}</div><div className={styles.keyGrid}><div><span>Report date</span><b>{data.report_date||payload?.meta?.date||"Not available"}</b></div><div><span>Status</span><b>{human(data.delivery_status||"saved")}</b></div></div>{parts.some(([,n])=>n>0)&&<div className={styles.legend}>{parts.map(([label,n])=><span key={label}><b>{label}</b> {Math.round(n/60)}m</span>)}</div>}<a className={styles.cardAction} href={withSite("/reports/",siteId)}>Open reports →</a></div>;}
  if(card?.type==="setup"){const steps=data.steps||[];return <div className={styles.richCard}><div className={styles.richTitle}>{card.title||"Setup"}</div><div className={styles.setupSteps}>{steps.map((s)=><div className={styles.setupStep} key={s.key}><span className={s.done?styles.stepDone:styles.stepOpen}>{s.done?"✓":"○"}</span><span>{s.label}</span></div>)}</div><a className={styles.cardAction} href={withSite("/setup/",siteId)}>Continue guided setup →</a></div>;}
  if(card?.type==="recorder"||card?.type==="capabilities"){const recorder=data.recorder||data;return <div className={styles.richCard}><div className={styles.richTitle}>{card.title||"Recorder"}</div><div className={styles.keyGrid}><div><span>Device</span><b>{[recorder.vendor,recorder.model].filter(Boolean).join(" ")||"Not identified"}</b></div><div><span>Capability profile</span><b>{data.capability_known===false?"Unconfirmed":"Evidence graded"}</b></div></div></div>;}
  if(card?.type==="approval")return <div className={styles.richCard}><div className={styles.richTitle}>{card.title||"Approval required"}</div><div className={styles.muted}>WatchLog will not change recorder settings until an authorized user approves the proposal.</div><a className={styles.cardAction} href={withSite("/site-control/",siteId)}>Review proposal →</a></div>;
  return null;
}

export default function AIWorkspace(){
  const[email,setEmail]=useState("");const[sites,setSites]=useState([]);const[siteId,setSiteId]=useState("");const[context,setContext]=useState(null);const[conversationId,setConversationId]=useState("");const[messages,setMessages]=useState([]);const[draft,setDraft]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[rightOpen,setRightOpen]=useState(false);const endRef=useRef(null);const inputRef=useRef(null);

  const loadBase=useCallback(async()=>{const sb=supabase();const{data:{session}}=await sb.auth.getSession();if(!session){location.replace("/login/");return;}setEmail(session.user.email||"");const{data,error}=await sb.rpc("wl_sites");if(error){setError(say(error));return;}const next=data||[];setSites(next);const params=new URLSearchParams(window.location.search);const preferred=params.get("site")||selectedSiteId()||next[0]?.id||"";const conv=params.get("conversation")||"";if(preferred){setSiteId(preferred);rememberSite(preferred,next.find((s)=>s.id===preferred)?.name||"");}if(conv)setConversationId(conv);},[]);
  const loadContext=useCallback(async(id)=>{if(!id){setContext(null);return;}const{data,error}=await supabase().rpc("wl_ai_context",{p_site_id:id});if(error){setError(say(error));return;}setContext(data||null);},[]);
  const loadMessages=useCallback(async(id)=>{if(!id){setMessages([]);return;}const{data,error}=await supabase().rpc("wl_ai_messages",{p_conversation_id:id,p_limit:100});if(error){setError(say(error));return;}setMessages((data||[]).map((m)=>({role:m.role,content:m.content,payload:m.payload||{},id:m.id})));},[]);
  useEffect(()=>{loadBase();},[loadBase]);useEffect(()=>{if(siteId)loadContext(siteId);},[siteId,loadContext]);useEffect(()=>{loadMessages(conversationId);},[conversationId,loadMessages]);useEffect(()=>{endRef.current?.scrollIntoView({behavior:"smooth"});},[messages,busy]);useEffect(()=>{const el=inputRef.current;if(!el)return;el.style.height="0px";const next=Math.min(el.scrollHeight,140);el.style.height=`${Math.max(38,next)}px`;el.style.overflowY=el.scrollHeight>140?"auto":"hidden";},[draft]);

  const selectedSite=sites.find((s)=>s.id===siteId);const monitored=(context?.cameras||[]).filter((c)=>c.monitor).length;const healthy=(context?.cameras||[]).filter((c)=>c.monitor&&c.health_state!=="offline").length;const recorder=[context?.recorder?.vendor,context?.recorder?.model].filter(Boolean).join(" ");const state=siteState(context);const starters=starterPrompts(context,selectedSite?.name);
  const suggestions=useMemo(()=>{const last=[...messages].reverse().find((m)=>m.role==="assistant");return last?.payload?.suggestions?.length?last.payload.suggestions:starters;},[messages,starters]);

  function changeSite(id){setSiteId(id);setConversationId("");setMessages([]);setError("");const name=sites.find((s)=>s.id===id)?.name||"";rememberSite(id,name);history.replaceState(null,"",`/ai/?site=${encodeURIComponent(id)}`);}
  async function send(text=draft){const prompt=String(text||"").trim();if(!prompt||busy||!siteId)return;setDraft("");setError("");setBusy(true);setMessages((m)=>[...m,{role:"user",content:prompt,payload:{}}]);const{data,error}=await supabase().functions.invoke("watchlog-ai",{body:{prompt,site_id:siteId,conversation_id:conversationId||null}});setBusy(false);if(error||data?.error){setError(data?.message||say(error)||"WatchLog AI could not complete that request.");return;}const nextId=data?.conversation_id||conversationId;if(nextId&&!conversationId){setConversationId(nextId);history.replaceState(null,"",`/ai/?site=${encodeURIComponent(siteId)}&conversation=${encodeURIComponent(nextId)}`);}setMessages((m)=>[...m,{role:"assistant",content:data.answer,payload:{cards:data.cards||[],suggestions:data.suggestions||[],proposed_actions:data.proposed_actions||[],mode:data.mode}}]);await loadContext(siteId);}

  return <div className="shell"><Nav active="WatchLog AI" email={email} currentSiteId={siteId}/><main className={styles.main}><header className={styles.topbar}><div><b>WatchLog AI</b><span>{selectedSite?.name||"Select a site"}</span></div><div className={styles.topActions}><select className={styles.siteSelect} value={siteId} onChange={(e)=>changeSite(e.target.value)} aria-label="Select site">{sites.map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</select><span className={styles.statusChip}><StatusDot state={state.state}/>{state.label}</span><button className={styles.mobileBtn} onClick={()=>setRightOpen(true)} aria-label="Open site context">◫</button></div></header>
    <section className={styles.chat}>{messages.length===0?<div className={styles.welcome}><div className={styles.aiMark}><Mark size={42}/></div><h1>How can I help with {selectedSite?.name||"your site"}?</h1><p>{state.label==="Setup required"?"I'll guide you through connecting WatchLog, identifying the recorder and setting up your cameras.":"Ask what happened, check your cameras, understand your recorder, or configure monitoring in plain language."}</p><div className={styles.starters}>{starters.map((x)=><button key={x} onClick={()=>send(x)} disabled={!siteId}>{x}<span>↗</span></button>)}</div>{state.label==="Setup required"&&siteId&&<a className={styles.setupCta} href={withSite("/setup/",siteId)}>Continue guided setup</a>}</div>:<div className={styles.thread}>{messages.map((m,i)=><div key={m.id||i} className={`${styles.message} ${m.role==="user"?styles.user:styles.assistant}`}><div className={styles.avatar}>{m.role==="user"?"You":<Mark size={24}/>}</div><div className={styles.messageBody}><div className={styles.messageText}>{m.content}</div>{(m.payload?.cards||[]).map((c,j)=><RichCard key={j} card={c} siteId={siteId}/>) }<ActionButtons actions={m.payload?.proposed_actions||[]} siteId={siteId}/>{m.role==="assistant"&&m.payload?.mode==="guided_fallback"&&<div className={styles.muted}>Verified-data mode · WatchLog deterministic guidance</div>}</div></div>)}{busy&&<div className={`${styles.message} ${styles.assistant}`}><div className={styles.avatar}><Mark size={24}/></div><div className={styles.thinking}><i/><i/><i/></div></div>}<div ref={endRef}/></div>}</section>
    {error&&<div className={styles.error}>{error}</div>}<footer className={styles.composerWrap}>{messages.length>0&&<div className={styles.suggestionRow}>{suggestions.slice(0,4).map((s)=><button key={s} onClick={()=>send(s)} disabled={busy}>{s}</button>)}</div>}<form className={styles.composer} onSubmit={(e)=>{e.preventDefault();send();}}><textarea ref={inputRef} style={{flex:"1 1 auto",width:"100%",minWidth:0,overflowY:"hidden"}} value={draft} onChange={(e)=>setDraft(e.target.value)} onKeyDown={(e)=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send();}}} placeholder={siteId?`Ask WatchLog about ${selectedSite?.name||"this site"}...`:"Select a site to start"} disabled={!siteId||busy} rows={1}/><button disabled={!draft.trim()||busy||!siteId} aria-label="Send">↑</button></form><small>WatchLog uses verified site and recorder data. Device changes require approval.</small></footer></main>

    <aside className={`${styles.context} ${rightOpen?styles.open:""}`}><div className={styles.contextHead}><div><span>Site context</span><b>{selectedSite?.name||"No site"}</b></div><button className={styles.iconBtn} onClick={()=>setRightOpen(false)} aria-label="Close site context">×</button></div>{!siteId?<div className={styles.emptyContext}>Add or select a site to give WatchLog operational context.</div>:<><div className={styles.contextCard}><div className={styles.contextTitle}>Monitoring</div><div className={styles.contextRow}><span>WatchLog</span><b><StatusDot state={state.state}/>{state.label}</b></div><div className={styles.contextRow}><span>Last contact</span><b>{ago(context?.connectivity?.last_seen)}</b></div></div><div className={styles.contextCard}><div className={styles.contextTitle}>Camera system</div><div className={styles.contextRow}><span>Recorder</span><b>{recorder||"Not identified"}</b></div><div className={styles.contextRow}><span>Cameras</span><b>{monitored?`${healthy}/${monitored} healthy`:"Not configured"}</b></div><div className={styles.contextRow}><span>Capability profile</span><b>{context?.capability_known?"Loaded":"Unconfirmed"}</b></div></div><div className={styles.contextCard}><div className={styles.contextTitle}>Attention</div>{!context?.connectivity?.last_seen&&!context?.connectivity?.agent_online?<div className={styles.muted}>Camera health isn't available yet. Connect the WatchLog Agent to begin monitoring.</div>:(context?.faults||[]).length?(context.faults||[]).slice(0,4).map((f,i)=><div className={styles.alertRow} key={i}><StatusDot state="offline"/><div><b>{f.camera||"Camera"}</b><span>{human(f.reason)}</span></div></div>):<div className={styles.muted}>No current monitoring issue is reported.</div>}</div><div className={styles.contextCard}><div className={styles.contextTitle}>Setup</div>{(context?.onboarding?.steps||[]).map((s)=><div className={styles.contextStep} key={s.key}><span className={s.done?styles.doneCheck:""}>{s.done?"✓":"○"}</span>{s.label}</div>)}<a className={styles.contextLink} href={withSite("/setup/",siteId)}>Open guided setup →</a></div><div className={styles.contextLinks}><a href={withSite("/site-health/",siteId)}>Site health</a><a href={withSite("/incidents/",siteId)}>Incidents</a><a href={withSite("/control-room/",siteId)}>Camera view</a><a href={withSite("/site-control/",siteId)}>Site Control</a></div></>}<div className={styles.userBox}><span>{email}</span></div></aside>{rightOpen&&<button className={styles.scrim} onClick={()=>setRightOpen(false)} aria-label="Close site context"/>}</div>;
}
