"use client";

import { useCallback, useEffect, useState } from "react";
import { supabase, say } from "../../lib/supabase";
import { Nav, requireTenant, setupPill } from "../shell";
import ui from "../portal.module.css";

const INSTALLER_URL=process.env.NEXT_PUBLIC_INSTALLER_URL||"";
const BILLING_URL=process.env.NEXT_PUBLIC_BILLING_URL||"";
const BILLING_PROVIDER=process.env.NEXT_PUBLIC_BILLING_PROVIDER||"";
const MARKETING_URL=process.env.NEXT_PUBLIC_MARKETING_URL||"";
function fmt(ts){return ts?new Date(ts).toLocaleString():"-";}
function money(minor,cur){return minor==null?"-":`${cur||"PKR"} ${(minor/100).toLocaleString()}`;}

export default function Settings(){
  const[email,setEmail]=useState(""),[trial,setTrial]=useState(null),[sites,setSites]=useState(null),[billing,setBilling]=useState(null),[plans,setPlans]=useState([]),[entitlement,setEntitlement]=useState(null),[documents,setDocuments]=useState(null),[role,setRole]=useState("viewer"),[tab,setTab]=useState("account"),[err,setErr]=useState(""),[note,setNote]=useState(""),[newSite,setNewSite]=useState(""),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const g=await requireTenant();if(!g)return;setEmail(g.session.user.email||"");const sb=supabase();const[t,s,p,e,r]=await Promise.all([sb.rpc("wl_trial_status"),sb.rpc("wl_sites"),sb.rpc("wl_billing_plans"),sb.rpc("wl_entitlement"),sb.rpc("wl_my_role")]);const failure=t.error||s.error||p.error||e.error||r.error;if(failure){setErr(say(failure));return;}const nextRole=r.data||"viewer";let billingData={},documentData=null;if(nextRole==="owner"){const b=await sb.rpc("wl_billing_overview");if(b.error){setErr(say(b.error));return;}billingData=b.data||{};const d=await sb.rpc("wl_customer_documents");if(!d.error)documentData=d.data||{};}setErr("");setTrial(t.data||{});setSites(s.data||[]);setBilling(billingData);setPlans(p.data||[]);setEntitlement(e.data||{});setDocuments(documentData);setRole(nextRole);},[]);
  useEffect(()=>{load();},[load]);
  const canBill=role==="owner",canOperate=role==="owner"||role==="admin",billingConfigured=Boolean(BILLING_PROVIDER&&BILLING_URL),t=trial||{};
  const statusCls=t.status==="active"?"s-ok":t.status==="trialing"?"s-warn":t.status==="past_due"?"s-bad":"s-unk";
  async function startCheckout(plan){setErr("");setNote("");if(!billingConfigured){setErr("Online plan changes are not available for this account yet. Contact WatchLog Support and we will help with the change.");return;}const{data,error}=await supabase().rpc("wl_billing_start_checkout",{p_plan:plan,p_provider:BILLING_PROVIDER});if(error){setErr(say(error));return;}if(data?.checkout_path){window.location.href=BILLING_URL+data.checkout_path;return;}setErr("We could not start the plan change. Your current access has not been changed. Please contact WatchLog Support.");}
  async function cancelSub(){if(!confirm("Cancel this subscription at the end of the current billing period?"))return;setErr("");setNote("");const{data,error}=await supabase().rpc("wl_billing_cancel");if(error){setErr(say(error));return;}setNote(data?.note||"Cancellation requested.");load();}
  async function addSite(e){e.preventDefault();setBusy(true);setErr("");setNote("");const{error}=await supabase().rpc("wl_add_site",{p_name:newSite.trim()});setBusy(false);if(error){setErr(say(error));return;}setNote("Site added. Create a setup code when you are ready to connect its cameras.");setNewSite("");load();}
  async function issueCode(siteId){setErr("");setNote("");const{data,error}=await supabase().rpc("wl_issue_code",{p_site_id:siteId,p_days:14});if(error){setErr(say(error));return;}setNote(`Setup code ${data.code} created. It can be used once and is valid for 14 days.`);load();}
  async function copyCode(code){if(!code)return;try{await navigator.clipboard.writeText(code);setErr("");setNote("Setup code copied.");}catch{setErr("Could not copy the setup code automatically. Select the code and copy it manually.");}}

  return <div className="shell"><Nav active="Settings" email={email}/><main className="main">
    <header className={ui.pageHead}><div><div className={ui.eyebrow}>Account & sites</div><h1>Manage your WatchLog account.</h1><p>Review your plan, billing history, customer documents and connected sites from one place.</p></div></header>
    {err&&<div className="err">{err}</div>}{note&&<div className="ok-note">{note}</div>}
    <div className={ui.tabs} role="tablist" aria-label="Settings sections"><button className={`${ui.tab} ${tab==="account"?ui.tabActive:""}`} onClick={()=>setTab("account")}>Account &amp; Plan</button><button className={`${ui.tab} ${tab==="sites"?ui.tabActive:""}`} onClick={()=>setTab("sites")}>Sites &amp; Setup</button></div>

    {tab==="account"?<>
      <section className={ui.metricGrid}><div className={ui.metric}><div className={ui.metricValue} style={{textTransform:"capitalize"}}>{t.plan||"trial"}</div><div className={ui.metricLabel}>Current plan</div></div><div className={ui.metric}><div className={ui.metricValue}><span className={"pill "+statusCls}>{t.status||"-"}</span></div><div className={ui.metricLabel}>Account status</div></div><div className={ui.metric}><div className={ui.metricValue}>{t.status==="trialing"?(t.days_left??0):"-"}</div><div className={ui.metricLabel}>{t.status==="trialing"?"Trial days left":"Trial"}</div></div><div className={ui.metric}><div className={ui.metricValue}><span className={"pill "+(entitlement?.reporting_enabled?"s-ok":"s-bad")}>{entitlement?.reporting_enabled?"active":"paused"}</span></div><div className={ui.metricLabel}>Daily reporting</div></div></section>
      {!canBill&&<div className={ui.callout} style={{marginTop:20}}><span className={ui.statusDot}/><div><strong>Plan changes are owner-managed</strong><p>Your {role} role can see the current plan and account status. The account Owner manages billing and subscription changes.</p></div></div>}
      {canBill&&!billingConfigured&&<div className={ui.callout} style={{marginTop:20}}><span className={ui.statusDot}/><div><strong>Need to change your plan?</strong><p>Online plan changes are not enabled for this account yet. Contact WatchLog Support and we will handle the change with you.</p></div></div>}
      <div className={ui.sectionHead}><div><h2>Plan and billing</h2><p>Choose the WatchLog package that fits your sites and reporting needs.</p></div></div>
      <section className={ui.twoCol}><div className={ui.featureCard}><h3>{t.status==="active"?"Plan options":"Choose a plan"}</h3><p>Your current package remains unchanged until a plan change is confirmed.</p><div className={ui.threeCol}>{plans.map((p)=><div className={ui.roleCard} key={p.plan}><strong style={{textTransform:"capitalize"}}>{p.plan}</strong><p>{money(p.amount_minor,p.currency)} / month</p>{canBill&&billingConfigured&&<button className="small" style={{width:"auto",marginTop:14}} onClick={()=>startCheckout(p.plan)}>Choose {p.plan}</button>}</div>)}</div>{MARKETING_URL&&<p style={{marginBottom:0}}>Need a larger or custom rollout? <a href={MARKETING_URL+"/contact/"}>Talk to WatchLog</a>.</p>}</div>
      <div className={ui.card}><h3>Account state</h3><div className={ui.splitList}><div className={ui.listRow}><span className={ui.statusDot}/><div><b style={{textTransform:"capitalize"}}>{t.status||"unknown"}</b><small>{t.status==="trialing"?`Trial ends ${t.trial_ends_at?new Date(t.trial_ends_at).toLocaleDateString():"soon"}`:"Current account state"}</small></div></div>{canBill&&billing?.subscription?.current_period_end&&<div className={ui.listRow}><span className={ui.statusDot}/><div><b>{new Date(billing.subscription.current_period_end).toLocaleDateString()}</b><small>{billing.subscription.cancel_at_period_end?"Access ends at this period boundary":"Current period renews"}</small></div></div>}<div className={ui.listRow}><span className={ui.statusDot}/><div><b>Your history stays available</b><small>If service pauses, your existing incident and report history remains in your account.</small></div></div></div>{canBill&&t.status==="active"&&<button className="btn-danger" style={{marginTop:16}} onClick={cancelSub}>Cancel at period end</button>}</div></section>
      {canBill&&<><div className={ui.sectionHead}><div><h2>Payment history</h2><p>Payments recorded for this WatchLog account.</p></div></div><div className="panel"><div className={ui.tableWrap}>{(billing?.transactions||[]).length?<table><thead><tr><th>Date</th><th>Plan</th><th>Amount</th><th>Status</th></tr></thead><tbody>{billing.transactions.map((x,i)=><tr key={i}><td className="mono">{new Date(x.created_at).toLocaleDateString()}</td><td style={{textTransform:"capitalize"}}>{x.plan||"-"}</td><td className="mono">{money(x.amount_minor,x.currency)}</td><td><span className={"pill "+(x.status==="succeeded"?"s-ok":x.status==="failed"?"s-bad":"s-unk")}>{x.status}</span></td></tr>)}</tbody></table>:<div className="empty">No payment history yet.</div>}</div></div></>}
      {canBill&&documents&&<><div className={ui.sectionHead}><div><h2>Invoices &amp; agreements</h2><p>Commercial documents shared with your WatchLog account.</p></div></div><section className={ui.twoCol}><div className={ui.card}><h3>Invoices</h3><div className={ui.splitList}>{(documents.invoices||[]).map(i=><div className={ui.listRow} key={i.id}><span className={ui.statusDot}/><div><b>{i.invoice_number}</b><small>{new Date(`${i.issue_date}T00:00:00`).toLocaleDateString()} · due {new Date(`${i.due_date}T00:00:00`).toLocaleDateString()} · {money(i.total_minor,i.currency)}</small></div><span className={"pill "+(i.status==="paid"?"s-ok":i.status==="overdue"?"s-bad":"s-unk")}>{i.status}</span></div>)}{!(documents.invoices||[]).length&&<div className="empty">No invoices have been added to your account yet.</div>}</div></div><div className={ui.card}><h3>Agreements</h3><div className={ui.splitList}>{(documents.contracts||[]).map(c=><div className={ui.listRow} key={c.id}><span className={ui.statusDot}/><div><b>{c.contract_number}</b><small>{c.title}{c.ends_on?` · through ${new Date(`${c.ends_on}T00:00:00`).toLocaleDateString()}`:""}</small></div><span className={"pill "+(c.status==="signed"?"s-ok":"s-unk")}>{c.status}</span></div>)}{!(documents.contracts||[]).length&&<div className="empty">No agreements have been added to your account yet.</div>}</div></div></section></>}
    </>:<>
      <section className={ui.heroGrid}><div className={ui.featureCard}><div className={ui.eyebrow}>Connect a site</div><h3>Bring your existing cameras into WatchLog.</h3><p>Use a Windows computer at the location, enter the setup code, and follow the guided connection steps. WatchLog will connect the camera system and prepare your cameras for monitoring.</p><div className={ui.splitList}><div className={ui.listRow}><span className={ui.statusDot}/><div><b>Your CCTV login stays at your site</b><small>WatchLog does not ask you to expose your recorder to the internet.</small></div></div><div className={ui.listRow}><span className={ui.statusDot}/><div><b>One setup code per site</b><small>The code can be used once and is valid for 14 days.</small></div></div></div>{INSTALLER_URL?<a className={ui.primaryLink} style={{marginTop:18}} href={INSTALLER_URL}>Download WatchLog for Windows</a>:<p className="muted" style={{fontSize:"var(--font-size-sm)",marginBottom:0}}>Windows setup is not available for download in this environment yet. Contact WatchLog Support if you are preparing a site now.</p>}</div><div className={ui.card}><h3>What you need</h3><div className={ui.splitList}><div className={ui.listRow}><span className={ui.statusDot}/><div><b>Your existing CCTV recorder</b><small>A supported NVR/DVR connected to the site network.</small></div></div><div className={ui.listRow}><span className={ui.statusDot}/><div><b>A Windows site computer</b><small>On the same network and normally kept switched on.</small></div></div><div className={ui.listRow}><span className={ui.statusDot}/><div><b>Your CCTV login</b><small>Used during guided setup to confirm the camera system.</small></div></div><div className={ui.listRow}><span className={ui.statusDot}/><div><b>Internet access</b><small>A normal internet connection for WatchLog updates and reports.</small></div></div></div></div></section>
      <div className={ui.sectionHead}><div><h2>Your sites</h2><p>Add locations, create setup codes and see when each site is ready.</p></div></div>
      {canOperate?<div className={ui.card}><form className="row" onSubmit={addSite}><div className="field"><label>Add a site</label><input required placeholder="Warehouse, Head Office, Branch 2" value={newSite} onChange={(e)=>setNewSite(e.target.value)}/></div><button className="small" disabled={busy} style={{width:"auto"}}>{busy?"Adding...":"Add site"}</button></form></div>:<div className={ui.callout}><span className={ui.statusDot}/><div><strong>Read-only site access</strong><p>Owners and Admins manage sites and setup codes. You can still see each site's current status.</p></div></div>}
      <div className="panel"><div className={ui.tableWrap}>{sites===null?<div className="empty">Loading...</div>:sites.length===0?<div className="empty">No sites yet.</div>:<table><thead><tr><th>Site</th><th>Setup</th><th>Cameras</th><th>Last activity</th><th>Setup code</th></tr></thead><tbody>{sites.map((s)=>{const[slabel,scls]=setupPill(s.setup_state,s.online);return <tr key={s.id}><td><b>{s.name}</b><div className="muted" style={{fontSize:"var(--font-size-xs)"}}>{s.timezone}</div></td><td><span className={"pill "+scls}>{slabel}</span></td><td className="mono">{s.cameras}</td><td className="muted">{fmt(s.last_event)}</td><td>{canOperate&&s.open_code?<><span className="mono">{s.open_code}</span><button className="ghost small" type="button" style={{marginLeft:8}} onClick={()=>copyCode(s.open_code)}>Copy</button></>:s.has_open_code?<span className="muted">Code ready</span>:<span className="muted">No active code</span>}{canOperate&&<button className="ghost small" type="button" style={{marginLeft:8}} onClick={()=>issueCode(s.id)}>New code</button>}</td></tr>;})}</tbody></table>}</div></div>
    </>}
  </main></div>;
}
