"use client";

import { useEffect, useState } from "react";
import { supabase, say } from "../../../lib/supabase";
import { AdminNav, requirePlatformAdmin } from "../admin-shell";
import styles from "../admin.module.css";

const fmt=v=>v?new Date(v).toLocaleString():"Never";
const money=(n,c="PKR")=>n==null?"-":`${c} ${(Number(n)/100).toLocaleString()}`;

export default function CommercialAdmin(){
  const [admin,setAdmin]=useState(null),[data,setData]=useState(null),[customers,setCustomers]=useState([]),[error,setError]=useState("");
  useEffect(()=>{(async()=>{const guard=await requirePlatformAdmin();if(!guard)return;setAdmin(guard.admin);const[b,t]=await Promise.all([supabase().rpc("wl_platform_billing"),supabase().rpc("wl_platform_tenants",{p_search:null,p_status:null,p_limit:200,p_offset:0})]);if(b.error||t.error){setError(say(b.error||t.error));return;}setData(b.data);setCustomers(t.data?.items||[]);})();},[]);
  const byPlan=Object.fromEntries((data?.by_plan||[]).map(x=>[x.plan,Number(x.tenants)])),byStatus=Object.fromEntries((data?.by_status||[]).map(x=>[x.status,Number(x.tenants)]));
  const followUp=customers.filter(c=>c.subscription_status==="past_due"||c.subscription_status==="trialing"||c.requested_plan).slice(0,20);
  return <div className="shell"><AdminNav active="Commercial" admin={admin}/><main className="main">
    <div className={styles.head}><div><h1>Commercial</h1><p>Manage plans, trials, billing follow-up and customer commercial records from one operating view.</p></div><div className={styles.actions}><a className={styles.link} href="/admin/tenants/">Open customer directory</a></div></div>
    {error&&<div className="err">{error}</div>}
    {!data?<div className={styles.card}>Loading commercial status...</div>:<>
      <div className={styles.grid4}><div className={styles.metric}><div className={styles.metricLabel}>Starter</div><div className={styles.metricValue}>{byPlan.starter||0}</div><div className={styles.metricHint}>customer accounts</div></div><div className={styles.metric}><div className={styles.metricLabel}>Growth</div><div className={styles.metricValue}>{byPlan.growth||0}</div><div className={styles.metricHint}>customer accounts</div></div><div className={styles.metric}><div className={styles.metricLabel}>Enterprise</div><div className={styles.metricValue}>{byPlan.enterprise||0}</div><div className={styles.metricHint}>customer accounts</div></div><div className={styles.metric}><div className={styles.metricLabel}>Needs follow-up</div><div className={styles.metricValue}>{(byStatus.past_due||0)+(byStatus.trialing||0)}</div><div className={styles.metricHint}>{byStatus.past_due||0} past due · {byStatus.trialing||0} trialing</div></div></div>

      <div className={styles.twoCol}><section className={styles.card}><h2>Commercial action queue</h2><p className="muted">Customers with a trial, payment issue or pending plan request.</p><div className={styles.stack}>{followUp.map(t=><a className={styles.row} style={{textDecoration:"none"}} href={`/admin/tenants/?tenant=${t.id}`} key={t.id}><div><strong>{t.name}</strong><small style={{textTransform:"capitalize"}}>{t.plan} · {t.subscription_status}{t.requested_plan?` · requested ${t.requested_plan}`:""}</small></div><span className={`${styles.badge} ${t.subscription_status==="past_due"?styles.bad:t.subscription_status==="trialing"?styles.warn:styles.muted}`}>Review</span></a>)}{!followUp.length&&<div className={styles.empty}>No customers currently need commercial follow-up.</div>}</div></section><section className={styles.card}><h2>What you can manage</h2><div className={styles.stack}><div className={styles.row}><div><strong>Plan & trial</strong><small>Change package, extend trials and record the reason.</small></div><span className={`${styles.badge} ${styles.ok}`}>Audited</span></div><div className={styles.row}><div><strong>Invoices & payments</strong><small>Generate invoices, print/save PDF and record verified manual payments.</small></div><span className={`${styles.badge} ${styles.ok}`}>Customer 360</span></div><div className={styles.row}><div><strong>Contracts</strong><small>Create service agreements, print/save PDF and track sent/signed status.</small></div><span className={`${styles.badge} ${styles.ok}`}>Customer 360</span></div><div className={styles.row}><div><strong>Billing contacts</strong><small>Maintain legal name, billing email, address, tax ID and payment terms.</small></div><span className={`${styles.badge} ${styles.ok}`}>Customer 360</span></div></div></section></div>

      <section className={styles.card}><h2>Trials expiring within 7 days</h2><div className={styles.stack}>{(data.trials_expiring||[]).map(t=><a className={styles.row} style={{textDecoration:"none"}} href={`/admin/tenants/?tenant=${t.tenant_id}`} key={t.tenant_id}><div><strong>{t.tenant}</strong><small>Ends {fmt(t.ends_at)}</small></div><span className={`${styles.badge} ${styles.warn}`}>Review customer</span></a>)}{!(data.trials_expiring||[]).length&&<div className={styles.empty}>No trials expire in the next 7 days.</div>}</div></section>

      <section className={styles.card}><h2>Recent provider transactions</h2><p className="muted">Payment-provider activity is kept separate from manual payment records entered in Customer 360.</p><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Customer</th><th>Plan</th><th>Amount</th><th>Method</th><th>Status</th><th>Created</th></tr></thead><tbody>{(data.transactions||[]).map((p,i)=><tr key={`${p.tenant_id}-${p.created_at}-${i}`}><td><a className={styles.link} href={`/admin/tenants/?tenant=${p.tenant_id}`}>{p.tenant}</a></td><td>{p.plan||"-"}</td><td>{money(p.amount_minor,p.currency)}</td><td>{p.provider}</td><td><span className={`${styles.badge} ${p.status==="succeeded"?styles.ok:p.status==="failed"?styles.bad:styles.muted}`}>{p.status}</span></td><td>{fmt(p.created_at)}</td></tr>)}{!(data.transactions||[]).length&&<tr><td colSpan="6"><div className={styles.empty}>No provider transactions in the last 90 days.</div></td></tr>}</tbody></table></div></section>
    </>}
  </main></div>;
}
