"use client";

import { useCallback, useEffect, useState } from "react";
import { supabase, say } from "../../lib/supabase";
import { Nav, requireTenant } from "../shell";
import { rememberSite, selectedSiteId } from "../site-context";
import Mark from "../mark";
import ui from "../portal.module.css";

const CHANNELS=[["whatsapp","WhatsApp"],["email","Email"],["both","WhatsApp + Email"]];
const TABS=[["daily","Daily"],["monthly","Monthly"],["executive","Executive"],["delivery","Delivery"]];
function statusPill(s){const cls=s==="sent"?"s-ok":s==="failed"?"s-bad":"s-unk";return <span className={"pill "+cls}>{s}</span>;}
function channelLabel(v){return CHANNELS.find(([k])=>k===v)?.[1]||v;}
function endpoint(r){return r.whatsapp_destination||r.email_destination||r.destination||"-";}
function humanDate(v){if(!v)return"-";try{return new Date(`${v}T00:00:00`).toLocaleDateString();}catch{return v;}}
function human(v){return String(v||"").replaceAll("_"," ").replace(/\b\w/g,(c)=>c.toUpperCase());}

function BriefCard({card}){const data=card?.data||{};if(card?.type==="coverage"){const root=data.classes||data;const live=Number(root.live_seconds||root.live||0),rec=Number(root.recovered_seconds||root.recovered||0),unv=Number(root.unverified_seconds||root.unverified||0),total=live+rec+unv||1;return <div className={ui.card}><h3>{card.title||"Monitoring coverage"}</h3><div className={ui.progress}><span style={{width:`${((live+rec)/total)*100}%`}}/></div><div className={ui.detailGrid} style={{marginTop:12}}><div className={ui.detailItem}><small>Live</small><b>{Math.round(live/60)} min</b></div><div className={ui.detailItem}><small>Recovered</small><b>{Math.round(rec/60)} min</b></div><div className={ui.detailItem}><small>Unverified</small><b>{Math.round(unv/60)} min</b></div><div className={ui.detailItem}><small>Verified coverage</small><b>{Math.round(((live+rec)/total)*100)}%</b></div></div></div>;}if(card?.type==="incident"){const incidents=Array.isArray(data.incidents)?data.incidents:(data.incident?[data.incident]:[]);return <div className={ui.card}><h3>{card.title||"Security attention"}</h3>{incidents.length?<div className={ui.splitList}>{incidents.slice(0,6).map((x,i)=><div className={ui.listRow} key={x.id||i}><span className={"pill "+(x.severity==="critical"?"s-bad":"s-warn")}>{human(x.severity||"review")}</span><div><b>{human(x.incident_type||x.type||"Activity")}</b><small>{[x.site,x.camera,x.time].filter(Boolean).join(" · ")}</small></div></div>)}</div>:<div className={ui.emptyCard}>No incident detail in this report.</div>}</div>;}if(card?.type==="report"){const payload=data.payload||{};return <div className={ui.card}><h3>{card.title||"Report snapshot"}</h3><div className={ui.detailGrid}><div className={ui.detailItem}><small>Report date</small><b>{data.report_date||payload?.meta?.date||"Current period"}</b></div><div className={ui.detailItem}><small>Status</small><b>{human(data.delivery_status||"saved")}</b></div></div></div>;}return null;}

export default function Reports(){
  const[email,setEmail]=useState(""),[recips,setRecips]=useState(null),[sites,setSites]=useState([]),[siteId,setSiteId]=useState(""),[deliveries,setDeliveries]=useState([]),[role,setRole]=useState("viewer"),[tab,setTab]=useState("daily"),[brief,setBrief]=useState(null),[briefBusy,setBriefBusy]=useState(false),[err,setErr]=useState(""),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[form,setForm]=useState({whatsapp:"",email:"",channel:"whatsapp",name:"",site_id:""});
  const load=useCallback(async()=>{const g=await requireTenant();if(!g)return;setEmail(g.session.user.email||"");const sb=supabase();const[r,s,d,me]=await Promise.all([sb.rpc("wl_recipients"),sb.rpc("wl_sites"),sb.rpc("wl_deliveries",{p_days:90}),sb.rpc("wl_my_role")]);if(r.error||s.error||d.error||me.error){setErr(say(r.error||s.error||d.error||me.error));return;}const next=s.data||[];setErr("");setRecips(r.data||[]);setSites(next);setDeliveries(d.data||[]);setRole(me.data||"viewer");if(!siteId&&next.length){const preferred=new URLSearchParams(window.location.search).get("site")||selectedSiteId()||next[0].id;setSiteId(preferred);rememberSite(preferred,next.find((x)=>x.id===preferred)?.name||"");}},[siteId]);
  useEffect(()=>{load();},[load]);
  const canManage=role==="owner"||role==="admin",active=(recips||[]).filter((r)=>r.enabled),selected=sites.find((s)=>s.id===siteId),siteDeliveries=deliveries.filter((d)=>!selected||d.site===selected.name);

  async function loadBrief(kind=tab){if(!siteId||kind==="delivery")return;setBriefBusy(true);setErr("");const prompts={daily:"Give me today's management report. Use the canonical WatchLog report snapshot when available. Lead with monitoring coverage, site activity, security attention, confirmed incidents and priority action.",monthly:"Give me the management trend summary for this site for the last 30 days: coverage, incidents, activity, after-hours patterns and the most important changes.",executive:"Give me an executive summary for this site: monitoring reliability, security attention, operational patterns, confirmed incidents and the single highest-priority action."};const{data,error}=await supabase().functions.invoke("watchlog-ai",{body:{prompt:prompts[kind],site_id:siteId,conversation_id:null}});setBriefBusy(false);if(error||data?.error){setErr(data?.message||say(error)||"WatchLog could not load this report view.");return;}setBrief(data||null);}
  useEffect(()=>{if(siteId&&tab!=="delivery")loadBrief(tab);},[siteId,tab]);
  function chooseSite(id){setSiteId(id);setBrief(null);rememberSite(id,sites.find((s)=>s.id===id)?.name||"");history.replaceState(null,"",`/reports/?site=${encodeURIComponent(id)}`);}
  async function add(e){e.preventDefault();setBusy(true);setErr("");setNote("");const{data,error}=await supabase().rpc("wl_add_recipient_v2",{p_whatsapp:form.channel==="email"?null:form.whatsapp.trim(),p_email:form.channel==="whatsapp"?null:form.email.trim(),p_channel:form.channel,p_name:form.name.trim()||null,p_site_id:form.site_id||null});setBusy(false);if(error){setErr(say(error));return;}if(data?.created===false)setNote(data.note||"Those report details are already saved.");else{setNote("Report recipient added.");setForm({whatsapp:"",email:"",channel:"whatsapp",name:"",site_id:""});}load();}
  async function toggle(id,enabled){const{error}=await supabase().rpc("wl_set_recipient",{p_id:id,p_enabled:!enabled});if(error)setErr(say(error));else load();}
  async function remove(id){if(!confirm("Remove this report recipient?"))return;const{error}=await supabase().rpc("wl_remove_recipient",{p_id:id});if(error)setErr(say(error));else load();}

  return <div className="shell"><Nav active="Reports" email={email} currentSiteId={siteId}/><main className="main">
    <header className="target-page-head"><div><div className="target-eyebrow">Management intelligence</div><h1>Reports</h1><p>See the actual WatchLog intelligence first. Delivery settings stay available without dominating the report itself.</p></div><div className="target-actions"><select value={siteId} onChange={(e)=>chooseSite(e.target.value)} aria-label="Select report site">{sites.map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button className="ghost small" onClick={()=>loadBrief(tab)} disabled={briefBusy||tab==="delivery"}>{briefBusy?"Refreshing…":"Refresh"}</button></div></header>
    {err&&<div className="err">{err}</div>}{note&&<div className="ok-note">{note}</div>}
    <div className={ui.tabs} role="tablist" aria-label="Report views">{TABS.map(([v,l])=><button key={v} className={`${ui.tab} ${tab===v?ui.tabActive:""}`} onClick={()=>{setTab(v);setBrief(null);}}>{l}</button>)}</div>

    {tab!=="delivery"?<>{briefBusy&&!brief?<div className={ui.card}><div className="empty">Loading WatchLog intelligence…</div></div>:brief?<><section className="daily-report-card"><div className="daily-report-head"><Mark size={26}/><div><b>{selected?.name||"Selected site"} · {TABS.find(([v])=>v===tab)?.[1]} report</b><div className="muted" style={{fontSize:12,marginTop:2}}>Grounded in WatchLog site, recorder, incident and coverage data</div></div></div><div className="daily-report-body"><p style={{whiteSpace:"pre-wrap",lineHeight:1.75,margin:0}}>{brief.answer}</p></div></section>{(brief.cards||[]).map((card,i)=><BriefCard card={card} key={i}/>)}</>:<div className={ui.emptyCard}>Choose a site to load its WatchLog report.</div>}</>:<>
      <section className={ui.metricGrid}><div className={ui.metric}><div className={ui.metricValue}>{active.length}</div><div className={ui.metricLabel}>Active recipients</div></div><div className={ui.metric}><div className={ui.metricValue}>{siteDeliveries.length}</div><div className={ui.metricLabel}>Deliveries in history</div></div><div className={ui.metric}><div className={ui.metricValue}>{siteDeliveries.filter((d)=>d.status==="failed").length}</div><div className={ui.metricLabel}>Delivery issues</div></div></section>
      <div className={ui.sectionHead}><div><h2>Report recipients</h2><p>Choose who receives each site's report and by which channel.</p></div></div>
      {canManage?<div className={ui.card}><form onSubmit={add}><div className="row"><div className="field"><label>Channel</label><select value={form.channel} onChange={(e)=>setForm({...form,channel:e.target.value})}>{CHANNELS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div className="field"><label>Name</label><input value={form.name} placeholder="Operations team" onChange={(e)=>setForm({...form,name:e.target.value})}/></div><div className="field"><label>Site</label><select value={form.site_id} onChange={(e)=>setForm({...form,site_id:e.target.value})}><option value="">All sites</option>{sites.map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div></div><div className="row" style={{marginTop:14}}>{form.channel!=="email"&&<div className="field"><label>WhatsApp number</label><input required value={form.whatsapp} onChange={(e)=>setForm({...form,whatsapp:e.target.value})}/></div>}{form.channel!=="whatsapp"&&<div className="field"><label>Email address</label><input required type="email" value={form.email} onChange={(e)=>setForm({...form,email:e.target.value})}/></div>}<button className="small" disabled={busy} style={{width:"auto"}}>{busy?"Adding…":"Add recipient"}</button></div></form></div>:<div className={ui.callout}><span className={ui.statusDot}/><div><strong>Read-only report access</strong><p>Owners and Admins manage recipients. You can still review delivery history.</p></div></div>}
      <div className="panel"><div className={ui.tableWrap}>{recips===null?<div className="empty">Loading recipients…</div>:recips.length===0?<div className="empty">No recipients yet.</div>:<table><thead><tr><th>Recipient</th><th>Channel</th><th>Destination</th><th>Site</th><th>Status</th><th></th></tr></thead><tbody>{recips.map((r)=><tr key={r.id}><td><b>{r.name||"Recipient"}</b></td><td>{channelLabel(r.channel)}</td><td>{endpoint(r)}</td><td>{r.site||"All sites"}</td><td><span className={"pill "+(r.enabled?"s-ok":"s-unk")}>{r.enabled?"active":"paused"}</span></td><td>{canManage&&<div className={ui.inlineActions}><button className="ghost small" onClick={()=>toggle(r.id,r.enabled)}>{r.enabled?"Pause":"Resume"}</button><button className="btn-danger" onClick={()=>remove(r.id)}>Remove</button></div>}</td></tr>)}</tbody></table>}</div></div>
      <div className={ui.sectionHead}><div><h2>Delivery history</h2><p>See whether scheduled reports reached their recipients.</p></div></div><div className="panel"><div className={ui.tableWrap}>{siteDeliveries.length===0?<div className="empty">No report deliveries for this site yet.</div>:<table><thead><tr><th>Date</th><th>Site</th><th>Channel</th><th>To</th><th>Status</th><th>Events</th></tr></thead><tbody>{siteDeliveries.map((d,i)=><tr key={`${d.date}-${d.channel}-${i}`}><td>{humanDate(d.date)}</td><td>{d.site}</td><td>{channelLabel(d.channel)}</td><td>{d.destination}</td><td>{statusPill(d.status)}</td><td>{d.events??"-"}</td></tr>)}</tbody></table>}</div></div>
    </>}
  </main></div>;
}
