"use client";

import { useEffect, useState } from "react";
import { supabase, say } from "../../../lib/supabase";
import { AdminNav, requirePlatformAdmin } from "../admin-shell";
import styles from "../admin.module.css";

const fmt=(v)=>v?new Date(v).toLocaleString():"-";
const money=(n,c="PKR")=>n==null?"-":`${c} ${(Number(n)/100).toLocaleString()}`;

export default function Support(){
  const[admin,setAdmin]=useState(null),[ctx,setCtx]=useState(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  useEffect(()=>{(async()=>{const guard=await requirePlatformAdmin();if(!guard)return;setAdmin(guard.admin);const id=new URLSearchParams(location.search).get("session");if(!id)return;const{data,error}=await supabase().rpc("wl_platform_support_session",{p_session_id:Number(id)});if(error){setError(say(error));return;}setCtx(data);})();},[]);
  async function endSession(){if(!ctx?.id)return;setBusy(true);const{error}=await supabase().rpc("wl_platform_end_support_mode",{p_session_id:ctx.id,p_reason:"Support session completed"});setBusy(false);if(error){setError(say(error));return;}location.href=`/admin/tenants/?tenant=${ctx.tenant_id}`;}
  const customer=ctx?.customer||{},tenant=customer.tenant||{},commercial=ctx?.commercial||{},sites=customer.sites||[],members=customer.members||[];
  return <div className="shell"><AdminNav active="Support" admin={admin}/><main className="main">
    {!ctx&&!error?<div className={styles.card}><h1>Support Mode</h1><p>Start Support Mode from a customer record. The session is reason-bound, expires automatically and always keeps your WatchLog platform identity.</p><a className={styles.link} href="/admin/tenants/">Choose a customer</a></div>:<>
      <section className={styles.card} style={{borderColor:"rgba(114,212,255,.45)",marginBottom:18}}><div className={styles.actions} style={{justifyContent:"space-between",alignItems:"flex-start"}}><div><div className={styles.role}>WATCHLOG SUPPORT MODE</div><h1 style={{margin:"6px 0"}}>{tenant.name||"Customer workspace"}</h1><p style={{margin:0}}>You are viewing this customer as WatchLog Support. You have not become the customer user. Your platform identity and every supported action remain auditable.</p></div><button className="btn-danger" disabled={busy} onClick={endSession}>Exit Support Mode</button></div>{ctx&&<div className={styles.detailGrid} style={{marginTop:16}}><div className={styles.kv}><small>Reason</small><strong>{ctx.reason}</strong></div><div className={styles.kv}><small>Started</small><strong>{fmt(ctx.started_at)}</strong></div><div className={styles.kv}><small>Expires</small><strong>{fmt(ctx.expires_at)}</strong></div><div className={styles.kv}><small>Your role</small><strong>{ctx.role}</strong></div></div>}</section>
      {error&&<div className="err">{error}</div>}
      {ctx&&<>
        <div className={styles.grid4}><div className={styles.metric}><div className={styles.metricLabel}>Plan</div><div className={styles.metricValue} style={{fontSize:24,textTransform:"capitalize"}}>{tenant.plan||"-"}</div><div className={styles.metricHint}>{tenant.subscription_status||"-"}</div></div><div className={styles.metric}><div className={styles.metricLabel}>Sites</div><div className={styles.metricValue}>{sites.length}</div><div className={styles.metricHint}>{sites.reduce((n,s)=>n+Number(s.cameras||0),0)} cameras</div></div><div className={styles.metric}><div className={styles.metricLabel}>People</div><div className={styles.metricValue}>{members.length}</div><div className={styles.metricHint}>with customer access</div></div><div className={styles.metric}><div className={styles.metricLabel}>Open invoices</div><div className={styles.metricValue}>{(commercial.invoices||[]).filter(i=>!['paid','void'].includes(i.status)).length}</div><div className={styles.metricHint}>commercial follow-up</div></div></div>
        <div className={styles.twoCol}><section className={styles.card}><div className={styles.actions} style={{justifyContent:"space-between"}}><div><h2>Customer sites</h2><p className="muted">The same estate the customer is operating, shown with support-safe status.</p></div><a className={styles.link} href={`/admin/tenants/?tenant=${tenant.id}`}>Open Customer 360</a></div><div className={styles.stack}>{sites.map(s=><div className={styles.row} key={s.id}><div><strong>{s.name}</strong><small>{s.cameras} cameras · {s.analytics_rules||0} analytics setups</small></div><div style={{textAlign:"right"}}><span className={`${styles.badge} ${s.agents_online?styles.ok:styles.bad}`}>{s.agents_online?"Connected":"Offline"}</span><small style={{display:"block",marginTop:4}}>Last contact {fmt(s.last_seen_at)}</small></div></div>)}{!sites.length&&<div className={styles.empty}>No sites yet.</div>}</div></section><section className={styles.card}><h2>Customer access</h2><div className={styles.stack}>{members.map(m=><div className={styles.row} key={m.user_id}><div><strong>{m.email}</strong><small>Joined {fmt(m.joined_at)}</small></div><span className={styles.badge}>{m.role}</span></div>)}{!members.length&&<div className={styles.empty}>No customer users.</div>}</div></section></div>
        <div className={styles.twoCol}><section className={styles.card}><h2>Commercial summary</h2><div className={styles.stack}>{(commercial.invoices||[]).slice(0,6).map(i=><a className={styles.row} href={`/admin/invoices/?invoice=${i.id}`} key={i.id} style={{textDecoration:"none"}}><div><strong>{i.invoice_number}</strong><small>{i.status} · due {i.due_date}</small></div><span>{money(i.total_minor,i.currency)}</span></a>)}{!(commercial.invoices||[]).length&&<div className={styles.empty}>No invoices.</div>}</div></section><section className={styles.card}><h2>Internal support history</h2><div className={styles.stack}>{(commercial.support_notes||[]).slice(0,8).map(n=><div className={styles.row} key={n.id}><div><strong>{n.note}</strong><small>{n.created_by||"WatchLog team"} · {fmt(n.created_at)}</small></div></div>)}{!(commercial.support_notes||[]).length&&<div className={styles.empty}>No internal notes.</div>}</div></section></div>
        <section className={styles.card}><h2>What Support Mode can do</h2><p>Use Customer 360 for plan, trial, billing profile, invoices, contracts, payments, password recovery and internal notes. Operational customer data remains visible here without sharing or replacing the customer's login session.</p><div className={styles.actions}><a className={styles.link} href={`/admin/tenants/?tenant=${tenant.id}`}>Open Customer 360</a><a className={styles.link} href="/admin/operations/">Open Operations</a><a className={styles.link} href="/admin/billing/">Open Commercial</a></div></section>
      </>}
    </>}
  </main></div>;
}
