"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase, say } from "../../../lib/supabase";
import { AdminNav, requirePlatformAdmin } from "../admin-shell";
import styles from "../admin.module.css";

const fmt=(v)=>v?new Date(v).toLocaleString():"-";
const money=(n,c="PKR")=>n==null?"-":`${c} ${(Number(n)/100).toLocaleString()}`;

export default function Support(){
  const[admin,setAdmin]=useState(null),[ctx,setCtx]=useState(null),[customers,setCustomers]=useState([]),[search,setSearch]=useState(""),[selected,setSelected]=useState(""),[reason,setReason]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);

  const loadCustomers=useCallback(async(q="")=>{const{data,error}=await supabase().rpc("wl_platform_tenants",{p_search:q||null,p_status:null,p_limit:100,p_offset:0});if(error){setError(say(error));return;}setCustomers(data?.items||[]);},[]);

  useEffect(()=>{(async()=>{const guard=await requirePlatformAdmin();if(!guard)return;setAdmin(guard.admin);const id=new URLSearchParams(location.search).get("session");if(id){const{data,error}=await supabase().rpc("wl_platform_support_session",{p_session_id:Number(id)});if(error){setError(say(error));setLoading(false);return;}setCtx(data);setLoading(false);return;}await loadCustomers();setLoading(false);})();},[loadCustomers]);

  async function searchCustomers(e){e.preventDefault();setLoading(true);setError("");await loadCustomers(search.trim());setLoading(false);}
  async function startSupportMode(){if(!selected||reason.trim().length<4)return;setBusy(true);setError("");const{data,error}=await supabase().rpc("wl_platform_start_support_mode",{p_tenant_id:selected,p_reason:reason.trim()});setBusy(false);if(error){setError(say(error));return;}location.href=`/admin/support/?session=${data.id}`;}
  async function endSession(){if(!ctx?.id)return;setBusy(true);const{error}=await supabase().rpc("wl_platform_end_support_mode",{p_session_id:ctx.id,p_reason:"Support session completed"});setBusy(false);if(error){setError(say(error));return;}location.href=`/admin/tenants/?tenant=${ctx.tenant_id}`;}

  const customer=ctx?.customer||{},tenant=customer.tenant||{},commercial=ctx?.commercial||{},sites=customer.sites||[],members=customer.members||[];
  const selectedCustomer=useMemo(()=>customers.find(c=>c.id===selected),[customers,selected]);

  return <div className="shell"><AdminNav active="Support" admin={admin}/><main className="main">
    {error&&<div className="err">{error}</div>}
    {loading?<div className={styles.card}>Loading support workspace...</div>:!ctx?<>
      <div className={styles.head}><div><div className={styles.role}>WatchLog Support</div><h1>Customer support workspace</h1><p>Find a customer, record why you are helping them, then open a short-lived Support Mode session without taking over their login.</p></div></div>
      <section className={styles.card} style={{marginBottom:18}}><form className={styles.toolbar} onSubmit={searchCustomers}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customer or owner email"/><button type="submit">Search</button><span className="muted">{customers.length} shown</span></form></section>
      <div className={styles.twoCol}>
        <section className={styles.card}><h2>Choose customer</h2><div className={styles.stack}>{customers.map(c=><button key={c.id} type="button" className={styles.row} onClick={()=>setSelected(c.id)} style={{textAlign:"left",width:"100%",border:selected===c.id?"1px solid var(--color-violet-bright)":undefined,background:selected===c.id?"rgba(139,107,255,.08)":undefined}}><div><strong>{c.name}</strong><small>{c.owner_email||"No owner email"} · {c.plan} · {c.subscription_status}</small></div><div style={{textAlign:"right"}}><strong>{c.sites} site{Number(c.sites)===1?"":"s"}</strong><small>{c.agents_online}/{c.agents_total} connections online</small></div></button>)}{!customers.length&&<div className={styles.empty}>No customers match this search.</div>}</div></section>
        <section className={styles.card}><h2>Start Support Mode</h2>{selectedCustomer?<><div className={styles.kv}><small>Customer</small><strong>{selectedCustomer.name}</strong></div><p className="muted">Your platform identity stays active. The session expires automatically and is written to the audit log.</p><label>Reason for access</label><textarea minLength="4" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Customer asked for help with site setup or account configuration"/><button disabled={busy||reason.trim().length<4} onClick={startSupportMode}>{busy?"Opening...":"Open Support Mode"}</button><div className={styles.actions} style={{marginTop:14}}><a className={styles.link} href={`/admin/tenants/?tenant=${selectedCustomer.id}`}>Open Customer 360 instead</a></div></>:<div className={styles.empty}>Select a customer to begin.</div>}</section>
      </div>
      <section className={styles.card}><h2>Support principles</h2><div className={styles.detailGrid}><div className={styles.kv}><small>Identity</small><strong>Always your WatchLog admin identity</strong></div><div className={styles.kv}><small>Access</small><strong>Reason-bound and time-limited</strong></div><div className={styles.kv}><small>Audit</small><strong>Start and exit are recorded</strong></div><div className={styles.kv}><small>Customer login</small><strong>Never replaced or shared</strong></div></div></section>
    </>:<>
      <section className={styles.card} style={{borderColor:"rgba(114,212,255,.45)",marginBottom:18}}><div className={styles.actions} style={{justifyContent:"space-between",alignItems:"flex-start"}}><div><div className={styles.role}>WATCHLOG SUPPORT MODE</div><h1 style={{margin:"6px 0"}}>{tenant.name||"Customer workspace"}</h1><p style={{margin:0}}>You are viewing this customer as WatchLog Support. You have not become the customer user. Your platform identity and every supported action remain auditable.</p></div><button className="btn-danger" disabled={busy} onClick={endSession}>Exit Support Mode</button></div><div className={styles.detailGrid} style={{marginTop:16}}><div className={styles.kv}><small>Reason</small><strong>{ctx.reason}</strong></div><div className={styles.kv}><small>Started</small><strong>{fmt(ctx.started_at)}</strong></div><div className={styles.kv}><small>Expires</small><strong>{fmt(ctx.expires_at)}</strong></div><div className={styles.kv}><small>Your role</small><strong>{ctx.role}</strong></div></div></section>
      <div className={styles.grid4}><div className={styles.metric}><div className={styles.metricLabel}>Plan</div><div className={styles.metricValue} style={{fontSize:24,textTransform:"capitalize"}}>{tenant.plan||"-"}</div><div className={styles.metricHint}>{tenant.subscription_status||"-"}</div></div><div className={styles.metric}><div className={styles.metricLabel}>Sites</div><div className={styles.metricValue}>{sites.length}</div><div className={styles.metricHint}>{sites.reduce((n,s)=>n+Number(s.cameras||0),0)} cameras</div></div><div className={styles.metric}><div className={styles.metricLabel}>People</div><div className={styles.metricValue}>{members.length}</div><div className={styles.metricHint}>with customer access</div></div><div className={styles.metric}><div className={styles.metricLabel}>Open invoices</div><div className={styles.metricValue}>{(commercial.invoices||[]).filter(i=>!['paid','void'].includes(i.status)).length}</div><div className={styles.metricHint}>commercial follow-up</div></div></div>
      <div className={styles.twoCol}><section className={styles.card}><div className={styles.actions} style={{justifyContent:"space-between"}}><div><h2>Customer sites</h2><p className="muted">Current location and connection state.</p></div><a className={styles.link} href={`/admin/tenants/?tenant=${tenant.id}`}>Open Customer 360</a></div><div className={styles.stack}>{sites.map(s=><div className={styles.row} key={s.id}><div><strong>{s.name}</strong><small>{s.cameras} cameras · {s.analytics_rules||0} analytics setups</small></div><div style={{textAlign:"right"}}><span className={`${styles.badge} ${s.agents_online?styles.ok:styles.bad}`}>{s.agents_online?"Connected":"Offline"}</span><small style={{display:"block",marginTop:4}}>Last contact {fmt(s.last_seen_at)}</small></div></div>)}{!sites.length&&<div className={styles.empty}>No sites yet.</div>}</div></section><section className={styles.card}><h2>Customer access</h2><div className={styles.stack}>{members.map(m=><div className={styles.row} key={m.user_id}><div><strong>{m.email}</strong><small>Joined {fmt(m.joined_at)}</small></div><span className={styles.badge}>{m.role}</span></div>)}{!members.length&&<div className={styles.empty}>No customer users.</div>}</div></section></div>
      <div className={styles.twoCol}><section className={styles.card}><h2>Commercial summary</h2><div className={styles.stack}>{(commercial.invoices||[]).slice(0,6).map(i=><a className={styles.row} href={`/admin/invoices/?invoice=${i.id}`} key={i.id} style={{textDecoration:"none"}}><div><strong>{i.invoice_number}</strong><small>{i.status} · due {i.due_date}</small></div><span>{money(i.total_minor,i.currency)}</span></a>)}{!(commercial.invoices||[]).length&&<div className={styles.empty}>No invoices.</div>}</div></section><section className={styles.card}><h2>Internal support history</h2><div className={styles.stack}>{(commercial.support_notes||[]).slice(0,8).map(n=><div className={styles.row} key={n.id}><div><strong>{n.note}</strong><small>{n.created_by||"WatchLog team"} · {fmt(n.created_at)}</small></div></div>)}{!(commercial.support_notes||[]).length&&<div className={styles.empty}>No internal notes.</div>}</div></section></div>
      <section className={styles.card}><h2>Continue working</h2><p>Use Customer 360 for plan, trial, billing profile, invoices, contracts, payments, password recovery, account lifecycle and internal notes.</p><div className={styles.actions}><a className={styles.link} href={`/admin/tenants/?tenant=${tenant.id}`}>Open Customer 360</a><a className={styles.link} href="/admin/operations/">Open Operations</a><a className={styles.link} href="/admin/billing/">Open Commercial</a></div></section>
    </>}
  </main></div>;
}
