"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase, say } from "../../lib/supabase";
import { Nav, requireTenant } from "../shell";
import { rememberSite, selectedSiteId, withSite } from "../site-context";
import styles from "./analytics.module.css";
import ui from "../portal.module.css";

function metric(label,value,hint){return{label,value:Number(value||0).toLocaleString(),hint};}
function linePath(values,width=720,height=220,pad=18){if(!values.length)return"";const max=Math.max(1,...values);return values.map((v,i)=>{const x=pad+(i*(width-pad*2))/Math.max(1,values.length-1),y=height-pad-(v/max)*(height-pad*2);return`${i?"L":"M"}${x.toFixed(1)},${y.toFixed(1)}`;}).join(" ");}
const GOAL_LABEL={visitor_flow:"Visitor Flow",vehicle_flow:"Vehicle Flow",boundary_monitoring:"Boundary Monitoring",zone_activity:"Zone Activity",dwell:"Dwell / Time in Zone",checkout_activity:"Checkout Activity",after_hours:"After-Hours Activity"};

export default function AnalyticsOverview(){
  const[email,setEmail]=useState(""),[studio,setStudio]=useState(null),[overview,setOverview]=useState(null),[days,setDays]=useState(7),[siteId,setSiteId]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);const guard=await requireTenant();if(!guard)return;setEmail(guard.session.user.email||"");const sb=supabase();const studioRes=await sb.rpc("wl_analytics_studio");if(studioRes.error){setError(say(studioRes.error));setLoading(false);return;}const s=studioRes.data||{sites:[]};setStudio(s);let chosen=siteId;if(!chosen&&s.sites?.length){chosen=new URLSearchParams(window.location.search).get("site")||selectedSiteId()||s.sites[0].id;setSiteId(chosen);rememberSite(chosen,s.sites.find((x)=>x.id===chosen)?.name||"");}const overviewRes=await sb.rpc("wl_analytics_overview",{p_days:days,p_site_id:chosen||null});if(overviewRes.error){setError(say(overviewRes.error));setLoading(false);return;}setOverview(overviewRes.data||{summary:{},daily:[],by_rule:[]});setError("");setLoading(false);},[days,siteId]);
  useEffect(()=>{load();},[load]);
  const sites=studio?.sites||[],daily=overview?.daily||[],summary=overview?.summary||{},selected=siteId?sites.find((s)=>s.id===siteId):null,hasRetail=selected?.site_type==="retail";
  const metrics=[metric("Visitors in",summary.visitor_in,"Visitor Flow"),metric("Visitors out",summary.visitor_out,"Visitor Flow"),metric("Vehicles in",summary.vehicles_in,"Vehicle Flow"),metric("Zone entries",summary.zone_entries,"Activity zones"),metric("After hours",summary.after_hours,"Outside your selected hours"),...(hasRetail?[metric("Checkout peak",summary.checkout_peak,"People present in checkout area")]:[])];
  const coverage=useMemo(()=>sites.filter((s)=>!siteId||s.id===siteId).flatMap((s)=>(s.cameras||[]).map((c)=>({site:s.name,camera:c.name||`Camera ${c.channel}`,purpose:c.purpose,rules:(c.rules||[]).filter((r)=>r.enabled)}))),[sites,siteId]);
  const visitorPath=linePath(daily.map((d)=>Number(d.visitor_in||0))),vehiclePath=linePath(daily.map((d)=>Number(d.vehicles_in||0)));
  function choose(id){setSiteId(id);rememberSite(id,sites.find((s)=>s.id===id)?.name||"");history.replaceState(null,"",`/analytics/?site=${encodeURIComponent(id)}`);}

  return <div className="shell"><Nav active="Analytics" email={email} currentSiteId={siteId} right={<><select value={siteId} onChange={(e)=>choose(e.target.value)} aria-label="Filter analytics by site" style={{width:"100%",margin:0}}>{sites.map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={days} onChange={(e)=>setDays(Number(e.target.value))} aria-label="Analytics date range" style={{width:"100%",margin:"6px 0 0"}}><option value={1}>24 hours</option><option value={7}>7 days</option><option value={30}>30 days</option></select></>}/><main className="main">
    <div className={styles.pageHead}><div><div className={styles.subnav}><a className={styles.current} href={withSite("/analytics/",siteId)}>Overview</a><a href={withSite("/analytics/studio/",siteId)}>Analytics Setup</a><a href={withSite("/analytics/schedules/",siteId)}>Schedules</a></div><h1 style={{marginTop:22}}>Site intelligence</h1><p>Turn camera activity at {selected?.name||"this site"} into useful signals such as visitor flow, vehicle movement, zone activity and dwell time.</p></div><div className={styles.actions}>{studio?.can_manage!==false&&<a className={ui.primaryLink} href={withSite("/analytics/studio/",siteId)}>Set up analytics</a>}</div></div>
    {error&&<div className="err">{error}</div>}{loading?<div className={styles.card}>Loading intelligence for this site…</div>:<><section className={styles.grid5} aria-label="Analytics summary">{metrics.map((m)=><div className={styles.metric} key={m.label}><div className={styles.metricLabel}>{m.label}</div><div className={styles.metricValue}>{m.value}</div><div className={styles.metricHint}>{m.hint}</div></div>)}</section><section className={styles.twoCol}><div className={styles.card}><h2>Flow by day</h2>{daily.length?<><svg className={styles.chart} viewBox="0 0 720 220" role="img" aria-label="Daily visitor and vehicle flow">{[45,90,135,180].map((y)=><line key={y} x1="18" x2="702" y1={y} y2={y} className={styles.chartGrid}/>)}<path d={visitorPath} className={styles.chartVisitor}/><path d={vehiclePath} className={styles.chartVehicle}/></svg><div className={styles.legend}><span>Visitors in</span><span>Vehicles in</span></div></>:<div className={styles.empty}>No analytics insights yet. Set up a camera goal and WatchLog will begin showing activity here.</div>}</div><div className={styles.card}><h2>Analytics coverage</h2><div className={styles.coverage}>{coverage.length?coverage.slice(0,10).map((c)=><div className={styles.coverageRow} key={`${c.site}-${c.camera}`}><span className={c.rules.length?styles.dot:`${styles.dot} ${styles.dotMuted}`}/><div className={styles.grow}><strong>{c.camera}</strong><small>{c.rules.length} analytics setup{c.rules.length===1?"":"s"}</small></div><span className={styles.badge}>{(c.purpose||"custom").replaceAll("_"," ")}</span></div>):<div className={styles.empty}>No cameras are configured for analytics yet.</div>}</div></div></section><section className={styles.card}><h2>Most active analytics</h2>{(overview?.by_rule||[]).length?<table><thead><tr><th>Analytics setup</th><th>Camera</th><th>Goal</th><th>Activity</th></tr></thead><tbody>{overview.by_rule.map((r)=><tr key={r.rule_id}><td><b>{r.name}</b></td><td>{r.camera||"Camera"}</td><td>{GOAL_LABEL[r.analytic_key]||String(r.analytic_key||r.rule_type||"").replaceAll("_"," ")}</td><td>{Number(r.count||0).toLocaleString()}</td></tr>)}</tbody></table>:<div className={styles.empty}>Your analytics setups will appear here as WatchLog starts receiving activity.</div>}</section></>}
  </main></div>;
}
