#!/usr/bin/env python3
"""Regenerate the hash-locked Windows build dependency sets (Agent and Setup UI).

The release EXEs are frozen on CPython 3.12.10 / win_amd64. This resolves each
``prototype/packaging/requirements-<env>.in`` for exactly that target, without installing
anything: ``pip install --dry-run --report`` reads the wheels' metadata from the index and
reports the wheel it would install, with the index's SHA-256. The lock then names every
package (transitive dependencies included) with ``==`` and that one hash, so a build that
runs ``pip install --require-hashes --no-deps --only-binary=:all: -r <lock>`` installs
byte-identical wheels or fails.

    python tools/lock_build_deps.py                 # rewrite both locks
    python tools/lock_build_deps.py --check         # exit 1 if a lock is stale vs its .in
    python tools/lock_build_deps.py --uploaded-prior-to 2026-10-06T06:50:00Z

``--uploaded-prior-to`` reproduces the resolution as of a date (the 5.1.0 release build,
Windows Release run 134, started 2026-10-06T06:51Z). Changing a pin is a reviewed change:
edit the .in, regenerate, commit both.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGING = ROOT / "prototype" / "packaging"
ENVS = ("agent", "setup-ui")
TARGET = {"python_version": "3.12", "platform": "win_amd64", "implementation": "cp", "abi": "cp312"}
DEFAULT_CUTOFF = "2026-10-06T06:50:00Z"

_REQ = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s\\;]+)")


def canonical(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def parse_lock(path: Path) -> dict[str, tuple[str, list[str]]]:
    """{canonical name: (version, [sha256, ...])} from a hash-locked requirements file."""
    out: dict[str, tuple[str, list[str]]] = {}
    current = None
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        m = _REQ.match(line)
        if m:
            current = canonical(m.group(1))
            if current in out:
                raise ValueError(f"{path.name}: {current} is listed twice")
            out[current] = (m.group(2), [])
        for h in re.findall(r"--hash=sha256:([0-9a-f]{64})", line):
            if current is None:
                raise ValueError(f"{path.name}: hash before any requirement")
            out[current][1].append(h)
    return out


def parse_in(path: Path) -> dict[str, str | None]:
    """Top-level requirements: {canonical name: exact version or None (resolved)}."""
    out: dict[str, str | None] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        m = re.match(r"^([A-Za-z0-9][A-Za-z0-9._-]*)\s*(?:==\s*(\S+))?$", line)
        if not m:
            raise ValueError(f"{path.name}: unsupported requirement line {raw!r} (use name or name==x)")
        out[canonical(m.group(1))] = m.group(2)
    return out


def resolve(in_path: Path, cutoff: str | None) -> list[dict]:
    with tempfile.TemporaryDirectory() as tmp:
        report = Path(tmp) / "report.json"
        cmd = [sys.executable, "-m", "pip", "install", "--disable-pip-version-check", "--quiet",
               "--dry-run", "--ignore-installed", "--report", str(report),
               "--python-version", TARGET["python_version"], "--platform", TARGET["platform"],
               "--implementation", TARGET["implementation"], "--abi", TARGET["abi"],
               "--only-binary=:all:", "--target", str(Path(tmp) / "t"), "-r", str(in_path)]
        if cutoff:
            cmd += ["--uploaded-prior-to", cutoff]
        subprocess.run(cmd, check=True)
        data = json.loads(report.read_text(encoding="utf-8"))
    rows = []
    for item in data["install"]:
        meta, info = item["metadata"], item["download_info"]
        sha = (info.get("archive_info") or {}).get("hashes", {}).get("sha256")
        if not sha:
            raise SystemExit(f"index gave no sha256 for {meta['name']}")
        rows.append({"name": meta["name"], "version": meta["version"], "sha256": sha,
                     "file": info["url"].rsplit("/", 1)[-1]})
    return sorted(rows, key=lambda r: canonical(r["name"]))


def render(env: str, rows: list[dict], cutoff: str | None) -> str:
    lines = [
        f"# GENERATED by tools/lock_build_deps.py from requirements-{env}.in. Do not edit by hand.",
        "# Target: CPython 3.12.10, win_amd64 (the GitHub windows runner build interpreter).",
        f"# Resolved from packages uploaded before {cutoff or 'the time of generation'}.",
        "# Every shipped and build-time package is listed (transitive dependencies included)",
        "# with the SHA-256 of the exact wheel. Install ONLY with:",
        f"#   python -m pip install --require-hashes --no-deps --only-binary=:all: -r requirements-{env}.lock",
        "",
    ]
    for r in rows:
        lines.append(f"{r['name']}=={r['version']} \\")
        lines.append(f"    --hash=sha256:{r['sha256']}")
        lines.append(f"    # {r['file']}")
    return "\n".join(lines) + "\n"


def check(env: str) -> list[str]:
    """Problems with a committed lock that need no network: the .in pins are honoured."""
    problems = []
    lock = parse_lock(PACKAGING / f"requirements-{env}.lock")
    for name, pin in parse_in(PACKAGING / f"requirements-{env}.in").items():
        if name not in lock:
            problems.append(f"{env}: {name} is in the .in but not in the lock")
        elif pin and lock[name][0] != pin:
            problems.append(f"{env}: {name} is pinned {pin} in the .in but locked at {lock[name][0]}")
    for name, (_version, hashes) in lock.items():
        if len(hashes) != 1:
            problems.append(f"{env}: {name} must carry exactly one sha256 (has {len(hashes)})")
    return problems


# Present in every venv, never shipped, never in a lock: pip itself (the venv's bundled copy;
# its version is recorded in the build manifest instead).
_VENV_BOOTSTRAP = {"pip"}


def installed_distributions() -> dict[str, str]:
    """{canonical name: version} of every distribution visible to THIS interpreter."""
    from importlib import metadata
    out: dict[str, str] = {}
    for dist in metadata.distributions():
        name = dist.metadata.get("Name")
        if name:
            out[canonical(name)] = dist.version
    return out


def compare_installed(lock: dict[str, tuple[str, list[str]]], installed: dict[str, str]) -> list[str]:
    problems = []
    for name, (version, _hashes) in sorted(lock.items()):
        if name not in installed:
            problems.append(f"missing: {name}=={version} is locked but not installed")
        elif installed[name] != version:
            problems.append(f"different: {name} is {installed[name]}, the lock says {version}")
    for name in sorted(set(installed) - set(lock) - _VENV_BOOTSTRAP):
        problems.append(f"extra: {name}=={installed[name]} is installed but not in the lock")
    return problems


def verify_installed(lock_path: Path, record: Path | None, env_name: str) -> int:
    import hashlib
    import platform
    lock = parse_lock(lock_path)
    installed = installed_distributions()
    problems = compare_installed(lock, installed)
    for p in problems:
        print(f"LOCK MISMATCH ({env_name}): {p}")
    if record:
        record.write_text(json.dumps({
            "schema": "watchlog.build_env.v1",
            "env": env_name,
            "python": platform.python_version(),
            "python_implementation": platform.python_implementation(),
            "python_executable": sys.executable,
            "pip": installed.get("pip", ""),
            "lock_file": lock_path.name,
            "lock_sha256": hashlib.sha256(lock_path.read_bytes()).hexdigest().upper(),
            "matches_lock": not problems,
            "freeze": [f"{n}=={v}" for n, v in sorted(installed.items())],
        }, indent=2) + "\n", encoding="utf-8")
    if not problems:
        print(f"{env_name} build venv matches {lock_path.name} exactly ({len(lock)} packages)")
    return 1 if problems else 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="offline consistency check only")
    ap.add_argument("--uploaded-prior-to", default=DEFAULT_CUTOFF)
    ap.add_argument("--env", choices=ENVS, action="append")
    ap.add_argument("--verify-installed", metavar="LOCK", type=Path,
                    help="run with a build venv's python: fail unless its installed set equals LOCK")
    ap.add_argument("--record", type=Path, help="with --verify-installed: write the env record JSON")
    ap.add_argument("--env-name", default="build")
    args = ap.parse_args()
    if args.verify_installed:
        return verify_installed(args.verify_installed, args.record, args.env_name)
    envs = args.env or list(ENVS)
    if args.check:
        problems = [p for env in envs for p in check(env)]
        for p in problems:
            print("STALE:", p)
        return 1 if problems else 0
    for env in envs:
        rows = resolve(PACKAGING / f"requirements-{env}.in", args.uploaded_prior_to)
        out = PACKAGING / f"requirements-{env}.lock"
        out.write_text(render(env, rows, args.uploaded_prior_to), encoding="utf-8", newline="\n")
        print(f"wrote {out.relative_to(ROOT)} ({len(rows)} packages)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
