"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase, say } from "../../../lib/supabase";
import { AdminNav, canOperate, isOwner, requirePlatformAdmin } from "../admin-shell";
import styles from "../admin.module.css";

const fmt=(v)=>v?new Date(v).toLocaleString():"Never";
const dateOnly=(v)=>v?new Date(`${v}T00:00:00`).toLocaleDateString():"-";
const money=(n,c="PKR")=>n==null?"-":`${c} ${(Number(n)/100).toLocaleString()}`;
const today=()=>new Date().toISOString().slice(0,10);
const inDays=(days)=>{const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10);};

function Status({value}){const cls=value==="active"||value==="paid"||value==="signed"?styles.ok:value==="trialing"||value==="sent"||value==="draft"?styles.warn:value==="past_due"||value==="overdue"||value==="suspended"?styles.bad:styles.muted;return <span className={`${styles.badge} ${cls}`}>{String(value||"unknown").replaceAll("_"," ")}</span>;}

export default function Customers(){
  const[admin,setAdmin]=useState(null),[items,setItems]=useState([]),[total,setTotal]=useState(0),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[selected,setSelected]=useState(null);
  const[detail,setDetail]=useState(null),[commercial,setCommercial]=useState(null),[commercialAvailable,setCommercialAvailable]=useState(true),[lifecycle,setLifecycle]=useState(null),[lifecycleAvailable,setLifecycleAvailable]=useState(true);
  const[error,setError]=useState(""),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[trialDays,setTrialDays]=useState(14),[trialReason,setTrialReason]=useState("");
  const[plan,setPlan]=useState("starter"),[subStatus,setSubStatus]=useState("active"),[billingReason,setBillingReason]=useState(""),[supportReason,setSupportReason]=useState(""),[supportNote,setSupportNote]=useState(""),[accountReason,setAccountReason]=useState("");
  const[profile,setProfile]=useState({legal_name:"",billing_email:"",billing_address:"",tax_id:"",currency:"PKR",payment_terms_days:14,reason:""});
  const[invoice,setInvoice]=useState({description:"WatchLog subscription",quantity:1,unit_amount:"",tax_amount:"0",due_date:inDays(14),notes:"",reason:""});
  const[contract,setContract]=useState({title:"WatchLog service agreement",starts_on:today(),ends_on:"",value:"",currency:"PKR",terms:"",reason:""});
  const[payment,setPayment]=useState({invoice_id:"",amount:"",currency:"PKR",method:"Bank transfer",reference:"",note:"",reason:""});

  const loadList=useCallback(async(q=search,st=status)=>{const{data,error}=await supabase().rpc("wl_platform_tenants",{p_search:q||null,p_status:st||null,p_limit:200,p_offset:0});if(error){setError(say(error));return;}setItems(data?.items||[]);setTotal(data?.total||0);setError("");},[search,status]);
  const loadCommercial=useCallback(async(id)=>{const{data,error}=await supabase().rpc("wl_platform_commercial",{p_tenant_id:id});if(error){const msg=say(error);if(/wl_platform_commercial|function|schema cache/i.test(msg)){setCommercialAvailable(false);setCommercial(null);return;}setError(msg);return;}setCommercialAvailable(true);setCommercial(data||{});const p=data?.billing_profile||{};setProfile({legal_name:p.legal_name||"",billing_email:p.billing_email||"",billing_address:p.billing_address||"",tax_id:p.tax_id||"",currency:p.currency||"PKR",payment_terms_days:p.payment_terms_days??14,reason:""});},[]);
  const loadLifecycle=useCallback(async(id)=>{const{data,error}=await supabase().rpc("wl_platform_customer_lifecycle",{p_tenant_id:id});if(error){const msg=say(error);if(/wl_platform_customer_lifecycle|function|schema cache/i.test(msg)){setLifecycleAvailable(false);setLifecycle(null);return;}setError(msg);return;}setLifecycleAvailable(true);setLifecycle(data||null);},[]);
  const loadDetail=useCallback(async(id)=>{if(!id){setDetail(null);setCommercial(null);setLifecycle(null);return;}const{data,error}=await supabase().rpc("wl_platform_tenant",{p_tenant_id:id});if(error){setError(say(error));return;}setDetail(data);setSelected(id);setError("");await Promise.all([loadCommercial(id),loadLifecycle(id)]);},[loadCommercial,loadLifecycle]);

  useEffect(()=>{(async()=>{const guard=await requirePlatformAdmin();if(!guard)return;setAdmin(guard.admin);const id=new URLSearchParams(location.search).get("tenant");await loadList("","");if(id)await loadDetail(id);})();},[]); // eslint-disable-line react-hooks/exhaustive-deps
  async function choose(id){history.replaceState({},"",`/admin/tenants/?tenant=${id}`);await loadDetail(id);}
  async function applyFilters(e){e?.preventDefault();await loadList();}
  async function run(action){setBusy(true);setError("");setNote("");try{await action();}finally{setBusy(false);}}
  async function grantTrial(e){e.preventDefault();if(!selected)return;await run(async()=>{const{error}=await supabase().rpc("wl_platform_grant_trial",{p_tenant_id:selected,p_days:Number(trialDays),p_reason:trialReason.trim()});if(error){setError(say(error));return;}setNote(`Trial set to ${trialDays} days from today.`);setTrialReason("");await Promise.all([loadDetail(selected),loadList()]);});}
  async function overrideSubscription(e){e.preventDefault();if(!selected)return;if(!confirm(`Set this customer to ${plan} / ${subStatus}?`))return;await run(async()=>{const{error}=await supabase().rpc("wl_platform_set_subscription",{p_tenant_id:selected,p_plan:plan,p_status:subStatus,p_reason:billingReason.trim()});if(error){setError(say(error));return;}setNote(`Plan updated to ${plan} / ${subStatus}.`);setBillingReason("");await Promise.all([loadDetail(selected),loadList()]);});}
  async function setAccountStatus(next){if(!selected||accountReason.trim().length<4)return;const verb=next==="suspended"?"suspend":"reactivate";if(!confirm(`${verb[0].toUpperCase()+verb.slice(1)} this customer account?`))return;await run(async()=>{const{error}=await supabase().rpc("wl_platform_set_account_status",{p_tenant_id:selected,p_status:next,p_reason:accountReason.trim()});if(error){setError(say(error));return;}setNote(next==="suspended"?"Customer access suspended. Their data and commercial history are preserved.":"Customer access reactivated.");setAccountReason("");await Promise.all([loadDetail(selected),loadList()]);});}
  async function startSupportMode(){if(!selected)return;await run(async()=>{const{data,error}=await supabase().rpc("wl_platform_start_support_mode",{p_tenant_id:selected,p_reason:supportReason.trim()});if(error){setError(say(error));return;}location.href=`/admin/support/?session=${data.id}`;});}
  async function addSupportNote(e){e.preventDefault();if(!selected)return;await run(async()=>{const{error}=await supabase().rpc("wl_platform_add_support_note",{p_tenant_id:selected,p_note:supportNote.trim(),p_reason:`Customer support note: ${supportNote.trim().slice(0,80)}`});if(error){setError(say(error));return;}setSupportNote("");setNote("Internal support note added.");await loadCommercial(selected);});}
  async function saveProfile(e){e.preventDefault();if(!selected)return;await run(async()=>{const{error}=await supabase().rpc("wl_platform_set_billing_profile",{p_tenant_id:selected,p_legal_name:profile.legal_name,p_billing_email:profile.billing_email,p_billing_address:profile.billing_address,p_tax_id:profile.tax_id,p_currency:profile.currency,p_payment_terms_days:Number(profile.payment_terms_days),p_reason:profile.reason.trim()});if(error){setError(say(error));return;}setNote("Billing profile updated.");await loadCommercial(selected);});}
  async function createInvoice(e){e.preventDefault();if(!selected)return;await run(async()=>{const unit=Math.round(Number(invoice.unit_amount)*100),tax=Math.round(Number(invoice.tax_amount||0)*100);if(!Number.isFinite(unit)||unit<0){setError("Enter a valid invoice amount.");return;}const{data,error}=await supabase().rpc("wl_platform_create_invoice",{p_tenant_id:selected,p_due_date:invoice.due_date,p_currency:profile.currency||"PKR",p_items:[{description:invoice.description,quantity:Number(invoice.quantity),unit_amount_minor:unit}],p_tax_minor:tax,p_notes:invoice.notes||null,p_reason:invoice.reason.trim()});if(error){setError(say(error));return;}setNote(`Invoice ${data?.invoice?.invoice_number||"created"} is ready.`);setInvoice({...invoice,unit_amount:"",tax_amount:"0",notes:"",reason:""});await loadCommercial(selected);});}
  async function createContract(e){e.preventDefault();if(!selected)return;await run(async()=>{const value=contract.value===""?null:Math.round(Number(contract.value)*100);const{data,error}=await supabase().rpc("wl_platform_create_contract",{p_tenant_id:selected,p_title:contract.title,p_starts_on:contract.starts_on||null,p_ends_on:contract.ends_on||null,p_value_minor:value,p_currency:contract.currency,p_terms:contract.terms||null,p_reason:contract.reason.trim()});if(error){setError(say(error));return;}setNote(`Contract ${data?.contract?.contract_number||"created"} is ready.`);setContract({...contract,value:"",terms:"",reason:""});await loadCommercial(selected);});}
  async function recordPayment(e){e.preventDefault();if(!selected)return;await run(async()=>{const amount=Math.round(Number(payment.amount)*100);const{error}=await supabase().rpc("wl_platform_record_payment",{p_tenant_id:selected,p_invoice_id:payment.invoice_id?Number(payment.invoice_id):null,p_amount_minor:amount,p_currency:payment.currency,p_method:payment.method,p_reference:payment.reference||null,p_received_at:new Date().toISOString(),p_note:payment.note||null,p_reason:payment.reason.trim()});if(error){setError(say(error));return;}setNote("Payment recorded.");setPayment({...payment,amount:"",reference:"",note:"",reason:""});await loadCommercial(selected);});}
  async function sendPasswordReset(email){if(!email)return;await run(async()=>{const{error}=await supabase().auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/auth/reset/`});if(error){setError(say(error));return;}setNote(`Password reset email requested for ${email}.`);});}

  const t=detail?.tenant,sites=detail?.sites||[],members=detail?.members||[],selectedSummary=useMemo(()=>items.find(x=>x.id===selected),[items,selected]);
  const invoices=commercial?.invoices||[],contracts=commercial?.contracts||[],payments=commercial?.payments||[],supportNotes=commercial?.support_notes||[],accountStatus=lifecycle?.account_status||"active";

  return <div className="shell"><AdminNav active="Customers" admin={admin}/><main className="main">
    <div className={styles.head}><div><h1>Customers</h1><p>Run each WatchLog account from one place: access, plan, sites, people, billing, documents and support history.</p></div></div>{error&&<div className="err">{error}</div>}{note&&<div className="ok-note">{note}</div>}
    <form className={styles.toolbar} onSubmit={applyFilters}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customer or owner email" aria-label="Search customers"/><select value={status} onChange={e=>setStatus(e.target.value)} aria-label="Subscription status"><option value="">All subscription statuses</option><option value="trialing">Trialing</option><option value="active">Active</option><option value="past_due">Past due</option><option value="cancelled">Cancelled</option><option value="expired">Expired</option></select><button type="submit">Search</button><span className="muted">{total} customer{total===1?"":"s"}</span></form>
    <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Customer</th><th>Owner</th><th>Plan</th><th>Estate</th><th>Connections</th><th>24h activity</th><th>Last report</th></tr></thead><tbody>{items.map(x=><tr key={x.id} onClick={()=>choose(x.id)} style={{cursor:"pointer",background:selected===x.id?"rgba(139,107,255,.06)":undefined}}><td><a className={styles.link} href={`/admin/tenants/?tenant=${x.id}`} onClick={e=>{e.preventDefault();choose(x.id);}}>{x.name}</a><div style={{marginTop:6}}><Status value={x.subscription_status}/></div></td><td>{x.owner_email||"No owner"}</td><td style={{textTransform:"capitalize"}}>{x.plan}{x.requested_plan&&<div className="muted">Requested: {x.requested_plan}</div>}</td><td>{x.sites} sites<br/><span className="muted">{x.cameras} cameras</span></td><td>{x.agents_online}/{x.agents_total} online<br/><span className="muted">{fmt(x.last_seen_at)}</span></td><td>{x.incidents_24h} incidents<br/><span className="muted">{x.analytics_24h} insights</span></td><td>{fmt(x.last_report_at)}</td></tr>)}{!items.length&&<tr><td colSpan="7"><div className={styles.empty}>No customers match these filters.</div></td></tr>}</tbody></table></div>

    {t&&<div style={{marginTop:"var(--space-6)"}}>
      <div className={styles.head}><div><div className={styles.role}>Customer 360</div><h1 style={{fontSize:"var(--font-size-2xl)"}}>{t.name}</h1><p>Customer since {fmt(t.created_at)}</p></div><div className={styles.actions}>{lifecycleAvailable&&<Status value={accountStatus}/>}<Status value={t.subscription_status}/><span className={styles.badge} style={{textTransform:"capitalize"}}>{t.plan}</span></div></div>
      <section className={styles.card} style={{marginBottom:"var(--space-5)"}}><div className={styles.actions} style={{justifyContent:"space-between",alignItems:"flex-start"}}><div><h2 style={{marginBottom:4}}>Quick actions</h2><p className="muted" style={{margin:0}}>Common customer-service and commercial actions stay visible instead of being buried in separate screens.</p></div></div><div className={styles.formGrid} style={{marginTop:16}}><div className={styles.dangerBox}><h3>Support Mode</h3><p>Open an expiring customer workspace while keeping your platform identity and audit trail.</p><label>Reason</label><textarea minLength="4" value={supportReason} onChange={e=>setSupportReason(e.target.value)} placeholder="Customer called about site setup"/><button disabled={busy||supportReason.trim().length<4||!commercialAvailable} onClick={startSupportMode}>Open Support Mode</button></div><div className={styles.dangerBox}><h3>Account recovery</h3><p>Send a normal WatchLog password-recovery email to the customer owner. No temporary password is created.</p><button disabled={busy||!members.find(m=>m.role==="owner")?.email} onClick={()=>sendPasswordReset(members.find(m=>m.role==="owner")?.email)}>Send owner password reset</button></div><div className={styles.dangerBox}><h3>Customer access</h3>{!lifecycleAvailable?<p>Apply migration 0038 to manage suspension and reactivation.</p>:<><p>{accountStatus==="suspended"?"This customer is paused. Their data and commercial history are preserved.":"Temporarily pause portal access and reporting without cancelling the subscription."}</p><label>Reason</label><textarea minLength="4" value={accountReason} onChange={e=>setAccountReason(e.target.value)} placeholder={accountStatus==="suspended"?"Reason for restoring access":"Reason for pausing access"}/><button className={accountStatus==="suspended"?"":"btn-danger"} disabled={busy||!canOperate(admin?.role)||accountReason.trim().length<4} onClick={()=>setAccountStatus(accountStatus==="suspended"?"active":"suspended")}>{accountStatus==="suspended"?"Reactivate customer":"Suspend customer"}</button></>}</div></div></section>
      <div className={styles.detailGrid}><div className={styles.kv}><small>Current plan</small><strong style={{textTransform:"capitalize"}}>{t.plan}</strong></div><div className={styles.kv}><small>Customer access</small><strong style={{textTransform:"capitalize"}}>{lifecycleAvailable?accountStatus:"Migration 0038 pending"}</strong></div><div className={styles.kv}><small>Subscription</small><strong style={{textTransform:"capitalize"}}>{t.subscription_status}</strong></div><div className={styles.kv}><small>Trial ends</small><strong>{fmt(t.trial_ends_at)}</strong></div></div>

      {canOperate(admin?.role)&&<section className={styles.card} style={{marginBottom:"var(--space-5)"}}><h2>Plan and trial controls</h2><p className="muted">Every change requires a reason and is written to the platform audit log.</p><div className={styles.formGrid}><form className={styles.form} onSubmit={grantTrial}><div className={styles.dangerBox}><h3>Grant or restart trial</h3><label>Days</label><input type="number" min="1" max="90" value={trialDays} onChange={e=>setTrialDays(e.target.value)}/><label>Reason</label><textarea required minLength="4" value={trialReason} onChange={e=>setTrialReason(e.target.value)} placeholder="Commercial approval or support decision"/><button disabled={busy}>Apply trial</button></div></form>{isOwner(admin?.role)?<form className={styles.form} onSubmit={overrideSubscription}><div className={styles.dangerBox}><h3>Change customer plan</h3><div className={styles.formGrid}><div><label>Plan</label><select value={plan} onChange={e=>setPlan(e.target.value)}><option value="starter">Starter</option><option value="growth">Growth</option><option value="enterprise">Enterprise</option></select></div><div><label>Status</label><select value={subStatus} onChange={e=>setSubStatus(e.target.value)}><option value="active">Active</option><option value="past_due">Past due</option><option value="cancelled">Cancelled</option><option value="expired">Expired</option></select></div></div><label>Reason</label><textarea required minLength="4" value={billingReason} onChange={e=>setBillingReason(e.target.value)} placeholder="Payment received, approved upgrade or account decision"/><button disabled={busy}>Update plan</button></div></form>:<div className={styles.dangerBox}><h3>Plan changes</h3><p>Only the Platform Owner can change authoritative paid state. Platform Admins can manage trials and customer operations.</p></div>}</div></section>}

      <div className={styles.twoCol}><section className={styles.card}><h2>Sites</h2><div className={styles.stack}>{sites.map(s=><div className={styles.row} key={s.id}><div><strong>{s.name}</strong><small>{s.cameras} cameras · {s.analytics_rules||0} analytics setups</small><small>{(s.device_vendors||[]).filter(Boolean).join(", ")||"Camera system not identified"}</small></div><div style={{textAlign:"right"}}><span className={`${styles.badge} ${s.agents_online?styles.ok:styles.bad}`}>{s.agents_online?"Connected":"Offline"}</span><small style={{display:"block",marginTop:6,color:"var(--color-muted-dark)"}}>Last contact {fmt(s.last_seen_at)}</small></div></div>)}{!sites.length&&<div className={styles.empty}>No sites yet.</div>}</div></section><section className={styles.card}><h2>People with access</h2><div className={styles.stack}>{members.map(m=><div className={styles.row} key={m.user_id}><div><strong>{m.email}</strong><small>Joined {fmt(m.joined_at)}</small></div><div style={{textAlign:"right"}}><span className={styles.badge}>{m.role}</span><button className="ghost small" style={{display:"block",marginTop:6}} onClick={()=>sendPasswordReset(m.email)}>Send reset</button></div></div>)}{!members.length&&<div className={styles.empty}>No members.</div>}</div></section></div>

      {!commercialAvailable?<section className={styles.card}><h2>Commercial operations</h2><div className={styles.empty}>Apply migration 0037 to enable invoices, contracts, billing profiles, payments, internal notes and Support Mode.</div></section>:<>
        <div className={styles.twoCol}><section className={styles.card}><h2>Billing profile</h2><form className={styles.form} onSubmit={saveProfile}><label>Legal / billing name</label><input value={profile.legal_name} onChange={e=>setProfile({...profile,legal_name:e.target.value})}/><label>Billing email</label><input type="email" value={profile.billing_email} onChange={e=>setProfile({...profile,billing_email:e.target.value})}/><label>Billing address</label><textarea value={profile.billing_address} onChange={e=>setProfile({...profile,billing_address:e.target.value})}/><div className={styles.formGrid}><div><label>Tax / registration ID</label><input value={profile.tax_id} onChange={e=>setProfile({...profile,tax_id:e.target.value})}/></div><div><label>Payment terms (days)</label><input type="number" min="0" max="365" value={profile.payment_terms_days} onChange={e=>setProfile({...profile,payment_terms_days:e.target.value})}/></div></div><label>Reason</label><textarea required minLength="4" value={profile.reason} onChange={e=>setProfile({...profile,reason:e.target.value})} placeholder="Customer billing details confirmed"/><button disabled={busy||!canOperate(admin?.role)}>Save billing profile</button></form></section><section className={styles.card}><h2>Internal support notes</h2><form className={styles.form} onSubmit={addSupportNote}><textarea required minLength="2" value={supportNote} onChange={e=>setSupportNote(e.target.value)} placeholder="Internal note visible only to WatchLog platform staff"/><button disabled={busy}>Add note</button></form><div className={styles.stack} style={{marginTop:14}}>{supportNotes.slice(0,8).map(n=><div className={styles.row} key={n.id}><div><strong>{n.note}</strong><small>{n.created_by||"WatchLog team"} · {fmt(n.created_at)}</small></div></div>)}{!supportNotes.length&&<div className={styles.empty}>No internal notes yet.</div>}</div></section></div>
        <div className={styles.twoCol}><section className={styles.card}><h2>Create invoice</h2><form className={styles.form} onSubmit={createInvoice}><label>Description</label><input required value={invoice.description} onChange={e=>setInvoice({...invoice,description:e.target.value})}/><div className={styles.formGrid}><div><label>Quantity</label><input type="number" min="0.01" step="0.01" value={invoice.quantity} onChange={e=>setInvoice({...invoice,quantity:e.target.value})}/></div><div><label>Unit amount ({profile.currency||"PKR"})</label><input type="number" min="0" step="0.01" required value={invoice.unit_amount} onChange={e=>setInvoice({...invoice,unit_amount:e.target.value})}/></div></div><div className={styles.formGrid}><div><label>Tax ({profile.currency||"PKR"})</label><input type="number" min="0" step="0.01" value={invoice.tax_amount} onChange={e=>setInvoice({...invoice,tax_amount:e.target.value})}/></div><div><label>Due date</label><input type="date" min={today()} required value={invoice.due_date} onChange={e=>setInvoice({...invoice,due_date:e.target.value})}/></div></div><label>Customer note</label><textarea value={invoice.notes} onChange={e=>setInvoice({...invoice,notes:e.target.value})}/><label>Audit reason</label><textarea required minLength="4" value={invoice.reason} onChange={e=>setInvoice({...invoice,reason:e.target.value})} placeholder="Monthly subscription invoice"/><button disabled={busy||!canOperate(admin?.role)}>Generate invoice</button></form></section><section className={styles.card}><h2>Create contract</h2><form className={styles.form} onSubmit={createContract}><label>Title</label><input required value={contract.title} onChange={e=>setContract({...contract,title:e.target.value})}/><div className={styles.formGrid}><div><label>Starts</label><input type="date" value={contract.starts_on} onChange={e=>setContract({...contract,starts_on:e.target.value})}/></div><div><label>Ends</label><input type="date" value={contract.ends_on} onChange={e=>setContract({...contract,ends_on:e.target.value})}/></div></div><label>Contract value ({contract.currency})</label><input type="number" min="0" step="0.01" value={contract.value} onChange={e=>setContract({...contract,value:e.target.value})}/><label>Commercial terms</label><textarea rows="7" value={contract.terms} onChange={e=>setContract({...contract,terms:e.target.value})} placeholder="Scope, billing terms, support, renewal and any approved commercial conditions."/><label>Audit reason</label><textarea required minLength="4" value={contract.reason} onChange={e=>setContract({...contract,reason:e.target.value})} placeholder="New service agreement"/><button disabled={busy||!canOperate(admin?.role)}>Generate contract</button></form></section></div>
        <section className={styles.card}><h2>Invoices</h2><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Invoice</th><th>Status</th><th>Issued</th><th>Due</th><th>Total</th><th></th></tr></thead><tbody>{invoices.map(i=><tr key={i.id}><td><strong>{i.invoice_number}</strong></td><td><Status value={i.status}/></td><td>{dateOnly(i.issue_date)}</td><td>{dateOnly(i.due_date)}</td><td>{money(i.total_minor,i.currency)}</td><td><a className={styles.link} href={`/admin/invoices/?invoice=${i.id}`}>Open / print</a></td></tr>)}{!invoices.length&&<tr><td colSpan="6"><div className={styles.empty}>No invoices yet.</div></td></tr>}</tbody></table></div></section>
        <section className={styles.card}><h2>Contracts</h2><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Contract</th><th>Status</th><th>Period</th><th>Value</th><th></th></tr></thead><tbody>{contracts.map(c=><tr key={c.id}><td><strong>{c.contract_number}</strong><div className="muted">{c.title}</div></td><td><Status value={c.status}/></td><td>{dateOnly(c.starts_on)} → {dateOnly(c.ends_on)}</td><td>{money(c.value_minor,c.currency)}</td><td><a className={styles.link} href={`/admin/contracts/?contract=${c.id}`}>Open / print</a></td></tr>)}{!contracts.length&&<tr><td colSpan="5"><div className={styles.empty}>No contracts yet.</div></td></tr>}</tbody></table></div></section>
        <section className={styles.card}><h2>Record payment</h2><form className={styles.form} onSubmit={recordPayment}><div className={styles.formGrid}><div><label>Invoice (optional)</label><select value={payment.invoice_id} onChange={e=>setPayment({...payment,invoice_id:e.target.value})}><option value="">Unallocated payment</option>{invoices.filter(i=>i.status!=="void"&&i.status!=="paid").map(i=><option key={i.id} value={i.id}>{i.invoice_number} · {money(i.total_minor,i.currency)}</option>)}</select></div><div><label>Amount ({payment.currency})</label><input type="number" min="0.01" step="0.01" required value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})}/></div></div><div className={styles.formGrid}><div><label>Method</label><input required value={payment.method} onChange={e=>setPayment({...payment,method:e.target.value})}/></div><div><label>Reference</label><input value={payment.reference} onChange={e=>setPayment({...payment,reference:e.target.value})}/></div></div><label>Internal note</label><input value={payment.note} onChange={e=>setPayment({...payment,note:e.target.value})}/><label>Audit reason</label><textarea required minLength="4" value={payment.reason} onChange={e=>setPayment({...payment,reason:e.target.value})} placeholder="Payment verified against bank statement"/><button disabled={busy||!canOperate(admin?.role)}>Record payment</button></form><div className={styles.stack} style={{marginTop:16}}>{payments.slice(0,10).map(p=><div className={styles.row} key={p.id}><div><strong>{money(p.amount_minor,p.currency)} · {p.method}</strong><small>{p.reference||"No reference"} · {fmt(p.received_at)}</small></div></div>)}</div></section>
      </>}
      <div className={styles.twoCol}><section className={styles.card}><h2>Reporting and analytics</h2><div className={styles.detailGrid}><div className={styles.kv}><small>Report recipients</small><strong>{(detail.report_recipients||[]).filter(r=>r.enabled).length}</strong></div><div className={styles.kv}><small>Analytics setups</small><strong>{detail.analytics?.rules||0}</strong></div><div className={styles.kv}><small>Insights, 30d</small><strong>{detail.analytics?.measurements_30d||0}</strong></div></div></section><section className={styles.card}><h2>Recent payment history</h2><div className={styles.stack}>{(detail.transactions||[]).map(p=><div className={styles.row} key={p.id}><div><strong>{p.plan||"Payment"} · {money(p.amount_minor,p.currency)}</strong><small>{fmt(p.created_at)}</small></div><Status value={p.status}/></div>)}{!(detail.transactions||[]).length&&<div className={styles.empty}>No provider transactions.</div>}</div></section></div>
      <section className={styles.card}><h2>Recent platform actions</h2><div className={styles.audit}>{(detail.audit||[]).map((a,i)=><div className={styles.auditItem} key={`${a.created_at}-${i}`}><div className={styles.auditTop}><strong>{String(a.action).replaceAll("_"," ")}</strong><span className={styles.role}>{a.actor_role}</span></div><div className={styles.auditReason}>{a.reason} · {fmt(a.created_at)}</div></div>)}{!(detail.audit||[]).length&&<div className={styles.empty}>No platform actions for this customer.</div>}</div></section>
    </div>}
  </main></div>;
}
