"use client";

import { useCallback, useEffect, useState } from "react";
import { supabase, say } from "../../lib/supabase";
import { Nav, requireTenant } from "../shell";
import { rememberSite, selectedSiteId } from "../site-context";

function human(v){if(!v)return"";return String(v).replaceAll("_"," ").replace(/^./,(c)=>c.toUpperCase());}
function ago(ts){if(!ts)return"never";const s=Math.max(0,Math.round((Date.now()-Date.parse(ts))/1000));if(s<60)return`${s}s ago`;if(s<3600)return`${Math.round(s/60)}m ago`;if(s<86400)return`${Math.round(s/3600)}h ago`;return`${Math.round(s/86400)}d ago`;}
function capView(cap){const v=cap.verdict,e=cap.evidence_class;if(v==="supported"&&e==="FIELD_VERIFIED")return{cls:"s-ok",label:"Configurable",note:"Verified on your device",action:"configure"};if(v==="supported")return{cls:"s-warn",label:"Documented",note:"Per datasheet — verify on your device first",action:"verify"};if(v==="by_camera")return{cls:"s-unk",label:"Camera-side",note:"Configured on the camera, not the recorder",action:"none"};if(v==="unsupported")return{cls:"s-bad",label:"Not available",note:cap.constraints||"Not supported by this recorder",action:"disabled"};return{cls:"s-unk",label:"Not verified",note:"Run a check to confirm on your device",action:"check"};}
function reachPill(v,ok,bad){if(v===true)return <span className="pill s-ok">{ok}</span>;if(v===false)return <span className="pill s-bad">{bad}</span>;return <span className="pill s-unk">not verified</span>;}

export default function SiteControl(){
  const[email,setEmail]=useState(""),[sites,setSites]=useState([]),[siteId,setSiteId]=useState(""),[diag,setDiag]=useState(null),[ctx,setCtx]=useState(null),[onb,setOnb]=useState(null),[error,setError]=useState(""),[msg,setMsg]=useState("");
  const loadSite=useCallback(async(sid)=>{const sb=supabase();const[d,c,o]=await Promise.all([sb.rpc("wl_my_site_diagnosis",{p_site_id:sid}),sb.rpc("wl_my_site_context",{p_site_id:sid}),sb.rpc("wl_onboarding_status",{p_site_id:sid})]);if(d.error){setError(say(d.error));return;}setError("");setDiag(d.data||null);setCtx(c.data||null);setOnb(o.data||null);},[]);
  const load=useCallback(async()=>{const guard=await requireTenant();if(!guard)return;setEmail(guard.session.user.email||"");const sb=supabase();const s=await sb.rpc("wl_sites");if(s.error){setError(say(s.error));return;}const list=s.data||[];setSites(list);const preferred=new URLSearchParams(window.location.search).get("site")||selectedSiteId()||list[0]?.id||"";if(preferred){setSiteId(preferred);rememberSite(preferred,list.find((x)=>x.id===preferred)?.name||"");await loadSite(preferred);}},[loadSite]);
  useEffect(()=>{load();},[load]);
  async function pick(e){const sid=e.target.value;setSiteId(sid);rememberSite(sid,sites.find((s)=>s.id===sid)?.name||"");history.replaceState(null,"",`/site-control/?site=${encodeURIComponent(sid)}`);setDiag(null);await loadSite(sid);}
  async function saveType(e){const t=e.target.value;const r=await supabase().rpc("wl_upsert_site_context",{p_site_id:siteId,p_site_type:t});if(r.error)setError(say(r.error));else{setMsg("Business context saved.");await loadSite(siteId);setTimeout(()=>setMsg(""),2500);}}

  const rec=diag?.recorder||{},conn=diag?.connectivity||{},caps=diag?.capabilities||[],cams=diag?.cameras||[],tiers=diag?.tiers||{},faults=diag?.faults||[],cov=diag?.coverage||{};
  const explicitEnabled=diag?.site_control_enabled??diag?.flags?.site_control_enabled??diag?.enabled;
  const controlAvailable=explicitEnabled!==false;

  return <div className="shell"><Nav active="Site Control" email={email} currentSiteId={siteId}/><main className="main">
    <header className="target-page-head"><div><div className="target-eyebrow">Advanced Site Control</div><h1>Diagnose recorder capabilities safely.</h1><p>WatchLog reads what the selected recorder can do and never exposes raw device commands or credentials.</p></div>{sites.length>1&&<select value={siteId} onChange={pick}>{sites.map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</select>}</header>
    {error&&<div className="err">{error}</div>}{msg&&<div className="ok-note">{msg}</div>}
    {!diag?<div className="panel"><div className="empty">Loading site diagnosis…</div></div>:!controlAvailable?<div className="panel"><div className="empty"><b>Managed recorder controls aren't enabled for this site.</b><p className="muted">You can still use WatchLog AI, Site Health and Analytics. Advanced recorder changes remain unavailable until this site is explicitly enabled.</p></div></div>:<>
      <div className="panel"><div className="target-panel-title"><div><h2>Recorder</h2><p>Current recorder identity and verification state.</p></div></div><table><tbody><tr><td>Identity</td><td>{rec.identified?`${rec.vendor} ${rec.model}`:<span className="pill s-unk">not identified yet</span>}</td></tr><tr><td>Connection</td><td>{reachPill(conn.agent_online,"online","offline")} <span className="muted">{conn.last_seen?`· last seen ${ago(conn.last_seen)}`:""}</span></td></tr><tr><td>Clock / NTP</td><td><span className="pill s-unk">not verified</span> <span className="muted">· confirmed by a Site Control read, never assumed</span></td></tr><tr><td>Monitoring coverage</td><td>{cov.coverage_ratio!=null?`${Math.round(cov.coverage_ratio*100)}% of today verified`:<span className="pill s-unk">not verified</span>}</td></tr></tbody></table></div>

      <div className="panel"><div className="target-panel-title"><div><h2>Cameras & current faults</h2><p>Only configured cameras should count toward expected health.</p></div></div>{cams.length?<table><thead><tr><th>Channel</th><th>Camera</th><th>Purpose</th><th>Status</th></tr></thead><tbody>{cams.map((c)=><tr key={c.channel}><td className="mono">{c.channel}</td><td>{c.name}</td><td className="muted">{c.purpose||""}</td><td>{c.video_loss?<span className="pill s-bad">video loss</span>:c.health_state==="operational"?<span className="pill s-ok">ok</span>:c.health_state==="unknown"?<span className="pill s-unk">not verified</span>:<span className="pill s-warn">{human(c.health_state)}</span>}</td></tr>)}</tbody></table>:<div className="empty">No configured cameras yet.</div>}{faults.length>0&&<p className="muted" style={{padding:"0 18px 16px"}}>{faults.length} camera{faults.length===1?"":"s"} currently need attention.</p>}</div>

      <div className="panel"><div className="target-panel-title"><div><h2>Recorder capabilities</h2><p>Unknown remains unconfirmed. Documented support is not presented as field-verified.</p></div></div>{diag.capability_known?<table><thead><tr><th>Capability</th><th>Status</th><th>Evidence</th><th>Action</th></tr></thead><tbody>{caps.map((cap)=>{const view=capView(cap);const canApprove=tiers.approve,canRecommend=tiers.recommend;return <tr key={cap.capability}><td>{human(cap.capability)}</td><td><span className={"pill "+view.cls}>{view.label}</span><div className="muted" style={{fontSize:12}}>{view.note}</div></td><td className="muted">{human(cap.evidence_class)}</td><td>{view.action==="configure"?(canApprove?<button className="small">Recommend & approve</button>:canRecommend?<button className="small ghost">Recommend</button>:<span className="muted">read only</span>):view.action==="verify"||view.action==="check"?<button className="small ghost">Check on device</button>:view.action==="disabled"?<button className="small ghost" disabled title={view.note}>Not available</button>:<span className="muted">on camera</span>}</td></tr>;})}</tbody></table>:<div className="empty">This recorder is not in the capability knowledge base yet. WatchLog will not guess its support.</div>}</div>

      <div className="panel"><div className="target-panel-title"><div><h2>Business context</h2><p>Basic site context belongs here only for maintenance; first-time configuration stays in Guided Setup.</p></div></div><div style={{padding:18}}><label>Site type <select value={ctx?.site_type||""} onChange={saveType}><option value="">Choose…</option>{["office","retail","factory","restaurant","warehouse","clinic","other"].map((t)=><option key={t} value={t}>{human(t)}</option>)}</select></label>{onb&&<div style={{marginTop:14}}><div className="health-camera-list">{(onb.steps||[]).map((st)=><div className="health-camera-row" key={st.key}><i/><span>{st.label}</span><span>{st.done?<span className="pill s-ok">done</span>:<span className="pill s-unk">pending</span>}</span></div>)}</div></div>}</div></div>
    </>}
  </main></div>;
}
